README.md, src/test/elements/closeio/contacts.js
* overview section and how section to give better intro as to what `churros` is and how it works
=> updates to readme

package.json, src/core/cloud.js, src/test/platform/events/events.js, test/core/cloud.test.js
* Added integration tests for event notification webhook headers, body, and signature hash
=> Added integration tests for event notification webhooks

README.md
=> updating badges

.gitignore, src/test/platform/elements/assets/element.instance.schema.json, src/test/platform/elements/elements.js, src/test/platform/elements/instances.js, src/test/platform/elements/metadata.js
* Added element instance schema validation and encrypted config masking checks 
Closes #83
=> Added element instance test including masked encrypted values

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
* updating the template files for PRs and issues to be more obvious, per feedback from other devs
=> Template updates

src/core/cloud.js, test/core/cloud.test.js
* using ES6 function syntax for cloud.listenForEvents
* back to 100% coverage
* Closes #100
=> Using ES6 syntax for cloud.listenForEvents. Back to 100% coverage. Added event listen timeout test.

src/core/oauth.js
* SFDC was not provisioning on `circleCI` server due to firefox version...fixed
=> fixing up oauth provisioning for sfdc to provision on circleci server

CHANGELOG.md, README.md, src/cli/churros.js
* Release `v0.3.0` of `churros` - incrementing versions.
=> fixing versions

src/core/cloud.js
* Now waiting for request end before storing event and resolving listenForEvents
* Closes #112
=> Waiting until request end before resolving event listener

src/test/platform/notifications/assets/deliveries.schema.json, src/test/platform/notifications/assets/delivery.schema.json, src/test/platform/notifications/deliveries.js, src/test/platform/notifications/subscriptions.js
* Added tests for notification subscription delivery APIs
* Added tests for notification delivery failure modes - retry and queue
* Closes #97
* Closes #98
=> Notifications deliveries

src/core/cloud.js, src/core/suite.js, src/test/elements/taxify/taxes.js, test/core/suite.test.js
* Adding should supportCd test
=> CE-3988 adding CD test and updating taxify tests to test delete API.

src/core/oauth.js, src/core/provisioner.js
* Now uses the `element`:`oauth.callback.url` if it's present during provisioning.  Needed for `sage200`
=> support for sage 200

src/test/platform/transformations/assets/objectDefinition.schema.json, src/test/platform/transformations/assets/objectDefinitions.schema.json, src/test/platform/transformations/assets/transformation.schema.json, src/test/platform/transformations/assets/transformations.schema.json, src/test/platform/transformations/transformations.js
* Added CRUD tests for objects/definitions and transformations API at organization, account, and instance levels
* Added basic payload transformation tests for a custom object
* Closes #128
=> Added basic objects/definitions and transformations tests

src/test/platform/elements/assets/common.js, src/test/platform/elements/assets/element.configuration.schema.json, src/test/platform/elements/assets/element.configurations.schema.json, src/test/platform/elements/assets/element.hook.schema.json, src/test/platform/elements/assets/element.hooks.schema.json, src/test/platform/elements/assets/element.model.schema.json, src/test/platform/elements/assets/element.models.schema.json, src/test/platform/elements/assets/element.parameter.schema.json, src/test/platform/elements/assets/element.parameters.schema.json, src/test/platform/elements/assets/element.resource.schema.json, src/test/platform/elements/assets/element.resources.schema.json, src/test/platform/elements/assets/element.schema.json, src/test/platform/elements/assets/elements.schema.json, src/test/platform/elements/assets/keys.schema.json, src/test/platform/elements/configuration.js, src/test/platform/elements/elements.js, src/test/platform/elements/hooks.js, src/test/platform/elements/parameters.js, src/test/platform/elements/resourceHooks.js, src/test/platform/elements/resourceModels.js, src/test/platform/elements/resourceParameters.js, src/test/platform/elements/resources.js
* Added tests for `/elements` by key and all subresources.
* Closes #120
=> Elements (by key) APIs

src/test/platform/transformations/transformations.js
* Added object definition and transformation inheritance tests
* Refactored some of the existing object definition and transformation tests
* Closes #124
=> Added transformation inheritance test

src/core/suite.js, src/test/platform/notifications/notifications.js, test/core/suite.test.js
* new test in the `notification.js` file to test for platform pagination
* new `tests.should.supportNextPagePagination(x)` function that:
* creates `x` number of objects
* paginates through each of them using our `?pageSize=1&nextPage=foo`
* deletes the objects that were created
`--verbose` output to show example:
```
$ churros test platform/notifications --verbose --test 'nextPage'
...
debug: POST /notifications with options %s
debug: POST /notifications with options %s
debug: POST /notifications with options %s
debug: POST /notifications with options %s
debug: POST /notifications with options %s
debug: finding page 1 of results for /notifications using null
debug: GET /notifications with options %s topics[]=pagination-topic, nextPage=null, pageSize=1
debug: finding page 2 of results for …
```
=> platform pagination tests for notifications

CHANGELOG.md, package.json
* Updates to `CHANGELOG.md` to reflect all changes in release `v0.4.0`
=> release v0.4.0

package.json, src/cli/churros.js
* updating versions to `v0.5.0` after `v0.4.0` release
=> update versions after release

src/test/platform/formulas/formulas.scripts.js
* New formula script test to validate that a return statement can be used in a helper function inside of a script.
=> adding new test to validate that helper function works in a v2 script

src/test/platform/formulas/assets/simple-successful-formula.json
* Updating formula tests to use the `v2` script engine to test an actual execution of a formula using `grover`.
=> changing simple-successful script step to be v2

src/core/provisioner.js, src/test/platform/elements/accounts.js, src/test/platform/elements/assets/element.accounts.schema.json, src/test/platform/elements/configuration.js, src/test/platform/elements/elements.js, src/test/platform/elements/hooks.js, src/test/platform/elements/instances.js, src/test/platform/elements/parameters.js, src/test/platform/elements/resourceHooks.js, src/test/platform/elements/resourceModels.js, src/test/platform/elements/resourceParameters.js, src/test/platform/elements/resources.js
* Added tests for all element and subresource APIs by key and ID
http://cl.ly/090J3O1d100D
* Closes #138
=> Added element APIs by key and ID tests

src/test/platform/events/events.js
* Updated event payload signature algorithm to SHA-256
* Closes #151
=> Updated event payload signature algorithm to SHA-256

src/test/elements/jira/assets/incidentComments.json, src/test/elements/jira/assets/incidents.json, src/test/elements/jira/assets/transformations.json, src/test/elements/jira/incidents.js
* Created tests for Jira /incidents/id/comments
=> Jira /incidents/id/comments and /incidents/id/attachments tests

src/test/platform/elements/accounts.js, src/test/platform/elements/elements.js
* fixing accounts and elements tests so they run
=> fixing accounts and elements tests so they run

src/test/platform/events/assets/event.schema.json, src/test/platform/events/assets/events.schema.json, src/test/platform/events/events.js
* Added tests for `/instances/events` APIs
* Refactored events tests instance creation/deletion
* Closes #154
=> Added tests for /instances/events APIs

src/test/platform/elements/instances.js
* Removed `freshdesk` references from `elements/instances` platform tests
* Closes #163
=> Replaced freshdesk with jira in elements/instances

src/test/platform/notifications/deliveries.js
* handled potential race condition a little more elegantly in the deliveries tests.
=> resiliency w notification tests

src/core/cloud.js, src/core/provisioner.js, src/test/elements/sugarcrmv2/activities.js
* fixing provisioning failure for `magento`.
* attempting to work on `sugarcrmv2` tests passing
=> element failures

CHANGELOG.md
* updates to the `CHANGELOG.md` to represent the changes made in `v0.5.0`
=> v0.5.0 changelog updates

.github/CONTRIBUTING.md
* added some best practices in contributing guide
=> best practices in contributing

README.md
* version number in readme updated
=> version updates

src/core/oauth.js
* during the `shopify` provisioning processes, there is an optional screen that seems new, where you have to "Install" the shopify app.  this optional screen is now handled properly.
* Closes #182
=> handling extra, optional, screen in shopify oauth process

src/cli/churros-props.js, src/cli/churros-test.js, src/core/defaults.js, src/core/props.js, src/test/elements/box/files.js, src/test/elements/lifecycle.js, src/test/platform/instances/assets/instances.schema.json, src/test/platform/notifications/assets/notification.schema.json, src/test/platform/notifications/assets/notifications.schema.json, src/test/platform/notifications/assets/subscription.schema.json, src/test/platform/notifications/notifications.js, src/test/platform/transformations/assets/transformations.schema.json
* validating plural responses properly for notification tests
* retroactively following best practices by leveraging es6 string templates
* Closes #87
=> validate plural responses in notifications properly

test/core/server.test.js
* testing those two lines in the `server` module so we can see that 100% again :100:
=> testing those two lines in the server

package.json, src/test/platform/usage/assets/analytics.schema.json, src/test/platform/usage/assets/usage.schema.json, src/test/platform/usage/usage.js
* Added platform tests for /usage APIs
=> Added platform tests for /usage APIs

src/test/elements/sage200/invoices.js
* Closing my dev. complete for Sage200, I noticed an error with the invoices churros test. Due date field is now conflicting with current date. Just removed it (optional field)
=> Test fail fix

src/core/suite.js, src/test/platform/formulas/assets/invalid.formula.json, src/test/platform/formulas/formulas.steps.js
* tests to ensure formula step properties are being validated properly
=> new formula step tests to make sure properties are being validated

package.json, src/core/tools.js, src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/complex-successful-formula-instance.json, src/test/platform/formulas/assets/complex-successful-formula.json, src/test/platform/formulas/assets/script-with-on-failure-successful-formula-instance.json, src/test/platform/formulas/assets/script-with-on-failure-successful-formula.json, src/test/platform/formulas/executions.js, test/core/tools.test.js
* Flattened existing Formula execution tests so they're easier to read
* New `wait.upTo(x).for(lambda)` functionality, used currently to wait for Formula executions to complete
* Migrated remaining test from Robot.  They're all in Churros now :tada:
=> ifAnd more formula tests

src/test/elements/shopify/addresses.js, src/test/elements/shopify/assets/fulfillment-events.json, src/test/elements/shopify/assets/paymentCapture.json, src/test/elements/shopify/assets/paymentRefund.json, src/test/elements/shopify/assets/riskCreate.json, src/test/elements/shopify/collects.js, src/test/elements/shopify/custom-collections.js, src/test/elements/shopify/fulfillment-events.js, src/test/elements/shopify/fulfillments.js, src/test/elements/shopify/metafields.js, src/test/elements/shopify/payments.js, src/test/elements/shopify/refunds.js, src/test/elements/shopify/risks.js
-- Shopify element hardening Churros Test
-- Added tests for below resources:
* Collect
* CustomCollection
* CustomerAddress
* Fulfillment
* FulfillmentEvent
* Metafield
* Order Risks
* Refund
* Transaction
=> CE-4193 Shopify element hardening Churros Test Cases

src/test/elements/chargebee/assets/transformations.json, src/test/elements/chargebee/customers.js, src/test/elements/chargebee/plans.js, src/test/elements/chargebee/transactions.js
Chargebee Element Churros Tests
Added tests for below resources:
* customers
* plans
* transactions
=> CE-4291 Chargebee Churros Tests

src/test/platform/formulas/formula.instances.js
* added a new test to `PUT` a formula instance
=> added test to update a formula instance

src/test/platform/events/events.js
* Checking for duplicate event IDs in events platform test
=> Checking for duplicate event IDs in events platform test

src/test/elements/mysql/assets/contacts.json, src/test/elements/mysql/assets/transformations.json, src/test/elements/mysql/contacts.js, src/test/elements/mysql/query.js
* Churros Tests for MySql Element
churros test elements/mysql
contacts
✓ should allow CRUDS for /hubs/db/contacts (8518ms)
✓ should support searching /hubs/db/contacts by id (7880ms)
✓ should allow paginating with page and pageSize /hubs/db/contacts (2394ms)
query
✓ should allow POST for /hubs/db/query (4673ms)
4 passing (31s)
* Closes #CE-4294
=> CE-4294 Tests for MySql Element

src/test/platform/formulas/formulas.config.js
* new formula tests that validate that when a variable (config) has its key updated, than any trigger or steps that were relying on that variable are also updated
=> new tests to verify that updating a config updates any dependent trigger or steps too

src/test/elements/sailthru/assets/templates.json, src/test/elements/sailthru/assets/transformations.json, src/test/elements/sailthru/assets/triggers.json, src/test/elements/sailthru/templates.js, src/test/elements/sailthru/triggers.js
* Sailthru templates and triggers tests
=> Adding tests to create Sailthru templates and triggers

package.json
* Include the `request` library in `package.json`, as it is used in code 😳
=> include request in package.json

src/core/provisioner.js, test/core/provisioner.test.js
* added test for new `custom` provisioning type
=> code coverage back to 100%

src/core/provisioner.js
=> remove debug

src/test/platform/formulas/executions.js
* trying to make executions more reliable
=> trying to make formula execution tests more reliable

src/test/elements/desk/organizations.js
* Updated the organizations payload to account for random POST/PATCH test failures
* Closes #217
=> Desk.com /organizations name fix

src/test/platform/formulas/assets/filter-returns-false-instance.json, src/test/platform/formulas/assets/filter-returns-false.json, src/test/platform/formulas/assets/simple-successful-formula-instance.json, src/test/platform/formulas/executions.js
* validates that a formula that has a `filter` step that returns false as the final step, still shows a successful execution
=> new formula execution test

src/test/elements/assets/object.definitions.json, src/test/elements/brandfolder/assets/assets.json, src/test/elements/brandfolder/assets/attachments.json, src/test/elements/brandfolder/assets/attachments2.json, src/test/elements/brandfolder/assets/brandfolders.json, src/test/elements/brandfolder/assets/brandfolders2.json, src/test/elements/brandfolder/assets/collections.json, src/test/elements/brandfolder/assets/transformations.json, src/test/elements/brandfolder/attachments.js, src/test/elements/brandfolder/brandfolders.js, src/test/elements/brandfolder/collections.js, src/test/elements/brandfolder/newAssets.js, src/test/elements/brandfolder/organizations.js, src/test/elements/brandfolder/sections.js
* Churros tests for Brandfolder organization, brandfolders, collections, sections, assets and attachments
* Brandfolder [API](https://api.brandfolder.com/v2/docs#nav-88) is pretty messy and involves lots of sub-resources
=> Brandfolder churros tests

src/test/elements/brandfolder/collections.js
* Uncommented paging test after I got word that Brandfolder was able to fix their 500 bug
=> Re-adding paging test after Brandfolder fixed their 500 bug

src/test/platform/elements/assets/common.js, src/test/platform/elements/elements.js
* Element Builder support for creating Database element 
```
elements
✓ should support search (255ms)
✓ should support get keys (242ms)
✓ should support CRUD by key (385ms)
✓ should support CRUD by ID (391ms)
✓ should support JDBC element CRUD by key (747ms)
✓ should support JDBC element CRUD by ID (1125ms)
✓ should support export by key (99ms)
✓ should support export by ID (177ms)
✓ should support clone by key (313ms)
✓ should support clone by ID (376ms)
✓ should support activate/deactivate by key (500ms)
✓ should support activate/deactivate by ID (498ms)
✓ should support oauth URL generation by key (97ms)
✓ should support oauth URL generation by ID (454ms)
✓ should support retrieve default transformations by key (91ms)
✓ should support retrieve default transformations by ID (165ms)
```
=> Churros tests for creating DB element

src/core/cloud.js, src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/element-request-successful-formula-instance.json, src/test/platform/formulas/assets/large-payload-successful-formula-instance.json, src/test/platform/formulas/assets/loop-successful-formula-instance.json, src/test/platform/formulas/assets/simple-error-formula-instance.json, src/test/platform/formulas/assets/simple-no-return-formula-instance.json, src/test/platform/formulas/assets/simple-successful-formula-instance.json, src/test/platform/formulas/assets/simple-timeout-formula-instance.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/formulas.load.js
* Just cleaning up some of the formula execution tests that I previously broke
=> Cleaning up the formula execution tests

src/test/elements/adobe-esign/library-documents.js, src/test/elements/adobe-esign/widgets.js
* Added the ability to support nested transformations for Voldemort Elements. Fixing the churros for the elements that were using nested transformations but were dependent on non transformed response.
=> Fixes for supporting nested transformations

src/core/oauth.js, src/test/elements/mailchimpv3/assets/campaigns.json, src/test/elements/mailchimpv3/assets/lists.json, src/test/elements/mailchimpv3/assets/transformations.json, src/test/elements/mailchimpv3/campaigns.js, src/test/elements/mailchimpv3/lists.js, src/test/elements/mailchimpv3/reports.js
* MailChimp v3.0 APIs tests for campaigns, comments, lists, contacts, fields and reports
* Closes cloud-elements/soba#1954
=> MailChimp v3.0 Tests

src/test/platform/notifications/notifications.js
* Updated notifications suite pagination schema to plural (array) schema
=> Updated notifications suite pagination schema

src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/formulas/element-request-successful-formula.json
* Leveraging the newly available `retryStatusCodes` in the formula retry tests
=> retry status codes

src/core/cloud.js, src/test/platform/formulas/scripts.js
* New tests with the default script executor changes
=> More formula script execution tests

src/test/platform/elements/elements.js
* Added POST /elements/:keyOrId/oauth/url test
=> Added POST /elements/:keyOrId/oauth/url test

src/test/elements/magentosoapv19/addresses.js, src/test/elements/magentosoapv19/assets/transformations.json, src/test/elements/magentosoapv19/customers.js, src/test/elements/magentosoapv19/products.js
* Updated magentosoapv19 to test recent changes
=> Magento SOAP v1.9 test updates

src/test/platform/formulas/executions.js, src/test/platform/formulas/load.js
* Added formula instance execution validation to all formula execution tests
=> Enhancements for formula execution tests

src/test/platform/formulas/assets/formulas/big-formula.json, src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-successful-formula.json, src/test/platform/formulas/assets/formulas/filter-returns-false.json, src/test/platform/formulas/assets/formulas/large-payload-successful-formula.json, src/test/platform/formulas/assets/formulas/loop-formula.json, src/test/platform/formulas/assets/formulas/loop-successful-formula.json, src/test/platform/formulas/assets/formulas/script-context-successful-formula.json, src/test/platform/formulas/assets/formulas/script-with-on-failure-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-error-formula.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-request-trigger-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-scheduled-trigger-formula.json, src/test/platform/formulas/assets/formulas/simple-timeout-formula.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/scripts.js
* Updated formula execution tests to not show that `mimeType` is necessary
=> Removed mimeType from formula JSON files

src/test/platform/elements/assets/common.js, src/test/platform/elements/resourceModels.js
* Ability to define model for the request body
=> Resource Model changes to support requestSwagger

src/test/platform/formulas/assets/formulas/big-formula.json, src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-successful-formula.json, src/test/platform/formulas/assets/formulas/filter-returns-false.json, src/test/platform/formulas/assets/formulas/formula-with-invalid-configs.json, src/test/platform/formulas/assets/formulas/loop-formula.json, src/test/platform/formulas/assets/formulas/loop-successful-formula.json, src/test/platform/formulas/assets/formulas/script-context-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v2.json, src/test/platform/formulas/assets/formulas/simple-no-return-console-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-no-return-console-formula.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-v2.json, src/test/platform/formulas/assets/formulas/simple-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-request-trigger-formula.json, src/test/platform/formulas/assets/formulas/simple-timeout-formula.json, src/test/platform/formulas/executions.js
* All scripty (script, filter, notification) steps defined for the formula execution tests have been converted to v2.
* The exception is where it makes sense to continue having tests for v1, in which case the test was split into two parts, one for v1, and one for v2.
* Closes #252
=> Convert scripty formula steps to V2

src/test/elements/hireright/assets/background-checks.json, src/test/elements/hireright/assets/transformations.json, src/test/elements/hireright/background-checks.js, src/test/elements/hireright/packages.js, src/test/elements/hireright/products.js
* HireRight element tests for background checks, reports, statuses, packages and products
=> Adding tests for the HireRight element

src/core/oauth.js, src/test/elements/sageone/assets/contacts.json, src/test/elements/sageone/assets/expenses.json, src/test/elements/sageone/assets/products.json, src/test/elements/sageone/assets/sales-invoices.json, src/test/elements/sageone/assets/transformations.json, src/test/elements/sageone/bankAccounts.js, src/test/elements/sageone/contactTypes.js, src/test/elements/sageone/contacts.js, src/test/elements/sageone/expenses.js, src/test/elements/sageone/journals.js, src/test/elements/sageone/ledger-accounts.js, src/test/elements/sageone/products.js, src/test/elements/sageone/sales-invoices.js, src/test/elements/sageone/taxRates.js, src/test/elements/sageone/transactions.js
* Sage One tests for resources bankAccounts, contacts, contactTypes, expenses, journals, ledger-accounts, products, sales-invoices, taxRates and transactions
=> Sage One tests

src/test/elements/expensify/assets/transformations.json, src/test/elements/expensify/reports.js
* Tests GET /reports and change status to reimbursed 
PS: Haven't added tests for creating /reports, /expenses and /policies as they don't have a delete ability
=> Expensify Element tests

src/test/elements/wrike/folders.js
* Adding a test for Wrike /folders/{folderId}/copy API
=> adding test for Wrike to copy folders

src/test/elements/wrike/folders.js
* Updating Wrike update folder to test updating project data and metadata with spaces and special characters.
=> Wrike improved update folder test

src/cli/churros-clean.js
=> Fixed typo in CLI docs

src/core/oauth.js, src/test/elements/sagelive/assets/customers.json, src/test/elements/sagelive/assets/dimensions.json, src/test/elements/sagelive/assets/journals.json, src/test/elements/sagelive/assets/ledger-accounts.json, src/test/elements/sagelive/assets/tax-codes.json, src/test/elements/sagelive/assets/tax-rates.json, src/test/elements/sagelive/assets/tax-treatments.json, src/test/elements/sagelive/assets/transformations.json, src/test/elements/sagelive/assets/vendors.json, src/test/elements/sagelive/customers.js, src/test/elements/sagelive/dimensions.js, src/test/elements/sagelive/journals.js, src/test/elements/sagelive/ledger-accounts.js, src/test/elements/sagelive/posting-rules.js, src/test/elements/sagelive/tax-codes.js, src/test/elements/sagelive/tax-rates.js, src/test/elements/sagelive/tax-treatments.js, src/test/elements/sagelive/vendors.js
* Sage One tests for resources customers, dimensions, journals, ledger-accounts, posting-rules, tax-codes, tax-rates, tax-treatments, and vendors
=> Sage Live tests

src/test/platform/formulas/assets/formulas/simple-error-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-successful-request-trigger-formula.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/load.js, src/test/platform/formulas/sub-formula-executions.js
* A few minor cleanups in formula tests...ready to start re-factoring a lot of things to help clean up code and debug via #232
=> Minor cleanup of formula things

src/test/platform/usage/usage.js
* Added usage API test with all query parameters
=> Added usage API query parameters

src/core/oauth.js, src/test/elements/sageoneuk/assets/contacts.json, src/test/elements/sageoneuk/assets/products.json, src/test/elements/sageoneuk/assets/purchase-invoices.json, src/test/elements/sageoneuk/assets/sales-invoices.json, src/test/elements/sageoneuk/assets/transformations.json, src/test/elements/sageoneuk/bank-accounts.js, src/test/elements/sageoneuk/chart-of-accounts.js, src/test/elements/sageoneuk/contact-types.js, src/test/elements/sageoneuk/contacts.js, src/test/elements/sageoneuk/journals.js, src/test/elements/sageoneuk/ledger-accounts.js, src/test/elements/sageoneuk/products.js, src/test/elements/sageoneuk/purchase-invoices.js, src/test/elements/sageoneuk/sales-invoices.js, src/test/elements/sageoneuk/tax-rates.js, src/test/elements/sageoneuk/transactions.js
* Tests for bank-accounts, chart-of-accounts, contact-types, contacts, journals, ledger-accounts, products, purchase-invoices, sales-invoices, tax-rates and transactions.
=> Sage One UK Tests

src/test/elements/sagelive/customers.js, src/test/elements/sagelive/dimensions.js, src/test/elements/sagelive/journals.js, src/test/elements/sagelive/ledger-accounts.js, src/test/elements/sagelive/posting-rules.js, src/test/elements/sagelive/tax-codes.js, src/test/elements/sagelive/tax-rates.js, src/test/elements/sagelive/tax-treatments.js, src/test/elements/sagelive/vendors.js
* Updating Sage Hub to Accounting hub to reflect changes in soba
=> Sage Live: Update Sage Hub elements to Accounting Hub

src/test/elements/sageoneus/account-types.js, src/test/elements/sageoneus/bank-accounts.js, src/test/elements/sageoneus/contact-types.js, src/test/elements/sageoneus/contacts.js, src/test/elements/sageoneus/expenses.js, src/test/elements/sageoneus/ledger-accounts.js, src/test/elements/sageoneus/products.js, src/test/elements/sageoneus/purchase-invoices.js, src/test/elements/sageoneus/sales-invoices.js, src/test/elements/sageoneus/tax-rates.js
* Updating Sage Hub to Accounting hub to reflect changes in soba
=> Sage One US: Update Sage Hub to Accounting Hub

src/core/provisioner.js, src/test/elements/lifecycle.js
* Fixed bug that that old nuisance @bscharm left for us ...
* Closes #274
=> Fixed bug where token was not being set for all subsequent API calls

src/test/elements/sageoneus/account-types.js, src/test/elements/sageoneus/bank-accounts.js, src/test/elements/sageoneus/contact-types.js, src/test/elements/sageoneus/contacts.js, src/test/elements/sageoneus/expenses.js, src/test/elements/sageoneus/ledger-accounts.js, src/test/elements/sageoneus/products.js, src/test/elements/sageoneus/purchase-invoices.js, src/test/elements/sageoneus/sales-invoices.js, src/test/elements/sageoneus/tax-rates.js
* Move Sage One US to Sage Accounting Hub
=> Sage One US: Update Accounting Hub to Sage Accounting Hub

src/test/elements/sageoneuk/bank-accounts.js, src/test/elements/sageoneuk/chart-of-accounts.js, src/test/elements/sageoneuk/contact-types.js, src/test/elements/sageoneuk/contacts.js, src/test/elements/sageoneuk/journals.js, src/test/elements/sageoneuk/ledger-accounts.js, src/test/elements/sageoneuk/products.js, src/test/elements/sageoneuk/purchase-invoices.js, src/test/elements/sageoneuk/sales-invoices.js, src/test/elements/sageoneuk/tax-rates.js, src/test/elements/sageoneuk/transactions.js
* Move Sage One UK to Sage Accounting Hub
=> Sage One UK: Update Accounting Hub to Sage Accounting Hub

src/test/elements/sagelive/customers.js, src/test/elements/sagelive/dimensions.js, src/test/elements/sagelive/journals.js, src/test/elements/sagelive/ledger-accounts.js, src/test/elements/sagelive/posting-rules.js, src/test/elements/sagelive/tax-codes.js, src/test/elements/sagelive/tax-rates.js, src/test/elements/sagelive/tax-treatments.js, src/test/elements/sagelive/vendors.js
* Move Sage Live to Sage Accounting Hub
=> Sage Live: Update Accounting Hub to Sage Accounting Hub

src/test/platform/elements/assets/element.instance.schema.json, src/test/platform/elements/assets/element.instances.schema.json, src/test/platform/elements/instances.js, src/test/platform/formulas/executions.js
* Added new tests to validate that the `user` section comes back when retrieving an element instance.
=> Enhancements to the element instance tests

src/test/platform/formulas/assets/common.js, src/test/platform/formulas/instances.js
* New tests for scheduled formula job creation and deletion.
* Creating new formulas and instances, both active and inactive
* Updating existing formulas and instances to and from active and inactive
=> Add the tests for formula job creation and deletion

src/test/platform/events/events.js, src/test/platform/events/processing.js
* Fixed file load for event request data
=> Fixed file load for event request data

src/test/elements/assets/object.definitions.json, src/test/elements/freshbooks/assets/customers.json, src/test/elements/freshbooks/assets/transformations.json, src/test/elements/freshbooks/assets/vendors.json, src/test/elements/freshbooks/customers.js, src/test/elements/freshbooks/invoices.js, src/test/elements/freshbooks/items.js, src/test/elements/freshbooks/payments.js, src/test/elements/freshbooks/taxes.js, src/test/elements/freshbooks/vendors.js
* Moved Freshbooks existing tests to churros and added `items` and `taxes`
=> Freshbooks tests

README.md, src/cli/assets/sauce.template.json, src/core/tunnel.js, src/test/lifecycle.js, src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/formulas/basic-formula-instance.json, src/test/platform/formulas/assets/formulas/complex-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/large-payload-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/loop-formula-instance.json, src/test/platform/formulas/assets/formulas/loop-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/script-context-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/script-context-successful-formula.json, src/test/platform/formulas/assets/formulas/script-with-on-failure-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-error-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v1-single-threaded.json, src/test/platform/formulas/assets/formulas/simple-no-return-console-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-successful-formula-instance.json, src/test/platform/formulas/assets/formulas/simple-successful-formula-single-threaded.json, src/test/platform/formulas/assets/formulas/simple-successful-scheduled-trigger-formula.json, src/test/platform/formulas/assets/formulas/simple-timeout-formula-instance.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/instances.js, test/core/tunnel.test.js
* Drastic cleanup of the formula tests, specifically the `executions.js`.
> **NOTE:** There are still a few tests that could be cleaned up more but got rid of ~500 lines of code with this PR so happy with this boy scouting effort 
* Closes #240
=> Formula execution cleanup

src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/loop-successful-formula.json, src/test/platform/formulas/assets/formulas/nested-loops-formula.json, src/test/platform/formulas/executions.js
* Added test to validate that nested loops are supported in a formula
=> New formula execution test for nested loop validation

src/test/platform/formulas/executions.js
* Fixed formula execution test that relied on `event.notifiedData`
=> Fixing formula execution test that relies on event.notifiedData

src/core/cloud.js
=> Testing out doc updates

src/core/cloud.js
=> Doc update test

src/test/lifecycle.js
* Added check for events.url to override ngrok tunnel startup
* Closes #306
=> Added check for events.url to override ngrok tunnel startup

package.json, src/test/platform/docs/docs.js
* Tests to validate that our documentation endpoints return valid Swagger JSON
__Note:__ This test suite won't pass until https://github.com/cloud-elements/soba/issues/2699 is addressed.
=> Swagger verify

src/core/cloud.js, src/test/platform/docs/docs.js, src/test/platform/jobs/assets/job.json, src/test/platform/jobs/jobs.js
* Tests CRDS for the platform `/jobs` API.
=> Jobs tests

src/test/elements/freshservice/agents.js, src/test/elements/freshservice/assets/agents.json, src/test/elements/freshservice/assets/departments.json, src/test/elements/freshservice/assets/incidents.json, src/test/elements/freshservice/assets/task.json, src/test/elements/freshservice/assets/transformations.json, src/test/elements/freshservice/assets/users.json, src/test/elements/freshservice/departments.js, src/test/elements/freshservice/incidents.js, src/test/elements/freshservice/users.js
* Freshservice tests will now run in churros
=> Freshservice churros tests

src/test/elements/acton/assets/campaigns.json, src/test/elements/acton/assets/contacts.json, src/test/elements/acton/assets/contactsUpdate.json, src/test/elements/acton/assets/lists.json, src/test/elements/acton/assets/optouts.json, src/test/elements/acton/assets/subscriptiontypes.json, src/test/elements/acton/assets/transformations.json, src/test/elements/acton/campaigns.js, src/test/elements/acton/lists.js, src/test/elements/acton/optouts.js, src/test/elements/acton/subscriptiontypes.js
* Act-on tests will now run in churros
Currently 2 tests fail because the api calls are not working - Bugs have been logged in soba
=> Acton Churros Tests

src/test/elements/autotaskcrm/accounts.js, src/test/elements/autotaskcrm/assets/accounts.json, src/test/elements/autotaskcrm/assets/contacts.json, src/test/elements/autotaskcrm/assets/opportunities.json, src/test/elements/autotaskcrm/assets/products.json, src/test/elements/autotaskcrm/assets/tasks.json, src/test/elements/autotaskcrm/assets/transformations.json, src/test/elements/autotaskcrm/assets/users.json, src/test/elements/autotaskcrm/contacts.js, src/test/elements/autotaskcrm/opportunities.js, src/test/elements/autotaskcrm/products.js, src/test/elements/autotaskcrm/tasks.js, src/test/elements/autotaskcrm/users.js
* Adding Tests for autotaskcrm
There is an issue with /users tests that I believe is a bug.
=> adding autotaskcrm tests

src/test/elements/assets/documents.js, src/test/elements/connectwisecrm/assets/organizations.json, src/test/elements/connectwisecrm/organizations.js, src/test/elements/connectwisehd/assets/organizations.json, src/test/elements/connectwisehd/organizations.js, src/test/platform/instances/assets/accountTransformation.json
* Fixed tests for platform/instances
* Fixed tests for assets/documents
* Fixed tests for elements/connectwisecrm
=> Few test fixes

src/test/elements/box/files.js
Updated box test to reflect correct HTTP methods
=> Box lock unlock

src/test/platform/formulas/assets/formulas/element-request-with-configured-api-successful-formula.json, src/test/platform/formulas/assets/formulas/http-request-successful-formula.json, src/test/platform/formulas/executions.js
* Added a test for the formula `httpRequest` step type
* The test uses a configuration variable for the step `URL`, so that functionality is also implicitly tested
* Closes #264 
* Closes #344
=> Added an integration test for the HTTP request step type.

src/core/oauth.js, src/test/elements/namely/employees.js
=> Updated Namely tests

src/test/platform/usage/usage.js
* Now checking past month for `sfdc` `churros-instance` usage records in platform/usage tests
=> Minor platform/usage test updates

src/test/platform/publishing/assets/publishing.json, src/test/platform/publishing/publishing.js
* Tests for Client SDK generation and publishing
* AWS lambda generation
``` 
churros test platform/publishing
publishing
✓ should allow AWS lambda autogenerate and download for the element  (880ms)
✓ should allow delete of the element created for lambda autogenerate (194ms)
2 passing (2s)
```
=> Tests for generating and publishing client sdk

src/test/platform/publishing/publishing.js
* Update the publishing payload from `to` to `type`
=> updated publishing payload

src/test/elements/assets/object.definitions.json, src/test/elements/intacct/assets/contactsPatch.json, src/test/elements/intacct/assets/transformations.json, src/test/elements/intacct/bills.js, src/test/elements/intacct/classes.js, src/test/elements/intacct/contacts.js, src/test/elements/intacct/customers.js, src/test/elements/intacct/departments.js, src/test/elements/intacct/employees.js, src/test/elements/intacct/invoices.js, src/test/elements/intacct/items.js, src/test/elements/intacct/journals.js, src/test/elements/intacct/ledger-accounts.js, src/test/elements/intacct/locations.js, src/test/elements/intacct/payments.js, src/test/elements/intacct/projects.js, src/test/elements/intacct/purchase-orders.js, src/test/elements/intacct/sales-orders.js, src/test/elements/intacct/terms.js, src/test/elements/intacct/transactions.js, src/test/elements/intacct/vendors.js, src/test/elements/intacct/vouchers.js, src/test/elements/intacct/warehouses.js
Intacct. Element Churros Tests
Added tests for below resources:
* Bills
* Classes
* Contacts
* Customers
* Departments
* Employees
* Invoices
* Items
* Journals
* Ledger-accounts
* Locations
* Payments
* Projects
* Purchase-orders
* Sales-orders
* Terms
* Transactions
* Vendors
* Vouchers
* Warehouses
=> Intacct. Element Churros Tests

src/test/platform/formulas/instances.js
* Added a test for the new formula/instances?elementInstanceId API
* Closes cloud-elements/soba#2764
=> Added a test for formula instance API

src/test/platform/publishing/assets/db-publishing.json, src/test/platform/publishing/publishing.js
* Tests for DB lambda publishing
```  publishing
✓ should allow AWS lambda autogenerate and download for the element  (2277ms)
✓ should allow AWS database lambda autogenerate and download for the element  (269ms)
```
=> DB lambda publishing tests

src/test/platform/formulas/assets/formulas/sub-formula-executions/sub-formula-duplicate-step.json, src/test/platform/formulas/sub-formula-executions.js
* Adding a test for a subformula containing a step with the same name as the on-success step in the parent on the formula step
=> sub-formula duplicate stepName

src/test/platform/events/events.js, src/test/platform/events/load.js
=> Added events load test

src/test/elements/sfdc/assets/campaigns.json, src/test/elements/sfdc/assets/transformations.json, src/test/elements/sfdc/campaigns.js
* CRUDS Test for Campaings
* Closes #363
=> Added Test For Campaigns

src/test/elements/intacct/contacts.js
* Remove reliance on old query params
=> Updating contacts query for Intacct

.github/CONTRIBUTING.md
* Removed `in-review` tag reference from docs
=> CONTRIBUTING.md in-review tag reference

src/test/elements/connectwisehd/bulk.js
=> Added bulk query tests for connectwise helpdesk element

src/test/platform/formulas/instances.js
* Cleanup all formulas and formula instances in the `instances.js` test file for formulas
* Closes #370
=> Formula instance cleanup

src/test/platform/users/assets/users.schema.json, src/test/platform/users/users.js
* Added tests for all APIs that are available under the `/users` platform API
=> Migrated platform /users tests from Robot

src/core/suite.js
* Making skip actually skip as opposed to "execute immediately" as it does now
=> Fixing skip bug

src/core/oauth.js
* Dropbox can now be provisioned by an account with business and personal or just an account with personal.
> **PROTIP:** Avoid Selenium at all costs.
* Closes #334
=> Fixed Dropbox provisioning

src/core/oauth.js, src/test/platform/formulas/sub-formula-executions.js
* Added `tools.wait.upTo(10000)` for sub-formula execution tests
=> Added tools.wait in subformula execution tests as well

src/test/elements/jira/agents.js, src/test/elements/jira/assets/attach.txt, src/test/elements/jira/assets/contact.json, src/test/elements/jira/assets/field.json, src/test/elements/jira/assets/issuetype.json, src/test/elements/jira/contacts.js, src/test/elements/jira/fields.js, src/test/elements/jira/incidentTypes.js, src/test/elements/jira/incidents.js, src/test/elements/jira/priorities.js, src/test/elements/jira/statuses.js
* Jira tests for incident-types, agents, contacts, fields, priorities, incident-types, and statuses
* Fixed test for incidents
=> Jira Tests

src/test/platform/usage/usage.js
* Added coverage for platform usage tests
=> Added coverage for platform usage tests

src/test/platform/integrations/assets/integration.schema.json, src/test/platform/integrations/integrations.js
* Integrations domain model changed, updating tests per these changes.
=> Integration test updates

src/core/oauth.js, src/test/elements/actessentialsoauth/activities.js, src/test/elements/actessentialsoauth/assets/activities.json, src/test/elements/actessentialsoauth/assets/contacts.json, src/test/elements/actessentialsoauth/assets/lists.json, src/test/elements/actessentialsoauth/assets/opportunities.json, src/test/elements/actessentialsoauth/assets/todos.json, src/test/elements/actessentialsoauth/assets/transformations.json, src/test/elements/actessentialsoauth/campaigns.js, src/test/elements/actessentialsoauth/contacts.js, src/test/elements/actessentialsoauth/lists.js, src/test/elements/actessentialsoauth/opportunities.js, src/test/elements/actessentialsoauth/todos.js
=> Added tests for Act! Essentials OAuth

src/test/elements/quickbase/contacts.js
* Updating attachments to the new account
=> Quickbase attachments update

src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/simple-sub-formulas.json, src/test/platform/formulas/sub-formula-executions.js
* Tests for passing configs to sub-formulas and ensuring that if they have the same key as the parent, they do not override the parents config.
=> Tests for sub-formula configs

src/cli/churros-test.js
* When running elements or platform tests you can now specify a folder to start with. See examples for command syntax
`churros test elements --start freshbooks`
`churros test platform --start general`
* Closes #418
=> Added the ability to specify a starting point when running multiple test suites

src/test/platform/notifications/assets/delivery.schema.json
=> Added a missing value to the delivery schema status enum

src/test/platform/formulas/assets/formulas/formula-with-invalid-step-properties.json
We increased the allowable retry attempts to 5, so increasing the negative test.
=> increasing the invalid formula step retry to 6

src/test/elements/zendesk/users.js
* Fixing Zendesk user tests to use a random email
=> Making zendesk user email random

src/test/elements/actessentialsoauth/activities.js, src/test/elements/actessentialsoauth/assets/lists.json, src/test/elements/actessentialsoauth/contacts.js, src/test/elements/actessentialsoauth/lists.js, src/test/elements/actessentialsoauth/opportunities.js, src/test/elements/actessentialsoauth/todos.js, src/test/elements/assets/documents.js, src/test/elements/eloqua/contacts.js, src/test/elements/eloqua/lists.js, src/test/elements/magentov20/products-attributes.js, src/test/platform/formulas/executions.js
* Fixing failures from circleci build
=> fixing a bunch of element test failures. increasing formula timeout

src/test/elements/magentosoapv19/orders.js, src/test/elements/magentov20/products-attributes.js, src/test/elements/sharefile/folder.js, src/test/elements/sharefile/share.js, src/test/platform/formulas/load.js
=> Fixing a bunch of element test failures

src/test/elements/assets/object.definitions.json, src/test/elements/netsuitefinancev2/assets/customer-refunds.json, src/test/elements/netsuitefinancev2/assets/transformations.json, src/test/elements/netsuitefinancev2/credit-terms.js, src/test/elements/netsuitefinancev2/custom-fields.js, src/test/elements/netsuitefinancev2/customer-refunds.js, src/test/elements/netsuitefinancev2/ledger-accounts.js, src/test/elements/netsuitefinancev2/payment-methods.js, src/test/elements/netsuitefinancev2/ping.js, src/test/elements/netsuitefinancev2/tax-codes.js, src/test/elements/netsuitefinancev2/tax-rates.js
* Added churros for netsuitefinancev2 element.
=> Added churros for netsuitfinancev2

src/test/platform/bulk/bulk.js
=> Fixing bulk download to get JSON test

src/test/elements/fieldawarev2/assets/jobs.json, src/test/elements/fieldawarev2/contacts.js, src/test/elements/fieldawarev2/custom-fields.js, src/test/elements/fieldawarev2/items.js, src/test/elements/fieldawarev2/locations.js, src/test/elements/fieldawarev2/tasks.js
=> Fixing some fieldawarev2 test errors

src/test/elements/infusionsoftmarketing/notes.js, src/test/elements/infusionsoftmarketing/ping.js
* Added churros for Infusion Soft Marketing.
Added churros for GET /notes with where clause and GET /ping.
=> Added churros for Infusion Soft Marketing

src/test/elements/salesforcemarketingcloud/ping.js
Added churros for Salesforce Marketing Cloud
=> Added churros for Salesforce Marketing Cloud

src/test/elements/brighttalk/channels.js
Added tests for brighttalk
* Closes #4267
=> Added tests for BrightTALK

src/test/elements/eventmobiv1/ping.js
Updated test for eventmobiv1
GET  /ping
* Closes #4422
=> CE-4422: Updated test for eventmobiv1

src/test/elements/brandfolder/ping.js
Added churros for ping
* Closes #4423
=> CE-4423 (brandfolder v2- General) Added churros gaps

src/test/elements/dynamicscrmadfs/accounts.js, src/test/elements/dynamicscrmadfs/assets/accounts.json, src/test/elements/dynamicscrmadfs/assets/contacts.json, src/test/elements/dynamicscrmadfs/assets/leads.json, src/test/elements/dynamicscrmadfs/assets/opportunities.json, src/test/elements/dynamicscrmadfs/contacts.js, src/test/elements/dynamicscrmadfs/leads.js, src/test/elements/dynamicscrmadfs/opportunities.js
Updated Test for Dynamics to set null values and float values.
=> Updated tests for Nulls and Floats.

src/test/elements/jira/assets/notification.json, src/test/elements/jira/contacts.js, src/test/elements/jira/incidents.js
* Added churros for the notification API and changed the contacts test.
* Closes #4415
=> CE-4415 (Jira) Added churros for Jira

src/test/platform/usage/assets/usage.schema.json, src/test/platform/usage/usage.js
* Add new required fields to usage logs: `company_external_name` and `company_external_id`
=> Update usage log testing to include new fields

src/test/platform/formulas/formulas.js
* New test to validate our new `PATCH /formulas/:id` API
=> Added new formula test

src/test/elements/shopify/countries.js, src/test/elements/shopify/shipping-zones.js
* Adds Search test for `/shipping-zones`
* Adds Read & Search test `/countries`
Soba PR - https://github.com/cloud-elements/soba/pull/4370
=> Shopify - /shipping-zones & /countries

src/test/elements/sailthru/assets/transformations.json, src/test/elements/sailthru/assets/users.json, src/test/elements/sailthru/jobs.js, src/test/elements/sailthru/ping.js, src/test/elements/sailthru/users.js
Added churros for users, ping and jobs API for sailthru
GET /users, POST /users, GET /users{userId}, PATCH  GET /users{userId}, ping
* Closes #4314
=> CE-4314 (Sailthru) Added churros for users, ping and jobs API for sailthru

src/test/elements/hubspot/bulk.js
* Adds test for hubspot bulk download for change to support where clause
=> Add bulk download with where clause test for Hubspot

src/test/elements/hubspot/contacts.js, src/test/elements/mailchimpv3/campaigns.js, src/test/platform/formulas/executions.js
* Fixing failures for mailchimpv2, hubspot and formulas
=> Fix a few false failures

src/test/elements/intacct/bills.js, src/test/elements/intacct/classes.js, src/test/elements/intacct/contacts.js, src/test/elements/intacct/customers.js, src/test/elements/intacct/departments.js, src/test/elements/intacct/employees.js, src/test/elements/intacct/invoices.js, src/test/elements/intacct/items.js, src/test/elements/intacct/journals.js, src/test/elements/intacct/ledger-accounts.js, src/test/elements/intacct/locations.js, src/test/elements/intacct/payments.js, src/test/elements/intacct/ping.js, src/test/elements/intacct/projects.js, src/test/elements/intacct/purchase-orders.js, src/test/elements/intacct/sales-orders.js, src/test/elements/intacct/terms.js, src/test/elements/intacct/transactions.js, src/test/elements/intacct/vendors.js, src/test/elements/intacct/vouchers.js, src/test/elements/intacct/warehouses.js
* Updated formatting/ceql-search for intacct
=> Updated Intacct tests

src/core/provisioner.js, src/test/elements/weebly/provisioner.js, src/test/platform/elements/instances.js
* New tests for the new XSS sanitization logic for element names and tags.
=> Tests for XSS prevention

src/test/elements/sfdc/metadata.js
* Add test for additional SFDC metadata fields
=> Add test for new SFDC metadata fields

src/test/elements/assets/object.definitions.json, src/test/elements/eloqua/assets/customTest.csv, src/test/elements/eloqua/assets/eloquaCustomObject.csv, src/test/elements/eloqua/assets/transformations.json, src/test/elements/eloqua/bulk.js
* Add tests for Eloqua bulk for custom objects
=> Eloqua custom bulk

src/test/elements/freshservice/assets/comments.json, src/test/elements/freshservice/incidents.js, src/test/elements/freshservice/ping.js, src/test/elements/freshservice/users.js
* Added churros for ping, incidents and users
* POST /incidents/{incidentId}/comments
* GET /ping
* POST /users
* PATCH /users/{userId}
* Closes #4429
=> CE-4429 : FreshService

src/test/elements/abbyy/ping.js, src/test/elements/abbyy/tasks.js
Updated churros for abbyy
GET     /ping
DELETE  /task/{id}
* Closes #4427
=> CE-4427: Updated churros for abbyy

src/core/cloud.js, src/test/elements/assets/object.definitions.json, src/test/elements/sfdc/accounts.js, src/test/elements/sfdc/assets/transformations.json, src/test/elements/sfdc/contacts.js, src/test/elements/sfdc/leads.js, src/test/elements/sfdc/opportunities.js
* Fixed /notes tests and separated tests for better coverage
* Closes #573
=> Partitioning and fixing some SFDC tests

src/test/platform/formulas/assets/common.js, src/test/platform/formulas/formulas.js, src/test/platform/formulas/instances.js
* New XSS tests for formulas and formula instances.
=> XSS for formulas and formula instances

src/test/elements/amazons3/index.js, src/test/elements/amazons3/ping.js, src/test/elements/assets/documents.js
* Intitial amazon s3 tests. I verified that it works, but it needs to be further investigated for `/metadata` errors
=> Added initial amazon s3 tests

src/test/elements/sfdc/assets/transformations.json, src/test/elements/sfdc/contacts.js
=> Fix salesforce nested attachments upload test

src/test/elements/stripe/assets/charges.json, src/test/elements/stripe/assets/orders.json, src/test/elements/stripe/assets/transfers.json, src/test/elements/stripe/authenticate.js, src/test/elements/stripe/charges.js, src/test/elements/stripe/customers.js, src/test/elements/stripe/events.js, src/test/elements/stripe/orders.js, src/test/elements/stripe/payment-methods.js, src/test/elements/stripe/ping.js, src/test/elements/stripe/plans.js, src/test/elements/stripe/products.js, src/test/elements/stripe/refunds.js, src/test/elements/stripe/subscriptions.js, src/test/elements/stripe/transactions.js, src/test/elements/stripe/transfers.js
Updated churros for stripe
* Closes #4425
=> CE-4425: Updated churros for stripe

src/test/platform/elements/instances.js
* Adding a test for the `filter.response.nulls` configuration value 
* Closes #505
=> Add a test for the filter.response.nulls configuration value

src/core/cloud.js, src/core/suite.js, src/test/elements/mailjet/assets/messages.json, src/test/elements/mailjet/messages.js, src/test/elements/mailjet/ping.js, src/test/elements/mailjet/usage.js, test/core/cloud.test.js, test/core/suite.test.js
* Updated tests for Mailjet messing
* Added `test.should.supportCr()` in suite
=> Updated Mailjet Messaging tests

src/test/elements/volusion/assets/customer.json, src/test/elements/volusion/assets/order.json, src/test/elements/volusion/assets/product.json, src/test/elements/volusion/assets/transformations.json, src/test/elements/volusion/customers.js, src/test/elements/volusion/orders.js, src/test/elements/volusion/products.js
* Added Volusion tests for Orders, Products, and Customers
* Closes #612
=> Volusion Element Tests

src/test/elements/marketo/assets/attributes.json, src/test/elements/marketo/assets/external-activity.json, src/test/elements/marketo/external-activity.js
Updated churros for marketo
GET /external-activity/types
PATCH /external-activity/type/{apiName}/approve
PATCH /external-activity/type/{apiName}/attributes
POST /external-activity/type
* Closes #4566
=> CE-4566 :  Updated churros for marketo

src/test/elements/hubspotcrm/assets/contacts.json, src/test/elements/hubspotcrm/contacts.js
* Added implementation for GET /contacts/{id}/activities API.
* Fixed /Contacts CRUD APIs
* Closes #4140
=> CE-4140(hubspotcrm)

src/test/elements/autotaskhelpdesk/bulk.js, src/test/elements/autotaskhelpdesk/users.js
* Autotask Helpdesk User and bulk test fix
=> Autotask Helpdesk User and bulk test fix

src/core/suite.js
=> Only check pagination length if its not empty

src/test/elements/sharefile/files.js
* Added test for the Citrix ShareFile GET /files/{id}/links API
* Closes #626
=> Added test for the Citrix ShareFile GET /files/{id}/links API.

src/test/elements/salesforcemarketingcloud/campaigns.js, src/test/elements/salesforcemarketingcloud/contacts.js
* SalesforceMarketing cloud pagination tests
=> SalesforceMarketing cloud pagination tests

src/test/elements/googledrive/search.js
* Updated Churros test for Search Paging Soba Issue #3941
=> Updated Churros Test for Search Paging.

src/test/elements/sageoneuk/ledger-accounts.js
* bullet separated list of highlights
=> Skip creating ledger-accounts we can't delete

src/test/platform/elements/instances.js
* Tests whether it's possible to search for instances by tag
* Closes #634
=> Instances Tag Search Test

src/test/elements/zendesk/priorities.js
* Added churros for /priority API's
* Closes #4126
=> CE-4126 : Added churros for /priority API's

src/test/elements/dropboxbusiness/documentsDB.js, src/test/elements/dropboxbusiness/members.js
* Added the Churros for CD of /members
* Updated the memberId in documentDB file
* Closes #4134
=> CE-4134 dropboxbusiness (Added the churros for CD /members

src/test/elements/zuora/subscriptions.js
* Add churros for Zuora.
* GET /subscriptions/{id}
=> Zuora CE-4261

src/test/elements/netsuitecrmv2/accounts.js
* Updated Netsuite Search on Accounts to search on Custom Fields
=> Updated Netsuite Serach on Accounts to search on Custom Fields

src/test/elements/sqlserver/assets/test.json, src/test/elements/sqlserver/test.js
* Added Churros for missing API's of Microsoft SQL Server
* Closes #4120
=> CE-4120 : Added Churros for missing API's of Microsoft SQL Server

src/test/elements/etsy/assets/products.json, src/test/elements/etsy/assets/transformations.json, src/test/elements/etsy/products.js
* Added some `products` stuff for our dev. accout
=> Etsy: Adding some logic for /products

src/test/elements/netsuitecrmv2/accounts.js, src/test/elements/netsuitehcv2/assets/payroll-items.json, src/test/elements/netsuitehcv2/payroll-items.js
* Added Crud Churros For Payroll Items.
* Closes #666
=> Added Crud Churros For Payroll Items.

src/test/elements/etsy/products.js
* Added tests for CRUDS `/products`
* Added tests for US `/products/{id}/inventory`
* Added tests for S `/products-drafts`
=> Etsy updates

src/test/elements/himss/assets/mappings.json, src/test/elements/himss/mappings.js
* Added churros for the POST and DELETE /mappings APIs of HIMSS Mapping element
* Closes #5009
=> CE-5009 Churros for HIMSS Mapping element

src/core/cloud.js, src/core/suite.js, src/test/elements/marketo/activities.js, src/test/elements/marketo/external-activity.js, test/core/cloud.test.js, test/core/suite.test.js
* Added support for `supportCs`
* Fixed some tests
=> Marketo Updates

src/test/lifecycle.js, src/test/platform/transformations/assets/transformation.schema.json
* Improved validation for transformation-related tests to include the existing required fields, as well as the new `level` field that exists on a transformation field.
=> :love_letter: Added better validation for transformation fields

src/test/elements/facebooksocial/ping.js, src/test/elements/facebooksocial/user.js
* Added churros for missing resources of FacebookSocial
* Closes #4032
=> CE-4032 : Added churros for missing resources of FacebookSocial

src/test/elements/eloqua/contacts.js
added test to search by dates on Contacts. and epoch Conversion.
=> Added Churros for Searching by lastUpdatedAt

src/test/platform/elements/assets/atws.wsdl, src/test/platform/elements/elements.js
* Tests for converting WSDL to element and creating a SOAP element
=> Tests for converting WSDL to element and creating a SOAP element

src/core/oauth.js, src/test/elements/hubspot/activities.js, src/test/elements/hubspot/assets/transformations.json, src/test/elements/hubspot/assets/workflows.json, src/test/elements/hubspot/campaigns.js, src/test/elements/hubspot/contacts.js, src/test/elements/hubspot/files.js, src/test/elements/hubspot/workflows.js
* Updates and additions for updating Hubspot credentials to their new OAuth framework (issues with some calls - thus skipping for now)
=> Hubspot OAuth updates

src/test/elements/sharefile/poller.js
* bullet separated list of highlights `GET /hubs/documents/events/poll/documents?where=<whereClause>`
* Closes #703
=> Added a test for the ShareFile poller URL

src/core/suite.js
=> should fix most problems with my test

src/test/elements/zendesk/priorities.js, src/test/elements/zendesk/resourcesArticles.js
* Removed skip for priority API's and skipped resourcesArticles churros because for resourcesArticles POST method is not present
* Closes #4126
=> Removed skip for priority API's

src/test/platform/formulas/assets/formulas/bulk-transfer.json, src/test/platform/formulas/executions.js
=> Improve stream step test to verify that form data is sent correctly

src/test/elements/netsuitecrmv2/accounts.js
Updated Churros to use the correct function that utilizes where clause.
=> Updated broken churros.

src/test/elements/servicenow/accounts.js, src/test/elements/servicenow/agents.js, src/test/elements/servicenow/contacts.js, src/test/elements/servicenow/incidents.js, src/test/elements/servicenowoauth/accounts.js, src/test/elements/servicenowoauth/agents.js, src/test/elements/servicenowoauth/assets/scripts.js, src/test/elements/servicenowoauth/contacts.js, src/test/elements/servicenowoauth/incidents.js
* Updated tests to pass
* Added selenium to wake instance
=> ServiceNow updates

src/core/oauth.js
* Allow circle ci to run googledrive tests
* Closes #653
=> Should provision Google Drive in circle ci

src/test/platform/elementbuilder/assets/noendpoint_element.json, src/test/platform/elementbuilder/assets/noendpoint_instance_schema.json, src/test/platform/elementbuilder/multipleendpoint.js
* Tests for request chaining
* Tests for node `http` library use in script hooks
* Tests for node `https` library use in script hooks
* Tests for validating request chaining to limit to 3
```
elementbuilder
✓ should support calling multiple endpoint chain requests (387ms)
✓ should support calling http in hook requests (258ms)
✓ should support calling https in hook requests (2667ms)
✓ should fail if chain is more than 3 (365ms)
```
=> Element Builder multiple request chaining/ multiple endpoints

src/test/elements/sharefile/folder.js
* Test concurrent folder creation for ShareFile
* Closes #724
=> Sharefile concurrent folder creation test

src/test/elements/sharefile/folder.js
* Added a test to validate that a folder is not downloaded as a file for the Sharefile element
* Closes #728
=> Added a test to validate that a folder is not downloaded as a file for the Sharefile element

src/test/elements/hubspotcrm/contacts.js
* Paging test was broken on hubspotcrm contacts
=> Updated the paging to use nextPageToken

src/test/elements/hubspot/workflows.js, src/test/elements/magentov20/assets/orders.json, src/test/elements/magentov20/assets/products.json, src/test/elements/magentov20/orders.js, src/test/elements/magentov20/products.js
=> Updates for Magento orders

src/test/elements/connectwisecrm/assets/incidents.json, src/test/elements/connectwisecrm/assets/transformations.json, src/test/elements/connectwisecrm/incidents.js
Updated churros tests for Connectwise CRM.
CURDS for /incidents
* Closes #5271
=> Updated churros tests for Connectwise CRM

src/test/elements/sharefile/files.js
* Added a test for a 404 when the GET /files/metadata?path=<path> API for the ShareFile element
* Closes #735
=> Added a test for a 404 when the GET /files/metadata?path=<path> API for the ShareFile element

src/test/elements/googledrive/files.js
* Added New Test to export GoogleApp Files
=> Added Test for new MediaType parameter

src/test/elements/dropbox/links.js, src/test/elements/dropboxbusiness/documentsDB.js, src/test/elements/dropboxbusinessv2/documentsDB.js, src/test/elements/dropboxv2/links.js
* Added verification of proper download and view URLs for GET /files/links for all Dropbox elements
=> Dropbox GET /files/links

src/test/elements/assets/object.definitions.json, src/test/elements/expensify/assets/expenses.json, src/test/elements/expensify/assets/policies.json, src/test/elements/expensify/assets/reports.json, src/test/elements/expensify/assets/transformations.json, src/test/elements/expensify/expenses.js, src/test/elements/expensify/ping.js, src/test/elements/expensify/policies.js, src/test/elements/expensify/reports.js
Updated churros tests for Expensify
POST /expenses
GET /ping
CRS /policies
POST /reports
* Closes #5315
=> Updated churros tests for Expensify

src/test/elements/autotaskcrm/accounts.js, src/test/elements/autotaskcrm/assets/customers.json, src/test/elements/autotaskcrm/assets/transformations.json, src/test/elements/autotaskcrm/contacts.js, src/test/elements/autotaskcrm/customers.js, src/test/elements/autotaskcrm/opportunities.js, src/test/elements/autotaskcrm/ping.js, src/test/elements/autotaskcrm/tasks.js, src/test/elements/autotaskcrm/users.js
Updated churros test for Autotask CRM
Added 'nextPage' test cases for all API's.
CRUS for /customers
/GET for Ping
* Closes #$5275
=> Updated churros test for Autotask CRM

src/test/platform/elementbuilder/assets/noendpoint_element.json, src/test/platform/elementbuilder/assets/noendpoint_instance_postschema.json, src/test/platform/elementbuilder/multipleendpoint.js
* Added tests for post resources 
* fixed chaining limit test to 5
```
elementbuilder
✓ should support calling multiple endpoint chain requests (167ms)
✓ should support calling multiple endpoint chain requests for POST and body (123ms)
✓ should support calling http in hook requests (197ms)
✓ should support calling https in hook requests (888ms)
✓ should fail if chain is more than 5 (294ms)
5 passing (4s)
```
=> Tests for EB Multiple endpoint fixes

src/test/elements/assets/object.definitions.json, src/test/elements/netsuitecrmv2/assets/prospects.json, src/test/elements/netsuitecrmv2/assets/transformations.json, src/test/elements/netsuitecrmv2/prospects.js, src/test/elements/netsuiteerpv2/assets/prospects.json, src/test/elements/netsuiteerpv2/assets/transformations.json, src/test/elements/netsuiteerpv2/prospects.js
* Tests for Netsuite CRM and ERP for new prospects resource
=> Added netsuite tests for prospects

src/test/elements/oraclesalescloud/ping.js
added ping.js for OracleSalesCloud
GET /ping
* Closes #5373
=> Added ping.js for OracleSalesCloud

src/test/elements/box/bookmarks.js
* Tested folder/contents with bookmarks in it.
=> Added Churros to fetch bookmarks

src/test/platform/elementbuilder/assets/models/contacts_metadata.json, src/test/platform/elementbuilder/assets/models/onemodel_element.json, src/test/platform/elementbuilder/models.js
* One Resource One Model swagger for metadata
* tests for unified swagger
```
element-model
✓ should support calling combined/merged metadata for instance (121ms)
```
=> Element model tests for unified swagger model for metadata

src/test/elements/hubspot/assets/newResource.json, src/test/elements/hubspot/contacts-search.js, src/test/elements/hubspotcrm/assets/newResource.json, src/test/elements/hubspotcrm/contacts-search.js
* Tests Hubspot and Hubspot CRM elements resource extend and compatible with Element Builder
```
contacts-search
✓ should test newly added account resource contacts-search (1138ms)
```
=> Hubspot and Hubspot CRM elements resource extend tests

src/test/elements/magentov20/categories.js, src/test/elements/magentov20/coupons.js, src/test/elements/magentov20/credit-memos.js, src/test/elements/magentov20/customer-groups.js, src/test/elements/magentov20/customers.js, src/test/elements/magentov20/invoices.js, src/test/elements/magentov20/orders.js, src/test/elements/magentov20/shipments.js, src/test/elements/magentov20/stock-items.js, src/test/elements/magentov20/stores.js, src/test/elements/magentov20/transactions.js
* Added tests for `orderBy` feature added to MagentoV2.0
No example provided
* Closes [Soba Issue #5414](https://github.com/cloud-elements/soba/issues/5414)
=> Added test for magentov20 orderBy query parameter

src/test/elements/quickbooks/assets/newResource.json, src/test/elements/quickbooks/customers-search.js
* Tests for quickbooks element extend ability
=> Quickbooks Element Extend tests

package.json, src/core/tools.js, src/test/elements/bigcommerce/assets/categories.json, src/test/elements/bigcommerce/assets/customers.json, src/test/elements/bigcommerce/customers.js, src/test/elements/bigcommerce/products.js, src/test/elements/connectwisehd/bulk.js, src/test/elements/dropboxv2/links.js, src/test/elements/intacct/ledger-accounts.js, src/test/elements/mysql/Fairsail.js, src/test/elements/mysql/assets/fairsail.json, src/test/elements/netsuitecrmv2/accounts.js, src/test/elements/netsuitecrmv2/assets/accounts.json, src/test/elements/netsuitecrmv2/assets/contacts.json, src/test/elements/netsuitecrmv2/assets/leads.json, src/test/elements/netsuitecrmv2/contacts.js, src/test/elements/netsuitecrmv2/leads.js, src/test/elements/netsuitefinancev2/assets/lot-numbered-assembly-items.json, src/test/elements/netsuitefinancev2/assets/non-inventory-resale-items.json, src/test/elements/netsuitefinancev2/lot-numbered-assembly-items.js, src/test/elements/netsuitefinancev2/non-inventory-resale-items.js, src/test/elements/netsuitehcv2/assets/payroll-items.json, src/test/elements/netsuitehcv2/payroll-items.js, src/test/elements/sage200/assets/customers.json, src/test/elements/sage200/customers.js, src/test/elements/sharefile/folder.js, src/test/elements/sugarcrmv2/assets/users.json, src/test/elements/sugarcrmv2/users.js, test/core/assets/testPayload.json, test/core/tools.test.js
* In a JSON file use `<<method>>` to generate random data
* Look at faker.js for a complete list of all methods that can be used
```
{
"firstName": "<<name.firstName>>"
}
```
* Closes #760
=> Added ability to easily use randomized payloads

src/test/platform/elements/instances.js
* Added a test for updating element instance tags via the `PATCH /instances/{id}` API
* Closes #798
=> Added a test updating element instance tags

src/test/elements/hubspot/contacts-search.js
=> Hubspot required wrong file

src/core/tools.js
=> Added docs for `tools` functions

src/test/platform/formulas/formulas.js
* An abridged version of the formula payload can be retrieved by using `GET /formulas?abridged=true`
* The default value of the `abridged` parameter (if omitted) is `false`
* Closes #790
=> Added a test for the abridged version of the GET /formulas API response payload

src/test/elements/zohocrm/assets/newResource.json, src/test/elements/zohocrm/assets/newResourcePost.json, src/test/elements/zohocrm/contacts-post.js, src/test/elements/zohocrm/leads-search.js
* Zoho element extend tests
* Test for GET resource which is extended
* Test for POST resource which is extended
=> Zoho element extend tests

src/test/elements/pardot/assets/newResource.json, src/test/elements/pardot/prospects-query.js
=> Pardot element extend tests

src/test/elements/recurly/assets/billinginfo.json, src/test/elements/recurly/assets/customers.json, src/test/elements/recurly/assets/invoices.json, src/test/elements/recurly/assets/patch.json, src/test/elements/recurly/assets/plans.json, src/test/elements/recurly/assets/subscriptions.json, src/test/elements/recurly/assets/transactions.json, src/test/elements/recurly/assets/transformations.json, src/test/elements/recurly/customers.js, src/test/elements/recurly/invoices.js, src/test/elements/recurly/plans.js, src/test/elements/recurly/subscriptions.js, src/test/elements/recurly/transactions.js
=> Added Recurly Test

src/test/elements/sfdc/metadata.js
* Added a test for the `GET /hubs/crm/objects` API
* Closes #808
=> Added a test case for the GET /hubs/crm/objects API

src/test/elements/hubspotcrm/contacts-search.js, src/test/elements/pardot/prospects-query.js, src/test/elements/zohocrm/contacts-post.js, src/test/elements/zohocrm/leads-search.js
* Case Sensitive file names for requires
* Closes #812
=> Case Sensitive file names for requires

src/test/elements/box/assets/groups.json, src/test/elements/box/groups.js
* Prevents `unique` errors on the Box Group object.
=> Randomized Box Groups Payload

src/test/elements/dropboxbusinessv2/documentsDB.js
* Randomized dropboxbusinessv2 files and folders objects
=> Randomized dropboxbusinessv2 files and folders objects

src/test/elements/netsuitecrmv2/assets/prospects.json, src/test/elements/netsuitecrmv2/prospects.js
* Randomized Netsuitecrm `prospects` object
=> Randomized Netsuitecrm `prospects` object

src/test/elements/sfdc/assets/users.json, src/test/elements/sfdc/users.js
* Randomized sfdc's Users Object
=> Randomized sfdc's Users Object

src/test/elements/netsuiteerpv2/accounts.js, src/test/elements/netsuiteerpv2/assets/accounts.json
* Randomized Netsuite's Accounts Object
=> Randomized Netsuite's Accounts Object

src/test/elements/intacct/assets/customers.json, src/test/elements/intacct/customers.js
* Randomized the Intacct `customers` object
=> Randomized Intacct Customers

README.md, src/cli/churros-test.js, src/test/elements/lifecycle.js
* Updated the README.me with added features and more examples.
=> Updated README.md

src/test/platform/integrations/assets/integration.schema.json
* Updated the platform integration tests to check for the `elementInstances[]` and `formulaInstances[]` properties on responses
=> :koala: updated /integrations tests

src/test/platform/docs/docs.js
* Added tests for elements where swagger errors are fixed
=> Elements swagger validation

src/test/elements/hubspot/assets/lists.json, src/test/elements/hubspot/lists.js
* Randomized hubspot's `lists` object
=> Randomized Data For Hubspot's Lists Object

src/test/elements/oraclesalescloud/assets/opportunities.json, src/test/elements/oraclesalescloud/opportunities.js
* Randomized data for Oracle Sales Cloud's Opportunities object
=> Randomized Oracle Sales Cloud's Opportunities Object

src/test/elements/autotaskcrm/assets/newResource.json, src/test/elements/autotaskcrm/extended-resource.js, src/test/elements/autotaskhelpdesk/assets/newResource.json, src/test/elements/autotaskhelpdesk/extended-resource.js
* Autotask CRM and Helpdesk Element extend tests
=> Autotask CRM and Helpdesk Element extend tests

src/core/props.js, src/core/provisioner.js, src/core/suite.js, src/test/elements/closeio/contacts.js, src/test/elements/lifecycle.js, src/test/elements/sfdc/accounts.js, test/core/assets/suite-helper.js, test/core/provisioner.test.js, test/core/suite.test.js
Reverts cloud-elements/churros#755
=> Revert "Added ability to test polling"

README.md, src/cli/churros-test.js, src/core/provisioner.js
* Can add any parameters or override current parameters
`churros test elements/zuorav2 --params '{"zuorav2.sandbox": true}'`
* Closes #674
=> Added ability to add parameters while provisioning

src/test/elements/connectwisecrm/assets/comments.json, src/test/elements/connectwisecrm/incidents.js
Added Churros for ConnectWiseCRM  element for incident resource.
* Closes #5272
=> Connectwisecrm tests for incidents resource.

src/test/elements/netsuitecrmv2/assets/accounts.json, src/test/elements/netsuitecrmv2/assets/activities.json, src/test/elements/netsuitecrmv2/assets/contacts.json, src/test/elements/netsuitecrmv2/assets/customers.json, src/test/elements/netsuitecrmv2/assets/leads.json, src/test/elements/netsuitecrmv2/assets/opportunities.json, src/test/elements/netsuitecrmv2/assets/prospects.json
* Added required fields in churros payload for NetsuiteCRM
* Closes #5844
=> Added required fields in churros payload for NetsuiteCRM

src/test/elements/netsuiteerpv2/assets/accounts.json, src/test/elements/netsuiteerpv2/assets/cases.json, src/test/elements/netsuiteerpv2/assets/contacts.json, src/test/elements/netsuiteerpv2/assets/customers.json, src/test/elements/netsuiteerpv2/assets/employees.json, src/test/elements/netsuiteerpv2/assets/estimates.json, src/test/elements/netsuiteerpv2/assets/invoices.json, src/test/elements/netsuiteerpv2/assets/leads.json, src/test/elements/netsuiteerpv2/assets/opportunities.json, src/test/elements/netsuiteerpv2/assets/products.json, src/test/elements/netsuiteerpv2/assets/prospects.json, src/test/elements/netsuiteerpv2/assets/purchase-orders.json, src/test/elements/netsuiteerpv2/assets/vendor-payments.json, src/test/elements/netsuiteerpv2/assets/vendors.json
* Updated POST Payload by adding required fields as per the models.
=> Added required fields in churros payload for NetsuiteErp

src/test/elements/netsuitehcv2/assets/employees.json
- Added required fields in churros payload for Netsuite HC
* Closes #5845
=> Added required fields in churros payload for Netsuite HC

src/test/platform/elementbuilder/assets/execution/httprequestresponse_element.json, src/test/platform/elementbuilder/execution.js
* Element Builder tests for passing no headers
=> Element Builder tests for passing no headers

src/test/elements/pardot/activities.js, src/test/elements/pardot/assets/campaigns.json, src/test/elements/pardot/assets/contacts.json, src/test/elements/pardot/assets/transformations.json, src/test/elements/pardot/campaigns.js, src/test/elements/pardot/contacts.js, src/test/elements/pardot/leads.js, src/test/elements/pardot/lists.js, src/test/elements/pardot/ping.js
* Made use of faker.js in json payloads to generate dynamic values.
=> Added faker values in payloads for Pardot

src/test/elements/hubspot/accounts.js, src/test/elements/hubspot/assets/accounts.json, src/test/elements/hubspot/assets/contacts.csv, src/test/elements/hubspot/assets/contacts.json, src/test/elements/hubspot/assets/contactsProperties.json, src/test/elements/hubspot/assets/folders.json, src/test/elements/hubspot/assets/workflows.json, src/test/elements/hubspot/contacts.js, src/test/elements/hubspot/folders.js, src/test/elements/hubspot/listsContacts.js
* Added required fields in the churros payload as per updated models.
=> Added required fields in churros payload for Hubspot Marketing 

src/core/oauth.js, src/core/provisioner.js, src/test/elements/servicenowoauth/assets/scripts.js
=> ServiceNow OAuth updates

src/test/elements/acton/assets/campaigns.json, src/test/elements/acton/assets/contacts.json, src/test/elements/acton/assets/contactsUpdate.json, src/test/elements/acton/assets/lists.json, src/test/elements/acton/assets/optouts.json, src/test/elements/acton/lists.js, src/test/elements/acton/optouts.js, src/test/elements/netsuiteerpv2/assets/products.json, src/test/elements/netsuiteerpv2/contacts.js, src/test/elements/netsuiteerpv2/customers.js, src/test/elements/netsuiteerpv2/employees.js, src/test/elements/netsuiteerpv2/leads.js, src/test/elements/netsuiteerpv2/products.js, src/test/elements/netsuiteerpv2/prospects.js, src/test/elements/netsuiteerpv2/vendors.js
* Updated payloads by using faker values.
=> Updated churros payloads for Acton and NetsuiteErpV2

src/test/elements/quickbooks/assets/credit-memos.json, src/test/elements/quickbooks/assets/credit-terms.json, src/test/elements/quickbooks/assets/customers.json, src/test/elements/quickbooks/assets/departments.json, src/test/elements/quickbooks/assets/employees.json, src/test/elements/quickbooks/assets/ledger-accounts.json, src/test/elements/quickbooks/assets/products.json, src/test/elements/quickbooks/assets/vendor.json, src/test/elements/quickbooks/credit-terms.js, src/test/elements/quickbooks/customers.js, src/test/elements/quickbooks/departments.js, src/test/elements/quickbooks/employees.js, src/test/elements/quickbooks/ledger-accounts.js, src/test/elements/quickbooks/vendor.js
* Updated churros payloads by adding required fields as per updated models.
=> Updated churros payload for Quickbooks Online

src/test/platform/accounts/accounts.js, src/test/platform/elements/assets/element.metadata.expanedschema.json, src/test/platform/elements/instances.js, src/test/platform/elements/metadata.js, src/test/platform/formulas/errors.js, src/test/platform/formulas/executions.js
* Added a test for the new `sub-account-instances` role, to allow a parent admin account to view/use sub-account element and formula instances
* Fixed some of the formula tests
* Closes #878
=> Added a test for the new instance visibility account role and fixed some of the formula and platform/elements tests

README.md
* Updating link for API docs, was receiving a 404
=> updating hyperlink for docs

src/test/elements/stripe/plans.js
* Updated the churros payload to pass churros test of Plan API. 
* Closes #${5891}
=> CE-5891 Updated the churros for PATCH  method of plan API.

src/core/oauth.js
* Updated googledrive oauth process
=> Updated googledrive oauth process

src/test/elements/stripe/authenticate.js, src/test/elements/stripe/subscriptions.js
* Removed `/authentication` test
* Added GET `/subscriptions/{id}` resource
=> Stripe fixes

src/test/elements/facebooksocial/assets/status.json, src/test/elements/facebooksocial/status.js, src/test/elements/facebooksocial/user.js
* Updated churros payload as per by adding required fields as per updated models.
=> IBM: Updated churros payload for Facebook-Social

src/test/elements/servicecloud/assets/contacts.json, src/test/elements/servicecloud/contacts.js
* Added POST /contacts payload.
* Closes https://github.com/cloud-elements/soba/issues/5980
=> Oracle Service Cloud: Added payload for POST /contacts

src/test/elements/infusionsoftecommerce/orders.js, src/test/elements/infusionsoftecommerce/products.js
Added churros for resources.
* products
* orders
* Closes #[5714](https://github.com/cloud-elements/soba/issues/5714)
=> CE-5714 : Added churros for InfusionSoft Ecommerce

src/test/elements/zendesk/assets/fields.json, src/test/elements/zendesk/assets/incidents.json, src/test/elements/zendesk/assets/sections.json, src/test/elements/zendesk/assets/statusUpdate.json, src/test/elements/zendesk/statuses.js, src/test/elements/zendesk/users.js
* Updated churros payload by adding required fields as per the updated models.
* Added churros test cases for `statuses` resources.
=> IBM: Updated churros for Zendesk

src/core/cloud.js, src/test/platform/elementbuilder/elementextend.js, src/test/platform/elements/assets/common.js, src/test/platform/elements/configuration.js, src/test/platform/elements/elements.js, src/test/platform/elements/instances.js, src/test/platform/elements/oauthProxies.js, src/test/platform/elements/resource-models.js, src/test/platform/events/processing.js, src/test/platform/formulas/config.js, src/test/platform/formulas/formulas.js, src/test/platform/formulas/instances.js, src/test/platform/formulas/load.js, src/test/platform/formulas/steps.js, src/test/platform/integrations/integrations.js, src/test/platform/organizations/objects.js, src/test/platform/transformations/transformations.js
* Cleans up platform tests in case of failures
=> Cleanup Platform Tests

src/test/platform/docs/docs.js
* AWS Swagger docs validation tests for basepath
=> AWS Swagger docs validation tests for basepath

src/test/elements/assets/object.definitions.json, src/test/elements/mailchimpv3/assets/transformations.json, src/test/elements/mailchimpv3/lists.js, src/test/elements/woocommercerest/assets/transformations.json, src/test/elements/woocommercerest/customers.js, src/test/elements/woocommercerest/productsAttributes.js, src/test/elements/woocommercerest/productsCategories.js
* Sub object and snake case resources transformations tests
=> Sub object and snake case resources transformations tests

src/test/elements/ecwid/customers.js, src/test/elements/ecwid/orders.js, src/test/elements/ecwid/ping.js, src/test/elements/ecwid/products.js
- Added churros for all the resources.
- As there is no POST APIs , so PATCH test cases are skipped.
- "Where clause" is working with  customer_id but its not working with customer_email.
So raised a bug for that. [#5989](https://github.com/cloud-elements/soba/issues/5989)
* Closes [#4320](https://github.com/cloud-elements/soba/issues/4320)
=> CE-4320 : Added churros test for Ecwid 

src/test/elements/successfactors/assets/compositeEmployee.json, src/test/elements/successfactors/assets/employee.json, src/test/elements/successfactors/assets/employees.json, src/test/elements/successfactors/assets/employment.json, src/test/elements/successfactors/assets/job.json, src/test/elements/successfactors/assets/personal.json, src/test/elements/successfactors/assets/transformations.json, src/test/elements/successfactors/assets/users.json, src/test/elements/successfactors/compositeEmployee.js, src/test/elements/successfactors/employees.js, src/test/elements/successfactors/users.js
New element successfactors core Hr test cases
=> Successfactors test cases

src/test/lifecycle.js
=> Removed listener

src/core/suite.js
* Get base element in case someone is passing `pardot--events`
=> Get the base element for poller element props

src/core/provisioner.js, src/test/platform/elementbuilder/authtrace.js, test/core/provisioner.test.js
* Tests for Element Builder authentication trace
=> Tests for Element Builder authentication trace

src/core/oauth.js, src/test/elements/servicenow/assets/scripts.js, src/test/elements/servicenowoauth/assets/scripts.js, src/test/elements/woocommercerest/customers.js
* Added selenium script to ServiceNow
=> Adding selenium script to ServiceNow (basic auth)

src/test/elements/netsuitehcv2/employees.js, src/test/platform/elements/assets/closeioSwagger.schema.json, src/test/platform/elements/elements.js, src/test/platform/elements/instances.js, src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-with-configured-api-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-request-trigger-formula.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas-failed-request.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/pagination.js, src/test/platform/formulas/sub-formula-executions.js
* fixed tests I missed when changed from sfdc to closeio
=> Formula fixes

src/core/oauth.js, src/test/elements/assets/object.definitions.json, src/test/elements/campaignmonitor/accounts.js, src/test/elements/campaignmonitor/assets/accounts.json, src/test/elements/campaignmonitor/assets/campaigns.json, src/test/elements/campaignmonitor/assets/contacts.json, src/test/elements/campaignmonitor/assets/lists.json, src/test/elements/campaignmonitor/assets/segments.json, src/test/elements/campaignmonitor/assets/transformations.json, src/test/elements/campaignmonitor/campaigns.js, src/test/elements/campaignmonitor/contacts.js, src/test/elements/campaignmonitor/lists.js, src/test/elements/campaignmonitor/segments.js
Addition of test for the new Campaign Monitor element built by Left Hook Digital.
* added oauth flow to core
* added test and assets for campaign monitor element
* added object definition to assets for segements resource.
=> Test for New Element Campaign Monitor

src/test/elements/assets/object.definitions.json
=> Fix churros

src/test/elements/epages/carts.js
* Fixed test case failure for /carts/{id} API's of EPages. Added cartToken as a query parameter in subsequent API's of carts
* Closes #6193
=> Fixed test case failure for /carts/{id} API's of EPages

src/test/elements/assets/object.definitions.json
=> Object definition fix

src/test/elements/sfdclibraries/files.js
=> SFDC Libraries test for root file link

src/test/platform/formulas/faar.js
* Test around the new `/formulas/:id/docs` API that exists for FaaR formulas.
=> FaaR API doc tests

src/test/platform/elementbuilder/assets/bulk/accounts.csv, src/test/platform/elementbuilder/assets/bulk/bulk_element.json, src/test/platform/elementbuilder/bulk.js, src/test/platform/elements/assets/element.object.payload.json
* Element Builder Element object bulk tests
=> Element Builder Element object bulk tests

src/core/cloud.js, src/core/oauth.js, src/test/elements/campaignmonitor/accounts.js, src/test/elements/campaignmonitor/assets/accounts.json, src/test/elements/campaignmonitor/assets/campaigns.json, src/test/elements/campaignmonitor/assets/contacts.json, src/test/elements/campaignmonitor/assets/lists.json, src/test/elements/campaignmonitor/assets/segments.json, src/test/elements/campaignmonitor/assets/transformations.json, src/test/elements/campaignmonitor/campaigns.js, src/test/elements/campaignmonitor/contacts.js, src/test/elements/campaignmonitor/lists.js, src/test/elements/campaignmonitor/segments.js, src/test/elements/marketo/campaigns.js
* Updated various tests and OAuth flow
=> Campaign Monitor tests updates

src/test/elements/zendesk/assets/brands.json, src/test/elements/zendesk/assets/organizations.json, src/test/elements/zendesk/brands.js, src/test/elements/zendesk/organizations.js
* Added CRUD test for newly exposed "organizations" and "brands" endpoints
=> added tests for new zendesk exposed endpoints

src/test/platform/general/headers.js
* Added a test to assert for the new CORS header added in https://github.com/cloud-elements/soba/pull/6391
=> Added the trace id header to the CORS test

src/test/elements/assets/object.definitions.json, src/test/elements/zohocrm/assets/products.json, src/test/elements/zohocrm/assets/transformations.json, src/test/elements/zohocrm/products.js
* Added tests for products APIs of ZohoCRM element
=> Added tests for products APIs of ZohoCRM element

src/test/elements/shopify/metafields.js, src/test/elements/shopify/price-rules.js, src/test/elements/shopify/refunds.js
* Updated `metafields`, `price-rules` and `refunds` tests that were failing.
=> Fixed failing tests for Shopify

src/test/platform/docs/docs.js
* Added `sfdc` docs test
de any images, GIFs, etc. showing up these changes
=> Added SFDC to docs test

src/test/elements/sapc4chd/assets/nested-incident.json, src/test/elements/sapc4chd/incidents.js
=> Test for nested CEQL search on /incidents

src/test/elements/dropbox/folders.js, src/test/elements/dropboxbusiness/folders.js, src/test/elements/dropboxbusinessv2/folders.js, src/test/elements/dropboxv2/folders.js
* Fixed Dropbox root folder ID encoding for https://github.com/cloud-elements/soba/pull/6586
=> Dropbox root folder ID encoding

src/test/elements/box/files.js
* Added a test to make sure copying files does not delete the existing file when overwrite is false for the box element
* Closes #997
=> Added a test to make sure copying files does not delete the existing file when overwrite is false

src/test/elements/jira/assets/incidentProperties.json, src/test/elements/jira/incidents.js
* Added CRUD operation test cases for `incident-properties` resource.
* The `PUT` test is capable of creating a new property as well as updating an existing one.
=> Jira: Added CRUD test cases for incident-properties resource

src/test/elements/assets/object.definitions.json, src/test/elements/netsuitefinancev2/assets/classifications.json, src/test/elements/netsuitefinancev2/assets/departments.json, src/test/elements/netsuitefinancev2/assets/locations.json, src/test/elements/netsuitefinancev2/assets/transformations.json, src/test/elements/netsuitefinancev2/classifications.js, src/test/elements/netsuitefinancev2/departments.js, src/test/elements/netsuitefinancev2/locations.js
* CRUD tests for `classifications`
* CRUD tests for `departments`
* CRUD tests for `locations`
=> Netsuite Finance v2 tests for new resources

src/test/platform/elements/assets/element.object.payload.json
=> Fixes Element Object test

src/test/elements/box/files.js, src/test/elements/sharefile/files.js
* Added tests with for the `overwrite` flag for the ShareFile element's `POST /files/copy` API
* Closes #1012
=> Added test for the ShareFile file copy APIs

src/test/elements/lifecycle.js
* Will save the instance for an hour with `--save` flag
=> Save Instance Functionality

src/core/provisioner.js, src/core/suite.js, src/test/elements/gotowebinar/polling.js, src/test/elements/netsuiteerpv2/polling.js, src/test/elements/netsuitehcv2/assets/employees.json, src/test/elements/netsuitehcv2/employees.js, src/test/elements/netsuitehcv2/polling.js, src/test/elements/quickbooks/polling.js, src/test/elements/quickbooksonprem/polling.js
=> Polling Additions3

src/test/elements/quickbooks/assets/tax-agencies.json, src/test/elements/quickbooks/tax-agencies.js
Added test cases for the following newly added `tax-agencies` APIs:
* `GET /tax-agencies`
* `GET /tax-agencies/{id}`
* `POST /tax-agencies`
* Closes  https://github.com/cloud-elements/soba/issues/6244
=> Added test cases for `tax-agencies` resource added on QBO element

src/test/elements/netsuitefinancev2/purchase-orders.js
* Netsuite Purchase Order search test for status
=> Netsuite Purchase Order search test

src/test/elements/jira/assets/specialCharContact.json, src/test/elements/jira/contacts.js
* Added tests to support special character's in `username` filter for GET /contacts
* Closes #1013
=> JIRA - GET /contacts search w/ special chars

src/test/elements/googledrive/files.js
* Added tests for Google Drive copy file with overwrite flag
* Closes #1033
=> Added tests for Google Drive copy file with overwrite flag

src/core/oauth.js, src/test/elements/hootsuite/assets/addmember.json, src/test/elements/hootsuite/assets/media.json, src/test/elements/hootsuite/assets/members.json, src/test/elements/hootsuite/assets/messages.json, src/test/elements/hootsuite/assets/teams.json, src/test/elements/hootsuite/assets/users.json, src/test/elements/hootsuite/me.js, src/test/elements/hootsuite/media.js, src/test/elements/hootsuite/messages.js, src/test/elements/hootsuite/organizations.js, src/test/elements/hootsuite/social-profiles.js, src/test/elements/hootsuite/users.js
* Added churros for me, organizations, members, teams and socialProfiles APIs.
* [#6138](https://github.com/cloud-elements/soba/issues/6138)
=> CE-6138 : Added churros for Hootsuite elements

src/test/elements/onedrivev2/assets/special-folders.json, src/test/elements/onedrivev2/folders.js
* Added test to allow special characters in path for OneDrive
=> Added test to allow special characters in path

src/test/platform/elements/elements.js, src/test/platform/elements/instances.js
* Masking oauth apikey/secret instance config masking
* Masking oauth apikey/secret element config masking
=> Tests for oauth apikey/secret masking

src/test/platform/hubs/assets/hub.json, src/test/platform/hubs/hubs.js
* Tests for hubs platform APIs
=> Tests for hubs API

src/test/platform/docs/docs.js
*Added churros for sfdcservicecloud swagger validation
=> Added churros for sfdcservicecloud swagger validation

src/test/elements/sharefile/files.js, src/test/elements/sharefile/folder.js
* Fixed failing tests for `files` and `folders` resources. Having added fix for overwrite parameter in [pull request 6899](https://github.com/cloud-elements/soba/pull/6899/files), tests were overwriting existing files and folders with default `overwrite = false` and hence were failing.
=> Fixed failing tests for Citrix Sharefile

src/test/elements/magentov20/assets/categories.json, src/test/elements/magentov20/carts.js, src/test/elements/magentov20/categories.js
* Only put items in stock in your cart
* Randomized data
=> Few Magento test fixes

src/test/elements/connectwisecrm/contacts.js, src/test/elements/connectwisecrm/incidents.js, src/test/elements/connectwisecrm/organizations.js, src/test/elements/connectwisecrmrest/contacts.js, src/test/elements/connectwisecrmrest/organizations.js, src/test/elements/connectwisehd/contacts.js, src/test/elements/connectwisehd/incidents.js, src/test/elements/connectwisehd/organizations.js, src/test/elements/connectwisehd/time-entries.js
* Added unique id for pagination
=> Fixed Connectwise Pagination

src/test/platform/docs/docs.js
* Catches all swagger errors and will print them out in the error message.
=> Catches Swagger Errors

src/test/elements/freshdeskv2/accounts.js, src/test/elements/freshdeskv2/assets/accounts.json
* Updated tests for Accounts resource implementing API v2(/api/v2/companies)
* Closes #1031
=> Freshdesk: Updated churros for Accounts resource implementing API v2(/api/v2/companies)

src/test/elements/pipedrive/activity-types.js, src/test/elements/pipedrive/assets/activity-types.json
* Added churros for CUDS operation of /activity-type API. 
* Added churros for delete /activity-type API which accepts multiple ids to delete. 
* Closes #${6010}
=> CE-6010(Pipedrive): Added churros for activtiy-types API 

src/test/elements/intacct/assets/customers.json, src/test/elements/intacct/assets/invoices.json, src/test/elements/intacct/assets/payments-apply.json, src/test/elements/intacct/assets/payments.json, src/test/elements/intacct/assets/transformations.json, src/test/elements/intacct/payments.js
Added churros testcases for POST/payment/{id}/apply which was missing.
Also, included faker in customer and invoice.
* Closes [#6290](https://github.com/cloud-elements/soba/issues/6290)
=> [CE-6290] Intacct: Added churros for payment/{id}/apply

src/test/elements/icontact/assets/campaigns.json, src/test/elements/icontact/assets/contacts.json, src/test/elements/icontact/assets/lists.json, src/test/elements/icontact/assets/messages.json, src/test/elements/icontact/assets/multipleCampaigns.json, src/test/elements/icontact/assets/multipleContacts.json, src/test/elements/icontact/assets/multipleLists.json, src/test/elements/icontact/assets/multipleMessages.json, src/test/elements/icontact/assets/transformations.json, src/test/elements/icontact/campaigns.js, src/test/elements/icontact/contacts.js, src/test/elements/icontact/lists.js, src/test/elements/icontact/messages.js, src/test/elements/icontact/multiple.js, src/test/elements/icontact/ping.js, src/test/elements/icontact/unsubscribes.js
* Added tests for `contacts`, `lists`, `campaigns`, `messages` and `multiple` resources.
=> Added tests for iContact element.

src/test/elements/acton/assets/listUpdate.json, src/test/elements/acton/assets/lists.json, src/test/elements/acton/assets/updateList.csv, src/test/elements/acton/lists.js
* Added test for `PATCH lists/{id}` API.
=> Added test for PATCH lists/{id} for Act-On

src/test/elements/assets/object.definitions.json, src/test/elements/sapbusinessone/assets/customers.json, src/test/elements/sapbusinessone/assets/drafts.json, src/test/elements/sapbusinessone/assets/products.json, src/test/elements/sapbusinessone/assets/transformations.json, src/test/elements/sapbusinessone/customers.js, src/test/elements/sapbusinessone/drafts.js, src/test/elements/sapbusinessone/ledger-accounts.js, src/test/elements/sapbusinessone/products.js
* bullet separated list of highlights
=> Churros for SAP Business One.

src/test/platform/elements/elements.js, src/test/platform/elements/objects.js
* Tests for checking default value for configuration during element create/update
=> Tests for configuration  default value check during element create/update

src/test/elements/netsuitefinancev2/assets/subsidiaries.json, src/test/elements/netsuitefinancev2/assets/transformations.json, src/test/elements/netsuitefinancev2/subsidiaries.js
* Added CRUDS operations for subsidiary 
* Closes #6808
=> CE-6808 Added subsidiary API in Netsuite Finance 

src/test/elements/bigcommerce/customers.js, src/test/elements/bigcommerce/products.js
* Fixed product and customers randomized error.
* Closes # [US1183-TA426-bigcommerce](https://rally1.rallydev.com/#/144349237612d/detail/task/150628393620)
=> BigCommerce : Circle CI Churros fix for product and customer failure

src/test/elements/zendesk/assets/brands.json, src/test/elements/zendesk/brands.js
* Fixed randomization error for brands API.
* Closes #[US1183-TA427-zendesk](https://rally1.rallydev.com/#/144349237612d/detail/task/150641503520)
=> Zendesk : Circle CI Churros fix for brands randomization error

src/test/elements/servicecloud/assets/contacts.json, src/test/elements/servicecloud/contacts.js
* Fix for contacts randomization error
* Closes [#US1183-TA428-servicecloud](https://rally1.rallydev.com/#/144349237612d/detail/task/150648252940?fdp=true)
=>  ServiceCloud: Circle CI Churros fix for contact randomization error

src/test/elements/postgresql/assets/companies.json, src/test/elements/postgresql/companies.js
* Fixed companies randomization errror.
* Closes [#US1183-TA429-postgresql](https://rally1.rallydev.com/#/144349237612d/detail/task/150652437720)
=> Postgresql: Circle CI Churros fix for companies randomization error 

src/test/elements/eloqua/assets/lists.json, src/test/elements/eloqua/lists.js
=> Eloqua: randomized data

src/test/elements/netsuitefinancev2/assets/classifications.json, src/test/elements/netsuitefinancev2/assets/locations.json, src/test/elements/netsuitefinancev2/classifications.js, src/test/elements/netsuitefinancev2/locations.js
* Randomized data on classifications and locations objects
=> Netsuitefinancev2: Location and Classification random data

src/test/elements/sharefile/share.js
* Changed expiration date to 2020
=> Sharefile: updated expiration date

src/core/oauth.js
* Selenium url is slightly different on the sandbox side
=> Paypalv2--sandbox: Updated Selenium

src/test/elements/zohocrm/assets/scripts.js
* Updates the selenium to account for no tokens to delete before.
=> Zohocrm: Before selenium update

src/test/elements/netsuitefinancev2/tax-codes.js, src/test/elements/netsuitefinancev2/tax-rates.js
Fixed tax-rate and tax-codes failures.
* Closes #[US1183-TA431-netsuitefinancev2](https://rally1.rallydev.com/#/144349237612d/detail/task/150665840824)
=> NetsuiteFinancev2: Fixed tax-rate and tax-codes churros failure

src/core/oauth.js
* Replaces sleeps with a better wait function
=> Replacing sleeps

src/test/elements/hubspotcrm/assets/pipelines.json, src/test/elements/hubspotcrm/pipelines.js
* Added churros test for `pipelines` CRUD operations.
=> Added churros tests for 'pipelines' resource

src/test/elements/box/webhooks.js
* Added churros for CRUDS /webhooks
=> Added churros for webhooks of box

src/test/platform/formulas/assets/formulas/sub-formula-executions/error-sub-formulas.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/filter-sub-formulas.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas-failed-request.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/simple-sub-formulas.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/two-sub-formulas-no-steps-after.json, src/test/platform/formulas/assets/formulas/sub-formula-executions/two-sub-formulas.json, src/test/platform/formulas/executions.js, src/test/platform/formulas/sub-formula-executions.js
* subformula test support with bodenstein
`CHURROS_FORMULAS_ENGINE=v3 churros test platform/formulas --file sub-formula-executions`
=> subformula execution tests using v3 engine

src/test/elements/dropbox/assets/folders.json, src/test/elements/dropbox/folders.js, src/test/elements/dropboxbusiness/folders.js, src/test/elements/dropboxbusiness/members.js, src/test/elements/dropboxbusinessv2/folders.js, src/test/elements/dropboxv2/assets/folders.json, src/test/elements/dropboxv2/folders.js, src/test/elements/dropboxv2/links.js
* Added tests for using `refId` for all folders endpoints in Dropbox
=> Dropbox - Tests for refId use with folders

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
* Updated the PR Template and Contributing Doc.
N/A
* N/A
=> Updating PR Template and Contributing

src/test/platform/formulas/formulas.js
* positive and negative tests for setting bodenstein as the formula execution engine
=> Tests for upgrading a formula to the bodenstein engine

src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/formulas/basic-formula-instance.json, src/test/platform/formulas/assets/formulas/complex-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-successful-formula.json, src/test/platform/formulas/assets/formulas/element-request-with-configured-api-successful-formula.json, src/test/platform/formulas/assets/formulas/filter-returns-false.json, src/test/platform/formulas/assets/formulas/large-payload-successful-formula.json, src/test/platform/formulas/assets/formulas/loop-successful-formula.json, src/test/platform/formulas/assets/formulas/nested-loops-formula.json, src/test/platform/formulas/assets/formulas/retry-formula.json, src/test/platform/formulas/assets/formulas/script-context-successful-formula.json, src/test/platform/formulas/assets/formulas/script-with-on-failure-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v1-single-threaded.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-error-formula-v2.json, src/test/platform/formulas/assets/formulas/simple-filter-formula.json, src/test/platform/formulas/assets/formulas/simple-no-return-console-formula.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-v1.json, src/test/platform/formulas/assets/formulas/simple-no-return-formula-v2.json, src/test/platform/formulas/assets/formulas/simple-successful-formula-single-threaded.json, src/test/platform/formulas/assets/formulas/simple-successful-formula.json, src/test/platform/formulas/assets/formulas/simple-successful-request-trigger-formula.json, src/test/platform/formulas/assets/formulas/simple-timeout-formula.json, src/test/platform/formulas/assets/formulas/single-threaded-formula.json, src/test/platform/formulas/config.js, src/test/platform/formulas/executions.js, src/test/platform/formulas/formulas.js, src/test/platform/formulas/instances.js, src/test/platform/formulas/load.js
* Formula execution fixes. 
* Enable load testing with bode.
* this includes updates to the `complex-successful` formula and updating a lot of step and config names to be acceptable JS variable names by replaces dashes with underscores.
* Formula engine update tests to use `v3` instead of `bodenstein`
=> Formula execution fixes. Enable load testing with bode.

src/test/platform/elementbuilder/assets/objects/contacts_metadata.json, src/test/platform/elementbuilder/assets/objects/onemodel_element.json, src/test/platform/elementbuilder/element-objects.js
* ElementObject metadata tests for creating the instance and getting the metadata 
```
element-objects
✓ should support calling objectnames for instance (242ms)
✓ should support calling objects metadata for instance (129ms)
2 passing (4s)
```
=> Tests for ElementObject metadata

src/test/platform/formulas/formulas.js
* Updated abridged formula test with changes to include the triggers array on abridged formulas.
* Soba PR: https://github.com/cloud-elements/soba/pull/7419
=> Updated abridged formula tests

src/test/elements/hubspot/assets/contacts.json
* Updated churros and payloads as per updated models.
=> IBM : Updated churros for Hubspot Marketing

src/test/elements/quickbooks/purchases.js
* Updated churros and payloads as per updated models.
=> IBM : Updated churros for Quickbooks online

src/test/elements/lithiumlsw/assets/authors.json, src/test/elements/lithiumlsw/conversations.js
* Added tests for GET /changed-analytic-conversations and /changed-analytic-conversations/{conversationId}
* Closes #7285
=> Added Lithium Tests for conversations

src/test/elements/bigcommerce/assets/address.json, src/test/elements/bigcommerce/assets/customers.json, src/test/elements/bigcommerce/assets/group.json, src/test/elements/bigcommerce/customers.js
* Updated "customer" to avoid randomized data error .
Screenshot of the tests running successfully :
* [RALLY-#US1381](https://rally1.rallydev.com/#/144349237612d/detail/task/155437077408)
* Closes [#US1381-TA746](https://rally1.rallydev.com/#/144349237612d/detail/task/155437077408)
=> Bigcommerce : Updated "customer" resource to avoid randomized data failure 

src/test/platform/formulas/assets/formulas/loop-failure-formula.json
=> loop failure test should use an object as list and get an error

src/core/oauth.js, src/test/elements/hubspot/assets/contactsProperties.json, src/test/elements/hubspot/campaigns.js, src/test/elements/hubspot/files.js
* Added a 5 seconds delay and button click while creating the instance from churros.
* Added fixes to Hubspot tests (CRM and Marketing) 
* Updated OAuth to use a `portalId` setup in the `churros-sauce`
=> US1304: Added delay and button click while creating instance for Hubspot CRM

src/test/elements/eloqua/custom-objects.js, src/test/elements/eloqua/polling.js
* Added test cases for newly added `custom-objects` resource.
* Closes #[US1027](https://rally1.rallydev.com/#/144349237612d/detail/userstory/147402941488)
=> Added churros test cases for new resource custom-objects on Eloqua

src/test/elements/eloqua/email-headers.js, src/test/elements/fieldawarev2/assets/locations.json, src/test/elements/fieldawarev2/contacts.js, src/test/elements/fieldawarev2/jobs.js, src/test/elements/fieldawarev2/locations.js, src/test/elements/fieldawarev2/users.js
* All eloqua tests pass
* Only 1 (opposed to 9) fieldaware v2 failure
eloqua: https://cl.ly/3j1z3K2p0g47
fieldawarev2: https://cl.ly/3w2a411m1v0U
* Closes #768
=> Fieldaware, eloqua: Updates

src/test/elements/lifecycle.js
* Lets you know the environment, username, and oauth information you are running on
https://cl.ly/0y1e3U1W3T1W
=> More information about the tests

src/core/provisioner.js, src/test/elements/lifecycle.js
* Was previously overriding itself, now it doesn't do that
https://cl.ly/0N1h2F0Y3A0c
https://cl.ly/0G3e03063L38
https://cl.ly/443p0E0c213M
=> Refactor backup logic

src/test/platform/organizations/password-policies.js
* Updated password policy tests as the accepted expiration number has changed.
=> Password policy updated tests

src/test/elements/sfdcdocuments/assets/newResource.json, src/test/elements/sfdcdocuments/extended-resource.js
* Added churros for extended-resource for sfdcdocuments
* Closes #[US1498](https://rally1.rallydev.com/#/144349237612/detail/userstory/155195550300)
=> Added churros for extended-resource for sfdcdocuments

src/test/elements/eloqua/assets/newResource.json, src/test/elements/eloqua/extended-resource.js
* Added churros for extended-resource for eloqua
Polling for Eloqua is not working, raised a separate bug for the same.
* Closes #US1490
=> Added churros for extended-resource for eloqua

src/test/elements/connectwisecrm/assets/newResource.json, src/test/elements/connectwisecrm/extended-resource.js, src/test/elements/connectwisehd/assets/newResource.json, src/test/elements/connectwisehd/extended-resource.js
* Added test cases for extended resources of Connectwisehd
* [RALLY-#US1498]https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195549708
* Closes #US1496
=> Added test cases for extended resources of Connectwisehd

src/test/elements/woocommercerest/assets/productsTags.json, src/test/elements/woocommercerest/products.js, src/test/elements/woocommercerest/productsCategories.js, src/test/elements/woocommercerest/productsTags.js
* Fixed failing tests for below resources,
- products
- products-tags
- products-categories
* [RALLY-#US1486](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/155192974072)
* Closes #US1486
=> Fixed failing tests for Woocommerce REST element

src/test/elements/zendesk/assets/newResource.json, src/test/elements/zendesk/extended-resource.js
* Added churros for extended resources of  Zendesk.
* https://rally1.rallydev.com/#/144349237612d/detail/userstory/153626885832
* Closes #$US-1363
=> Added churros for extended resources of Zendesk

src/core/oauth.js
* Googledrive and googlesheets provisions
google sheets: https://cl.ly/2U3l2D3A0w0X
google drive: https://cl.ly/0Y1K400p0S1N
=> Google selenium

src/test/elements/magentov20/assets/cartProduct.json, src/test/elements/magentov20/carts.js, src/test/elements/magentov20/products-attribute-sets.js
* All pass
https://cl.ly/1O1P3j2A0j11
* Closes #771
=> Magento: tests fixed

src/cli/churros-test.js, src/core/tools.js, src/test/elements/assets/basics.js, src/test/elements/assets/object.definitions.json, src/test/elements/jira/incidents.js, src/test/elements/lifecycle.js, test/core/assets/testPayload.json
* Can now get a single letter or number through the faker method
* Also has the basic tests with docs, metadata, and objects endpoints
`<<random.letter>>`
`<<random.letterUppercase>>`
`<<random.singleNumber>>`
https://cl.ly/2I1f1e3n2d13
=> Single letter and basic tests

src/test/elements/quickbooks/assets/credit-terms.json, src/test/elements/quickbooks/assets/invoices.json, src/test/elements/quickbooks/assets/journal-entries.json, src/test/elements/quickbooks/assets/ledger-accounts.json, src/test/elements/quickbooks/assets/payment-methods.json, src/test/elements/quickbooks/assets/products.json
* Changed methods to limit length and avoid 400s
https://cl.ly/3j0e0l1N3b1Q
* [CircleCI] https://github.com/cloud-elements/soba/pull/7477
=> Quickbooks: changed randomized methods

src/test/elements/assets/basics.js, src/test/elements/lifecycle.js
* setting the props `hub` to correct value
https://cl.ly/2i1X29090Z21
=> Churros backup: set hub to correct value 

src/test/elements/sfdc/users.js
* Added another test case for users to get the currentUser
* Closes #$US1221
=> Added a test case for users/me (to get the current user)

src/test/elements/volusion/assets/newResource.json, src/test/elements/volusion/extended-resource.js
* Added test cases for extendable resource of volusion
* [RALLY-#${ticketNumber}]https://rally1.rallydev.com/#/144349237612d/detail/userstory/156281695940
* Closes #US1594
=> Added test cases for extendable resource of volusion

src/test/elements/acton/assets/newResource.json, src/test/elements/acton/extended-resource.js
*  Added test cases for Acton extended-resource
Churros test results:
[churros-results-acton.txt](https://github.com/cloud-elements/churros/files/1368155/churros-results-acton.txt)
[Closes #US1497](https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195550036)
=> US1497: Updated Acton to be Extendable

src/test/elements/linkedin/comments.js, src/test/elements/linkedin/users.js
* Added comments on skipped test cases for LinkedIn
* Churros test results:
* Closes [#DE40](https://rally1.rallydev.com/#/144349237612d/detail/defect/152427878388)
=> Added comments on skipped test cases for LinkedIn

src/test/elements/assets/basics.js, src/test/elements/lifecycle.js
* Skips the docs test
* Throws failure if we run on the backup instance (demo feedback)
https://cl.ly/290E3t1S2a0Z
=> Docs skipped and provisioning test

src/test/elements/assets/basics.js, src/test/elements/chargebee/assets/transformations.json, src/test/elements/chargebee/transactions.js, src/test/elements/chargify/assets/transformations.json, src/test/elements/chargify/product-families.js, src/test/elements/chargify/products.js, src/test/elements/chargify/transactions.js, src/test/elements/sailthru/assets/transformations.json, src/test/elements/salesforcemarketingcloud/assets/transformations.json, src/test/elements/salesforcemarketingcloud/contacts.js, src/test/elements/wufoo/assets/transformations.json, src/test/elements/wufoo/forms.js, src/test/elements/wufoo/reports.js, src/test/elements/wufoo/users.js
* Updated elements transformations to actually work
* Eloqua is now using `id` instead of `Hash` for consistency
* All elements below are consistent with other elements and pass all tests
Chargebee: https://cl.ly/2f2F1F0y352Y
Chargify: https://cl.ly/3w3R3G2G1q3X
Sailthru: https://cl.ly/2x3O0e220i2p
salesforcemarketingcloud: https://cl.ly/3T0Q3C0z3P0v
Wufoo: https://cl.ly/1A441R1N3s2X
=> Updating elements transformations

src/test/elements/zendesk/agents.js, src/test/elements/zendesk/assets/agents.json, src/test/elements/zendesk/assets/slaPolicies.json, src/test/elements/zendesk/slaPolicies.js
* Added churros test cases for slaPolicies resource of Zendesk.
* Updated churros test cases for agent resource of Zendesk.
* [RALLY-#US1311]https://rally1.rallydev.com/#/144349237612d/detail/userstory/151491239832
* Closes #US1311
=> Added churros test cases for slaPolicies resource of Zendesk

package-lock.json
=> Add NPM 5 support

src/test/platform/users/users.js
* Validate that users cannot grant/revoke roles to/from themselves.
* Validate that a user cannot create a new user with roles that the current user does not have permission to grant.
* [SOBA](https://github.com/cloud-elements/soba/pull/7550)
* [RALLY-#US2470](https://rally1.rallydev.com/#/144349238268d/detail/userstory/163776542100?fdp=true)
* [RALLY-#US2471](https://rally1.rallydev.com/#/144349238268d/detail/userstory/163776922616?fdp=true)
* [RALLY-#US2472](https://rally1.rallydev.com/#/144349238268d/detail/userstory/163776488668?fdp=true)
* [RALLY-#US2473](https://rally1.rallydev.com/#/144349238268d/detail/userstory/163777154544?fdp=true)
=> Tests for role changes to support the UI

src/core/oauth.js
* Hubspot changed there UI so updating selenium for it
https://cl.ly/1U2H3D3Z1R3b
=> Hubspot: updated selenium

src/test/elements/salesforcemarketingcloud/attribute-sets.js
* added attribute-sets checks
https://cl.ly/0l2X2G181502
* [https://github.com/cloud-elements/soba/pull/7587
=> Salesforce Marketing: attribute-sets

src/test/elements/infusionsoftcrm/users.js
* Un-skipped the test cases on the `users` resource.
* [SOBA](https://github.com/cloud-elements/soba/pull/7566)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/110)
* [Rally#US1133](https://rally1.rallydev.com/#/144349237612d/detail/userstory/149192013976)
* Closes  @[#US1133](https://rally1.rallydev.com/#/144349237612d/detail/userstory/149192013976)
=> Un-skiped test cases in Infusionsoft CRM

src/test/elements/quickbooksonprem/bill-payment-cards.js, src/test/elements/quickbooksonprem/bill-payment-checks.js, src/test/elements/quickbooksonprem/bills.js, src/test/elements/quickbooksonprem/credit-memos.js, src/test/elements/quickbooksonprem/credit-terms.js, src/test/elements/quickbooksonprem/currencies.js, src/test/elements/quickbooksonprem/customers.js, src/test/elements/quickbooksonprem/employees.js, src/test/elements/quickbooksonprem/invoices.js, src/test/elements/quickbooksonprem/item-receipts.js, src/test/elements/quickbooksonprem/journal-entries.js, src/test/elements/quickbooksonprem/ledger-accounts.js, src/test/elements/quickbooksonprem/payment-methods.js, src/test/elements/quickbooksonprem/payroll-wage-items.js, src/test/elements/quickbooksonprem/polling.js, src/test/elements/quickbooksonprem/tax-codes.js, src/test/elements/quickbooksonprem/tax-rates.js, src/test/elements/quickbooksonprem/vendor-credits.js, src/test/elements/quickbooksonprem/vendors.js
* Churros fix for `quickbooksonprem`
* Closes [#US1314](https://rally1.rallydev.com/#/144349237612/detail/userstory/151491240776)
=> Churros fix for Quickbooks Enterprise

src/test/elements/acton/assets/createList.csv, src/test/elements/acton/assets/listCreate.json, src/test/elements/acton/lists.js
* Implemented tests for uploading CSV file along with list payload for POST /lists API.
* [RALLY-#US1136](Link https://rally1.rallydev.com/#/144349237612ud/userstories?qdp=%2Fdetail%2Fuserstory%2F149194437216&tpsV=qv%3A0)
* Closes #US1136
=> ActOn: Implemented churros tests for CSV file upload for POST /lists API

src/test/elements/box/assets/customFields.json, src/test/elements/box/assets/template.json, src/test/elements/box/customTemplates.js, src/test/elements/box/files.js
* Fixed churros for custom field API's of Box
* Closes #${US2395}(https://rally1.rallydev.com/#/144349237612d/detail/userstory/161970079512)
=> Fixed churros for custom field API's of Box

src/test/elements/eloqua/assets/transformations.json, src/test/elements/freshdeskv2/assets/accounts.json, src/test/elements/freshdeskv2/assets/transformations.json, src/test/elements/hubspotcrm/contacts.js
* eloqua, freshdeskv2, hubspotcrm all pass
* updated eloqua's and freshdesk's transformation
* payload changes for freshdesk and hubspotcrm
eloqua: https://cl.ly/3k0j3c2P1T3Z
hubspot: https://cl.ly/0k2p0M3Z1z0E
freshdeskv2: https://cl.ly/2X1F173U2R1E
=> eloqua, freshdeskv2, hubspotcrm all pass

src/test/platform/formulas/faar.js
* Add a test for setting and then reverting a FaaR via PATCH /formulas
* [SOBA](https://github.com/cloud-elements/soba/pull/7609#issuecomment-341831710)
=> Add a test for setting and then reverting a FaaR via PATCH /formulas

src/core/assertions.js, src/test/platform/elements/assets/common.js, src/test/platform/elements/assets/element.object.payload.json, src/test/platform/elements/instances.js, src/test/platform/elements/metadata.js, src/test/platform/elements/object-fields.js, src/test/platform/elements/objects.js, src/test/platform/events/analytics.js
* All events test pass
* All but 1 elements failure, weird cloning issue I will have to revisit
Events: https://cl.ly/1O2v432k2C2r
Elements: 1 failure https://cl.ly/0y1s370r0R0t
=> Events and elements platform updates

src/test/platform/formulas/config.js
* Fix the broken formula config update test
=> Fix the broken formula config update test

src/test/elements/facebooksocial/status.js, src/test/elements/facebooksocial/user.js
* Fixed Churros test cases for /comment API of Facebook Social element
* [RALLY-#${DE387}](https://rally1.rallydev.com/#/144349237612d/detail/defect/170158425576?fdp=true)
* Closes #[DE387](https://rally1.rallydev.com/#/144349237612d/detail/defect/170158425576?fdp=true)
=> Fixed Churros for /comment API of Facebook Social element

src/test/platform/formulas/assets/common.js, src/test/platform/formulas/assets/events/raw-closeio-account-obj.json, src/test/platform/formulas/assets/formulas/complex-starwars-successful.json, src/test/platform/formulas/load.js
* Add formula load tests using `closeio` in addition to `sfdc`
* Add formula load tests that run `v1` and `v3` executions simultaneously
=> Extend our formula load tests

src/test/elements/assets/basics.js
* Don't test the provisioning if you specifically set it to run on the backup
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/117)
=> Provision test logic

src/test/elements/netsuiteerpv2/assets/folders.json, src/test/elements/netsuitefinancev2/assets/customers.json, src/test/elements/netsuitefinancev2/assets/departments.json, src/test/elements/netsuitefinancev2/assets/employees.json, src/test/elements/netsuitefinancev2/assets/folders.json, src/test/elements/netsuitefinancev2/assets/ledger-accounts.json, src/test/elements/netsuitefinancev2/assets/lot-numbered-assembly-items.json, src/test/elements/netsuitefinancev2/departments.js, src/test/elements/netsuitefinancev2/ledger-accounts.js
* Added randomized data to avoid 409 type errors
* [DE475](https://rally1.rallydev.com/#/144349238268d/detail/defect/175475487384)
* [DE476](https://rally1.rallydev.com/#/144349238268d/detail/defect/175475491556)
=> netsuite finance and erp fixes

src/core/cloud.js, src/core/oauth.js, src/core/suite.js, src/test/elements/box/assets/template.json, src/test/elements/box/files.js, src/test/elements/googledrive/search.js, src/test/elements/marketo/assets/companies.json, src/test/elements/marketo/companies.js, src/test/elements/marketo/extended-resource.js, src/test/elements/netsuitecrmv2/assets/folders.json, src/test/elements/netsuitecrmv2/assets/leads.json, src/test/elements/netsuitecrmv2/lookups.js, src/test/lifecycle.js
* All above pass except marketo has one failure related to circleci
https://circleci.com/gh/cloud-elements/churros-sauce/586
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/121)
* [DE459](https://rally1.rallydev.com/#/144349238268d/detail/defect/174733532716)
* [DE466](https://rally1.rallydev.com/#/144349238268d/detail/defect/175110112408)
* [DE467](https://rally1.rallydev.com/#/144349238268d/detail/defect/175110118000)
=> Fixes for box googledrive marketo netsuitecrmv2

src/core/provisioner.js, src/test/elements/eloqua/polling.js, src/test/elements/netsuiteerpv2/polling.js
* Eloqua polling passes
* onedrivev2 polling passes
* netsuiteerpv2 polling passes
eloqua: https://cl.ly/3A0e0z3E3D2k
onedrivev2: https://cl.ly/410Z3T1J3p3q
netsuiteerpv2: https://cl.ly/042H243C1l1k
* [RALLY-#DE73](https://rally1.rallydev.com/#/144349237612d/detail/defect/156209193616)
* [RALLY-#DE52](https://rally1.rallydev.com/#/144349237612d/detail/defect/153464854320)
=> Polling fixes

src/test/elements/assets/object.definitions.json
* Added spreadsheets transformations in object definitions
* [SOBA](https://github.com/cloud-elements/soba/pull/7655)
[DE418](https://rally1.rallydev.com/#/144349237612d/detail/defect/172118665604)
=> Added spreadsheets transformations in object definitions for googlesheetsv4

src/test/elements/jira/assets/projects.json, src/test/elements/jira/projects.js
* added test cases for projects resource
* [SOBA](https://github.com/cloud-elements/soba/pull/7596)
* [RALLY-#US2765](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168627226540)
* Closes #US2765
=> Added test cases for projects resource

src/test/elements/zendesk/brands.js, src/test/elements/zendesk/slaPolicies.js
* Added pagination test cases for slaPolicies and brands resources of zendesk element
* [SOBA](https://github.com/cloud-elements/soba/pull/7604)
* [RALLY-#$DE77](https://rally1.rallydev.com/#/144349237612d/detail/defect/156766252572)
* Closes #$DE77
=> Added pagination test cases for slaPolicies and brands resources of zendesk element

src/test/elements/box/assets/customFields.json, src/test/elements/box/files.js
* Added tests for PUT /files/${fileId1}/custom-fields API.
* Added tests for PATCH /files/${fileId1}/custom-fields/${tempKey} API
* [SOBA PR7695](https://github.com/cloud-elements/soba/pull/7695)
* [RALLY-#${DE481}](https://rally1.rallydev.com/#/144349237612ud/detail/defect/176202255700)
* Closes #$[DE481](https://rally1.rallydev.com/#/144349237612ud/detail/defect/176202255700)
=> Box: Added churros tests for files endpoint

src/test/elements/assets/basics.js
* Avoids the one request at a time error
https://cl.ly/3e0b132U463I
=> netsuite transformation tests synchronous 

src/test/elements/jira/agents.js
* Update Agent.js file testcase to pass the churros.
- Churros screenshots :- 
* [DE388](https://rally1.rallydev.com/#/144349237612d/detail/defect/170196517844)
=> Fixing churros for Jira elements

src/test/platform/users/users.js
* platform/users pass
https://cl.ly/3b471a1l0J3z
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/139)
=> Randomized user data

src/test/platform/bulk/bulk.js
* All bulk tests pass
https://cl.ly/3i1s3x0w0L1W
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/128)
=> Bulk tests pass

src/core/oauth.js, src/core/provisioner.js, src/test/elements/assets/basics.js, src/test/elements/xero/assets/journal-entry.json, src/test/elements/xero/assets/transformations.json, src/test/elements/xero/extended-resource.js, src/test/elements/xero/journal-entries.js
* Added support for extended element_key to oauth1 flow
* Added `xero--partner` to `oauth.js`
* Added `skip:true` to `extended-resource` for Xero until extendability implementation is completed for all auth types
* Added `journal-entries` resource test
* [SOBA](https://github.com/cloud-elements/soba/pull/7732)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/140)
* [RALLY-#US3466](https://rally1.rallydev.com/#/144349237612d/detail/userstory/178504265928)
=> Xero test & provisioning enhancement

src/test/platform/elementbuilder/authtrace.js, src/test/platform/elementbuilder/elementextend.js, src/test/platform/elementbuilder/import.js, src/test/platform/elementbuilder/multipleendpoint.js
* Most of the tests are fixed
* Bulk test is a known issue that has tickets open
* One jdbc test is failing due to VPN access, this has ticket open
https://cl.ly/3j0J0M17440x
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/131)
* [RALLY-#US4286](https://rally1.rallydev.com/#/144349238268d/detail/userstory/180103741900)
=> Element builder platform tests

src/test/platform/general/headers.js
* All pass
https://cl.ly/1k0l3B1W0e1X
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/132)
* [RALLY-#US4293](https://rally1.rallydev.com/#/144349238268d/detail/userstory/180133569200)
=> Fixed platform/general test

src/core/cloud.js, src/core/suite.js
* Won't fail platform tests unnecessarily
=> Avoiding a hard get of the `element` prop for platform tests

src/test/elements/sfdc/polling.js
* [SOBA](https://github.com/cloud-elements/soba/pull/7726)
* [RALLY-DE451](https://rally1.rallydev.com/#/144349238268d/detail/defect/174399865028)
=> Test for SFDC delete unused event poller records

src/cli/churros-test.js, src/test/elements/assets/basics.js
* Will run the basic tests synchronously for elements like netsuite or with api limiters
`churros test elements/closeio --sync`
https://cl.ly/3X1e3p2f2B0e
* Closes #[US4472](https://rally1.rallydev.com/#/144349238268d/detail/userstory/181221376728)
=> Added --sync option

src/test/elements/box/files.js
* Removed template from the body for API PATCH /files/{id}/custom-fields/{templateKey}
* [SOBA](https://github.com/cloud-elements/soba/pull/7786/files)
* [RALLY-#${DE534}](https://rally1.rallydev.com/#/144351344360/detail/defect/180126166108)
* Closes #[DE534](https://rally1.rallydev.com/#/144351344360/detail/defect/180126166108)
=> Removed template from the body for API PATCH /files/{id}/custom-fields/{templateKey}

src/test/elements/jira/worklogs.js
* Added the JIRA /worklogs APIs to the JIRA element.
* [[Soba](https://github.com/cloud-elements/soba/pull/7678)](Link to SOBA or Other PR for which tests were written, when applicable)
* [RALLUY-#${3001}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/172898464232)
=> Added the GET worklog API to the JIRA element. 

src/test/elements/assets/object.definitions.json, src/test/elements/quickbooksonprem/assets/creditcard-credits.json, src/test/elements/quickbooksonprem/assets/invoices.json, src/test/elements/quickbooksonprem/assets/journal-entries.json, src/test/elements/quickbooksonprem/assets/payments.json, src/test/elements/quickbooksonprem/assets/transformations.json, src/test/elements/quickbooksonprem/creditcard-credits.js, src/test/elements/quickbooksonprem/payments.js, src/test/elements/quickbooksonprem/vendor-credits.js
* Added Tests & Fixed Tests for Credit Card Credits & Vendor Credits
* [SOBA]https://github.com/cloud-elements/soba/pull/7825
* [RALLY-#${3147}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/174908006500)
* Closes #$US3147
=> Added and Fixed Churros for QBD. 

src/test/elements/closeio/contacts.js
* [SOBA]https://github.com/cloud-elements/soba/pull/7420
=> Add test for closeio fix

src/test/elements/xero/assets/employee.json, src/test/elements/xero/payments.js
* adds DELETE /payments to `payments` resource tests
* Added random value for Employee payload FirstName since employees aren't deleted and tests could potentially fail due to duplicate employee names
______________________________________________________________________
**Private:**
______________________________________________________________________
**Partner:**
______________________________________________________________________
**Public:**
______________________________________________________________________
* [SOBA](https://github.com/cloud-elements/soba/pull/7821)
* ~[CircleCI](Link to SOBA PR adding Tests to `circle.yml`, when applicable)~
* ~[churros-sauce](Link to Associated Churros-sauce PR, when applicable)~
* [RALLY-#US5539](https://rally1.rallydev.com/#/144349237612d/deta …
=> Xero - DELETE /payments

src/cli/churros-test.js, src/test/elements/assets/basics.js
* Will now only run the transformation test on the file resource given
* added quickbooksonprem to the synchronous calls and updated that logic
* [RALLY-#US5473](https://rally1.rallydev.com/#/144349238268d/detail/userstory/185205963420)
* [RALLY-#US5474](https://rally1.rallydev.com/#/144349238268d/detail/userstory/185205979968)
=> Updated transformation test to only run on resource given by --file flag

src/test/elements/connectwisecrmrest/assets/organizations.json
* Where is MH ?
```
churros test elements/connectwisecrmrest
info: Using url: https://staging.cloud-elements.com
info: Using user: t@tyler.com
info: Running tests for element: connectwisecrmrest
info: Provisioned with instance id of 74671
Basic tests
✓ should GET /objects (406ms)
- docs
✓ metadata (497ms)
✓ transformations (6836ms)
comments
✓ should allow CRUDS for /hubs/crm/incidents/{id}/comments (3077ms)
contacts
✓ should allow CRUDS for /hubs/crm/contacts (5802ms)
✓ should allow CRUDS for /hubs/crm/contacts (7108ms)
✓ should allow paginating with page and pageSize for /hubs/crm/contacts (2138ms)
✓ should support searching /hubs/crm/contacts by id (2309ms)
✓ should support searching /hubs/crm/contacts by email …
```
=> Updated CW Rest org payload to be valid

.github/PULL_REQUEST_TEMPLATE.md, src/test/platform/lbdocs/lbdocs.js
* Added validation to ensure purchased elements return 200
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/149)
* [TA4372](https://rally1.rallydev.com/#/144349238268d/detail/task/186763549396)
* Closes [TA4372](https://rally1.rallydev.com/#/144349238268d/detail/task/186763549396)
=> Adding basic lbdocs validation

src/test/platform/formulas/formulas.js
* Added integration tests for the `debug_logging_enabled` flag for formulas
* [RALLY-#US5259](https://rally1.rallydev.com/#/144349238268d/detail/userstory/184675880816)
* Closes #US5259
=> Added tests for the new debug_logging_enabled flag for Bodenstein formulas.

src/test/platform/formulas/assets/events/raw-case-webhook.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-sfdc-bulk1-instance.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-sfdc-bulk1.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-sfdc-bulk2-instance.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-sfdc-bulk2.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-sfdc-ticket-status.json, src/test/platform/formulas/assets/formulas/customer-formulas/lithium-ticket-instance.json, src/test/platform/formulas/assets/load-common.js, src/test/platform/formulas/customer-formulas.js, src/test/platform/formulas/load.js
* Tests for ticket status and bulk sync use cases
* [US3034](https://rally1.rallydev.com/#/144349238268d/detail/userstory/173800027756)
=> Additional v3 formula execution tests for specific use cases

src/test/elements/quickbooks/estimates.js, src/test/elements/quickbooks/invoices.js, src/test/elements/xero/invoices.js
* ☝️ 
* [SOBA](https://github.com/cloud-elements/soba/pull/7858)
* [RALLY](https://rally1.rallydev.com/#/144349237612d/detail/task/188159598836)
* [TA-4701](https://rally1.rallydev.com/#/144349237612d/detail/task/188159598836)
=> QBO test for downloading pdf for invoices

src/test/elements/jira/contacts.js, src/test/elements/jira/incidents.js
* Clean up users created no matter what
* quick fixed a test
* contacts were failing before, hence why the clean up is necessary 
https://cl.ly/2R153U2a1p35
* [RALLY-#US5219](https://rally1.rallydev.com/#/144349238268d/detail/userstory/184245259204)
=> Jira: clean up after user creation

src/cli/churros-test.js
* Cut the test case time out to 5 min
=> Reduced overall timeout

src/test/elements/dropbox/folders.js, src/test/elements/dropbox/links.js, src/test/elements/dropboxbusiness/folders.js, src/test/elements/dropboxbusinessv2/folders.js, src/test/elements/dropboxv2/folders.js
* added test for changes and commented out test that are failing on nightly build because dropboxbusiness does not support these
* https://github.com/cloud-elements/soba/pull/7866
=> added test for parentFolderId changes

src/test/elements/xero/assets/credit-memo-POST-allocations.json, src/test/elements/xero/assets/credit-memo-allocation.json, src/test/elements/xero/assets/invoice-POST-allocations.json, src/test/elements/xero/credit-memos.js
* `POST /credit-memos/:id/allocations`
**Public**:
**Private**:
**Partner**:
* [SOBA](https://github.com/cloud-elements/soba/pull/7850)
~* [CircleCI](Link to SOBA PR adding Tests to `circle.yml`, when applicable)~
~* [churros-sauce](Link to Associated Churros-sauce PR, when applicable)~
* [RALLY-#US5826](https://rally1.rallydev.com/#/144349237612d/detail/userstory/186752482156)
=> Xero endpoint test

src/core/tools.js, src/test/elements/slack/users.js, test/core/tools.test.js
* Fixing randomStr function returning an empty string.
* Many tests were incorrectly calling the function
* Added unit tests
=> Slack - fixing random string returning empty

src/core/tools.js, src/test/elements/slack/channels.js, src/test/elements/slack/users.js, test/core/tools.test.js
=> Fix Slack channels/{}/actions

src/test/elements/twiliov2/assets/transformations.json
Since transformation was not present, the basic test for transformation were failing.
* [DE610](https://rally1.rallydev.com/#/144349237612d/detail/defect/184430697148)
* Closes #[DE610](https://rally1.rallydev.com/#/144349237612d/detail/defect/184430697148)
=> Added transformation file to Twilio v2 churros

src/test/elements/sapc4ccrm/assets/opportunities.json
* SAPC4C CRM tests fix
```
ip-192-168-1-77:churros ramana$ churros test elements/sapc4ccrm
info: Using url: http://localhost:5050
info: Using user: churros@ce.com
info: Using oauth username: ELEMENTSCLAUDE7000109
info: Running tests for element: sapc4ccrm
info: Provisioned with instance id of 6354
Basic tests
✓ should GET /objects (3315ms)
- docs
✓ metadata (311ms)
error: Failed to retrieve or validate: /hubs/crm/ServiceRequestAttachmentFolder
error: Failed to retrieve or validate: /hubs/crm/comments
error: Failed to retrieve or validate: /hubs/crm/ServiceRequestDescription
error: Failed to retrieve or validate: /hubs/crm/attachments
✓ transformations (14176ms)
accounts
✓ should allow …
```
=> SAPC4C CRM tests fix

src/test/platform/formulas/assets/formulas/retry-formula.json
* Test that the formula retry step property can contain a range
* [SOBA](https://github.com/cloud-elements/soba/pull/7914)
* [DE742](https://rally1.rallydev.com/#/144349238268d/detail/defect/190616781600)
=> Test that the formula retry step property can contain a range

src/test/elements/googledrive/folders.js, src/test/elements/googledrive/search.js
* ☝️ 
* [SOBA](https://github.com/cloud-elements/soba/pull/7929)
* [RALLY-TA5523](https://rally1.rallydev.com/#/144349237612ud/detail/task/190586276000)
* [RALLY-TA5523](https://rally1.rallydev.com/#/144349237612ud/detail/task/190586276000)
=> Fixed search tests and moved/formatted folders

src/test/platform/formulas/assets/load-common.js, src/test/platform/formulas/load.js
* Fix closeio event generation and formula load tests
=> Fix the closeio formula load tests by fixing the event generation

src/test/platform/formulas/analytics.js
* New test for current formula execution status API.
* [PR 7930](https://github.com/cloud-elements/soba/pull/7930)
* [RALLY-#US6049](https://rally1.rallydev.com/#/144349238268d/detail/userstory/188488984420)
=> Formula status tests

src/test/platform/events/disposition.js, src/test/platform/formulas/errors.js
* Allow running formula error tests with V3 engine
* [SOBA](https://github.com/cloud-elements/soba/pull/7960)
=> Allow running formula error tests with V3 engine

src/test/elements/mailchimpv3/campaigns.js, src/test/elements/mailchimpv3/contacts.js
added tests for the following endpoints
* /hubs/marketing/campaigns/{id}/email-activities/{emailId}
* /hubs/marketing/campaigns/{id}/email-activity
* /hubs/marketing/contacts
* [SOBA](https://github.com/cloud-elements/soba/pull/7918/files)
* [RALLY-#${US6073}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/188750379736)
* Closes #${US6073}
=> tests for mailchimp enhancements to campaigns and contacts

src/test/elements/freshbooks/assets/vendors.json, src/test/elements/freshbooks/vendors.js
* Updated churros testcase for Vendors API. The payload will have random email passed while creating new Vendor.
* [SOBA](https://github.com/cloud-elements/soba/pull/7956)
* [Closes #${US8122}](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/196246565976)
=> Freshbooks : Fixed failing testcase for vendors API

src/test/platform/events/disposition.js, src/test/platform/formulas/assets/formulas/form-request.json, src/test/platform/formulas/errors.js, src/test/platform/formulas/executions.js
* Add a formula test that uses the form property for v3 formula executions
* [SOBA](https://github.com/cloud-elements/soba/pull/7988)
* [RALLY-#${US7295}](https://rally1.rallydev.com/#/144349238268d/detail/userstory/192442824652)
=> Add a formula test that uses the form property for v3 formula executions

src/test/elements/assets/object.definitions.json, src/test/elements/sapbusinessone/assets/transformations.json, src/test/elements/sapbusinessone/project-codes.js
* (https://github.com/cloud-elements/soba/pull/7990)
* [US7270](https://rally1.rallydev.com/#/144349237612d/detail/userstory/192208402652)
=> Added Test for Project Codes For SAP B1

src/test/platform/changemanagement/commits.js, src/test/platform/changemanagement/pull-requests.js
* Change Management tests for commit and pull-request APIs
* [SOBA](https://github.com/cloud-elements/soba/pull/8029)
=> Change Management tests for commit and pull-request APIs

src/test/platform/elements/assets/element.elementmodel.payload.json, src/test/platform/elements/assets/element.elementmodel.schema.json, src/test/platform/elements/assets/element.elementmodelfield.payload.json, src/test/platform/elements/assets/element.elementmodelfield.schema.json, src/test/platform/elements/modelfields.js, src/test/platform/elements/models.js
* Added tests for models and model fields
https://cl.ly/3O3w2I1s1W1Q/download/Image%202018-02-05%20at%206.03.57%20PM.png
* [8016](https://github.com/cloud-elements/soba/pull/8016)
=> Model tests

src/test/lifecycle.js
* There are no longer any API calls to `/api-v1` anywhere in churros, cause that API is old and soon to be destroyed. ⚔️ 
* [US8261](https://rally1.rallydev.com/#/144349238268d/detail/userstory/197580166764)
=> Removed V1 API calls from code

src/test/platform/elements/models.js
* [SOBA](https://github.com/cloud-elements/soba/pull/8067)
=> Add a test for upserting models

src/test/platform/changemanagement/pull-requests.js
* Add new pr tests for searching own and update/search by admin
* [SOBA](https://github.com/cloud-elements/soba/pull/8048)
=> Add new pr tests for searching own and update/search by admin

src/test/platform/formulas/assets/formulas/returns-info.json, src/test/platform/formulas/executions.js
* Add a test to verify the info portion of the formula execution context
* [SOBA](https://github.com/cloud-elements/soba/pull/8089)
=> Add a test to verify the info portion of the formula execution context

src/test/platform/changemanagement/assets/elementmodel.json, src/test/platform/changemanagement/pull-requests.js, src/test/platform/elements/models.js
* Adds an actual model for CloseIO element, uploads to s3 on PR creation
* [SOBA](https://github.com/cloud-elements/soba/pull/8088)
=> Change Management tests with model

src/test/platform/changemanagement/pull-requests.js
* Add test for merging a model PR
* [SOBA](https://github.com/cloud-elements/soba/pull/8085)
=> Add test for merging a model PR

src/test/elements/gotowebinar/assets/meetings.json, src/test/elements/gotowebinar/meetings.js
* Fixed failing /meetings Testcases.
* Fixed incorrect payload.
* [SOBA](https://github.com/cloud-elements/soba/pull/8097)
* [RALLY-#${DE609}](https://rally1.rallydev.com/#/144349237612d/detail/defect/184416267704)
* [RALLY-#${DE609}](https://rally1.rallydev.com/#/144349237612d/detail/defect/184416267704)
=> Gotowebinar: Fixed Failing Testcases 

src/test/platform/changemanagement/pull-requests.js, src/test/platform/elements/assets/element.elementmodel.payload.json
* Expand the PR merge test to test a deletion request
* [SOBA](https://github.com/cloud-elements/soba/pull/8107)
=> Expand the PR merge test to test a deletion request

src/core/oauth.js
* ☝️ 
* merged the sauce already
* [TA8473](https://rally1.rallydev.com/#/144349237612d/detail/task/199597326960)
* [TA8473](https://rally1.rallydev.com/#/144349237612d/detail/task/199597326960)
=> Fixing Sharepoint OAuth flow

src/test/elements/pardot/visitors.js, src/test/elements/pardot/visits.js
* 🌮 
* [SOBA](https://github.com/cloud-elements/soba/pull/8093)
* [RALLY - US8329](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197920052928)
=> Pardot - tests for visits & visitors

src/test/elements/salesforcemarketingcloud/assets/dataExtension.json, src/test/elements/salesforcemarketingcloud/data-extensions.js
* Fixed churros for SFMC /data-extensions resource
* https://github.com/cloud-elements/soba/pull/8077
=> Fixed churros for SFMC /data-extensions resource

src/test/elements/gooddata/projects.js
* Skipped the test cases for the `projects` resource as no creds  with admin rights are available
* [SOBA](https://github.com/cloud-elements/soba/pull/8101)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/162)
* [RALLY-#US7696](https://rally1.rallydev.com/#/144349237612d/detail/userstory/195164189260)
* [RALLY-#US8698](https://rally1.rallydev.com/#/144349237612d/detail/userstory/199131878840)
* [#US7696](https://rally1.rallydev.com/#/144349237612d/detail/userstory/195164189260)
* [#US8698](https://rally1.rallydev.com/#/144349237612d/detail/userstory/199131878840)
=> Skipped the test cases for projects on GoodData

src/core/provisioner.js, src/test/platform/accounts/users.js, src/test/platform/users/users.js
* New tests for job disablement on user deactivation.
* [Soba #7877](https://github.com/cloud-elements/soba/pull/7877)
* [RALLY-#US5044](https://rally1.rallydev.com/#/144349238268d/detail/userstory/182625281088)
=> Disable jobs tests for US5044

src/test/platform/transformations/assets/nofield-definition.json, src/test/platform/transformations/commonResources.js, src/test/platform/transformations/scripts.js, src/test/platform/transformations/transformations.js
* Added tests for js only transformations in v2
https://cl.ly/2l132w0v1Y0H
* [SOBA](https://github.com/cloud-elements/soba/pull/8038)
* [DE767](https://rally1.rallydev.com/#/144349238268d/detail/defect/192188657488)
=> JS only transformations

src/test/elements/freshservice/users.js
* Fixed where clause for the Freshservice element.
* [SOBA](https://github.com/cloud-elements/soba/pull/7708)
* [RALLY-#${US3151}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/174912047924)
* Closes #${US3151}
=> Fixed where clause for freshservice

src/test/elements/quickbooksonprem/assets/tax-codes.json, src/test/elements/quickbooksonprem/assets/tax-rates.json, src/test/elements/quickbooksonprem/customers.js, src/test/elements/quickbooksonprem/tax-codes.js, src/test/elements/quickbooksonprem/tax-rates.js
* Added tests for TaxCodes and TaxRates
=> New Tests for TaxCodes and TaxRates

src/test/elements/docusign/ping.js, src/test/elements/marketo/assets/programsLeads.json, src/test/elements/marketo/ping.js, src/test/elements/sfdc/ping.js, src/test/elements/sharefile/files.js, src/test/elements/slack/ping.js, src/test/elements/twiliov2/ping.js
Enhanced Test cases for `slack`, `sharefile`, `marketo`, `sfdc`, `twiliov2` and `docusign` with `/ping API`
* Added PING API for elements
* Fixes Churros for sharefile 
> should get file metadata by id/path 
> should delete file by path                 
> should copy file by id/path               
* Fixes Churros for `programsLeads.json Payload`
[SOBA](https://github.com/cloud-elements/soba/pull/8096)
[Marketo_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540741876)
[Slack_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540741532)
[Twiliov2_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540739560)
[Sharefile_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540739296) …
=> Enhanced slack, sharefile, marketo, sfdc, twiliov2 and docusign with /ping API

src/test/platform/elementbuilder/assets/import/odata_northwind.xml, src/test/platform/elementbuilder/import.js
* OData import churros
```elements-mac112:churros ramana$ churros test platform/elementbuilder --file import
element import
✓ should support converting and creating a SOAP element (10701ms)
✓ should support converting and creating a element From Swagger (6919ms)
✓ should support converting and creating a element From Odata (2433ms)
3 passing (21s)
```
* [SOBA#8110](https://github.com/cloud-elements/soba/pull/8110)
* [US7616](https://rally1.rallydev.com/#/144349238268d/detail/userstory/194210824536)
* [US7615](https://rally1.rallydev.com/#/144349238268d/detail/userstory/194210817484)
* [US7614](https://rally1.rallydev.com/#/144349238268d/detail/userstory/194196248968)
=> OData import churros

src/test/elements/assets/object.definitions.json, src/test/elements/dynamicscrmadfs/assets/cases.json, src/test/elements/dynamicscrmadfs/assets/knowledge-articles.json, src/test/elements/dynamicscrmadfs/assets/transformations.json, src/test/elements/dynamicscrmadfs/cases.js, src/test/elements/dynamicscrmadfs/knowledge-articles.js
=> Added churros for knowledge-articles and cases resources for dynamicscrmadfs

src/test/elements/woocommercerest/orders.js, src/test/elements/woocommercerest/products.js
* ☝️ 
* [SOBA](https://github.com/cloud-elements/soba/pull/8126)
* [TA8660](https://rally1.rallydev.com/#/144349237612d/detail/task/200215631444)
* [TA8660](https://rally1.rallydev.com/#/144349237612d/detail/task/200215631444)
=> Added tests for normalized where params for WooCommerce

src/core/oauth.js
* Added ability to provision Docusign element using an Oauth2
* Added selenium script for provisioning Docusign instance using Oauth2
* [SOBA](https://github.com/cloud-elements/soba/pull/8090)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/158)
* [RALLY-#${ticketNumber}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/196739032056)
* [US-8147](https://rally1.rallydev.com/#/144349237612d/detail/userstory/196739032056)
=> Added Docusign OAuth2 flow

src/core/defaults.js, src/test/platform/changemanagement/pull-requests.js, src/test/platform/changemanagement/releases.js
* Add tests for releasing a model
* [SOBA](https://github.com/cloud-elements/soba/pull/8160)
=> Add tests for releasing a model

src/test/platform/elements/assets/element.elementmodel.payload.json, src/test/platform/elements/assets/element.elementmodelfield.payload.json, src/test/platform/elements/models.js
* Tests associating a list of resources with a model
* [SOBA](https://github.com/cloud-elements/soba/pull/8190)
=> Associate resource with model

src/core/oauth.js
* Just updated the OAuth flow for freshbooksv2 (Freshbooks Cloud Accounting)
* [RALLY-#${DE1022}](https://rally1.rallydev.com/#/144349237612d/detail/defect/202278757036)
* [DE1022](https://rally1.rallydev.com/#/144349237612d/detail/defect/202278757036)
=> Updated OAuth for freshbooksv2

src/test/elements/eloqua/accounts.js
* Added churros test for Accounts API.
* [SOBA](https://github.com/cloud-elements/soba/pull/8130)
* [RALLY-US8504](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042340)
* [US8504](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042340)
=> Eloqua : Added test for Accounts API

src/core/oauth.js, src/test/elements/evernote/files.js
* Added tests for `DELETE /files` & `DELETE /files/{id}`
* [SOBA](https://github.com/cloud-elements/soba/pull/7835)
* ~[CircleCI](Link to SOBA PR adding Tests to `circle.yml`, when applicable)~
* ~[churros-sauce](Link to Associated Churros-sauce PR, when applicable)~
* [RALLY-#US5461](https://rally1.rallydev.com/#/144349237612d/detail/userstory/185167492424)
=> Evernote - Added DELETE files tests

src/test/elements/googlesuite/assets/messages.json, src/test/elements/googlesuite/messages.js, src/test/elements/googlesuite/threads.js
* Added ceql search tests for `messages` and `threads` objects.
* [RALLY-#DE878](https://rally1.rallydev.com/#/144349237612ud/detail/defect/197449254688)
* Closes #DE878
=> Added ceql search tests :Google Suite

src/core/suite.js, src/core/tools.js, src/test/elements/assets/object.definitions.json, src/test/elements/autotaskhelpdesk/assets/transformations.json, src/test/elements/hubspot/bulk.js, src/test/elements/lifecycle.js, test/core/tools.test.js
* ☝️ 
* [DE-233](https://rally1.rallydev.com/#/144349237612d/detail/defect/163745590556)
* [DE-456](https://rally1.rallydev.com/#/144349237612d/detail/defect/174604529972)
* [DE-457](https://rally1.rallydev.com/#/144349237612d/detail/defect/174608281560)
* [DE-233](https://rally1.rallydev.com/#/144349237612d/detail/defect/163745590556)
* [DE-456](https://rally1.rallydev.com/#/144349237612d/detail/defect/174604529972)
* [DE-457](https://rally1.rallydev.com/#/144349237612d/detail/defect/174608281560)
=> Fixed various bulk tests and added handling for non-json-l responses in bulk download

src/test/elements/sfdcdocuments/assets/comment.json, src/test/elements/sfdcdocuments/assets/test.txt, src/test/elements/sfdcdocuments/files.js
* Added testcases for  CRDS : /files/{id}/comments APIs.
* Added testcases for  CR : /files/comments  APIs.
* Added testcases for  RD : /files/comments/{comments_id} APIs.
* [SOBA](https://github.com/cloud-elements/soba/pull/7976)
* [RALLY-#${US6045}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/188485581736)
* Closes [US6045](https://rally1.rallydev.com/#/144349237612d/detail/userstory/188485581736)
=> SFDC: Added test cases for comments API

src/test/platform/elements/assets/element.elementmodel.payload.json, src/test/platform/elements/assets/element.elementmodelfield.payload.json, src/test/platform/elements/assets/element.elementmodelfield.schema.json, src/test/platform/elements/modelfields.js
* Refactored model fields tests to support commitMessages (and also work )
* [SOBA](https://github.com/cloud-elements/soba/pull/8187)
* [RALLY-#4521](https://rally1.rallydev.com/#/144349238268d/detail/userstory/181858388172)
=> Refactored model fields tests to support commitMessages (and also work )

src/test/elements/bullhorn/assets/client-contacts.json, src/test/elements/bullhorn/client-contacts.js
* Added CRUD API tests.
* [SOBA](https://github.com/cloud-elements/soba/pull/8133)
* [RALLY-#US8503](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/198554042096)
=> Added CRUD tests for 'client-contacts': Bullhorn

src/test/elements/twiliov2/assets/models_accounts_get.json, src/test/elements/twiliov2/assets/models_accounts_post.json, src/test/elements/twiliov2/assets/models_addresses_get.json, src/test/elements/twiliov2/assets/models_addresses_post.json, src/test/elements/twiliov2/assets/models_messages_get.json, src/test/elements/twiliov2/assets/models_messages_media_get.json, src/test/elements/twiliov2/assets/models_messages_post.json
=> Added json payload for Twiliov2. Messages, Accounts, Addresses Resource.

src/test/elements/acton/assets/models_contacts_patch.json, src/test/elements/acton/assets/models_contacts_post.json, src/test/elements/acton/assets/models_lists_patch.json, src/test/elements/acton/assets/models_lists_post.json
* Added payload for accounts and lists post and patch resource of Act-on
=> Act-on: added payload for contacts and lists resource

src/test/elements/bullhorn/assets/models_client_contacts_get.json, src/test/elements/bullhorn/assets/models_client_contacts_patch.json, src/test/elements/bullhorn/assets/models_client_contacts_post.json, src/test/elements/bullhorn/assets/models_leads_get.json, src/test/elements/bullhorn/assets/models_leads_patch.json, src/test/elements/bullhorn/assets/models_leads_post.json, src/test/elements/bullhorn/assets/models_opportunities_get.json, src/test/elements/bullhorn/assets/models_opportunities_patch.json, src/test/elements/bullhorn/assets/models_opportunities_post.json
* Added Payloads for Lead, Opportunity,ClientContact; Methods GET, POST & PATCH
=> Payloads for Lead, Opportunity,ClientContact; Methods GET, POST & PATCH

src/test/elements/square/ping.js, src/test/elements/square/transactions.js
* Added Test cases for 
`/ping API`
* Commented /Transaction API since it get worked out on Sandbox
[Soba](https://github.com/cloud-elements/soba/pull/8159)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/181049644456)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/197795535044)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/197796555608)
=> Enhanced Square by adding Testcases for /ping

src/test/platform/elements/models.js
=> Add test to get all models for an element

src/test/elements/onedrivebusiness/me.js
* Added test for GET /me API
* [SOBA](https://github.com/cloud-elements/soba/pull/8235)
* [RALLY-US9353](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677249368)
* [US9353](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677249368)
=> Onedrive for Business : Added test for GET /me

src/test/elements/amazons3/me.js, src/test/elements/box/me.js
* Added /me test cases for Box element
[Soba](https://github.com/cloud-elements/soba/pull/8280)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677247952)
=> Enhanced Box and amazons3 with /me Test cases

src/test/elements/sharepoint/me.js
* Added `GET /me API` test cases to sharepoint
[Soba](https://github.com/cloud-elements/soba/pull/8295)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677249648)
=> Enhanced sharepoint with /me Testcases

src/test/elements/googledrive/me.js
* Added /me API for Google Drive
> PS C:\Users\GS-1259\CE-4656\churros\finalch\churros-sauce> churros -i 624 test elements/googledrive
info: Using oauth username: churros.sauce@gmail.com
info: Using api key: 232945639549-cj65c4aeacj68nnv0mfpvv7m0v9e0eg2.apps.googleusercontent.com
info: Running tests for element: googledrive
info: Provisioned with instance id of 624
Basic tests
√ should GET /objects (270ms)
- docs
√ metadata (567ms)
error: Failed to delete /instances/624/transformations
error: Failed to delete /instances/624/transformations
√ transformations (625ms)
files
√ should allow ping for googledrive (360ms)
√ should allow CRD for …
=> Added me API for Google Drive

src/test/elements/sapc4ccrm/assets/contacts.json
* Updated POST payload for Contacts resource to fix churros failure.
* [DE1090](https://rally1.rallydev.com/#/144349237612d/detail/defect/204771712980)
=> SAP Hybris CRM: Updated POST contacts payload

src/test/elements/zohocrm/assets/cases.json, src/test/elements/zohocrm/assets/transformations.json, src/test/elements/zohocrm/cases.js
* Added churros tests for CRUDS operation for /cases API.
* All test are passing.
* [SOBA](https://github.com/cloud-elements/soba/pull/8273)
* [RALLY-US10062](https://rally1.rallydev.com/#/144349237612d/detail/userstory/203777853404)
* [US10062](https://rally1.rallydev.com/#/144349237612d/detail/userstory/203777853404)
=> Zoho CRM : Added tests for /cases API

src/test/elements/intacct/assets/model_Customer_PATCH.json, src/test/elements/intacct/assets/model_Customer_POST.json, src/test/elements/intacct/assets/model_Invoices_PATCH.json, src/test/elements/intacct/assets/model_Invoices_POST.json
Updated payloads for Intacct for below objects
- Customers
- Invoices
* PR #[8297](https://github.com/cloud-elements/soba/pull/8297)
=> Payloads for Invoices and Customers for Intacct element

src/test/elements/quickbooks/objects.js
* ☝️ 
* [RALLY-DE1238](https://rally1.rallydev.com/#/144349237612d/detail/defect/209353398176)
=> Added objects & object metadata test to Quickbooks

src/test/elements/mailchimpv3/assets/model_List_Contacts_PATCH.json, src/test/elements/mailchimpv3/assets/model_List_Contacts_POST.json, src/test/elements/mailchimpv3/assets/model_List_PATCH.json, src/test/elements/mailchimpv3/assets/model_List_POST.json, src/test/elements/mailchimpv3/assets/model_lists_{id}_fields_POST.json, src/test/elements/mailchimpv3/assets/model_lists_{id}_fields_{fieldId}_PATCH.json, src/test/elements/mailchimpv3/assets/models_campaigncomments_patch.json, src/test/elements/mailchimpv3/assets/models_campaigncomments_post.json, src/test/elements/mailchimpv3/assets/models_campaigns_patch.json, src/test/elements/mailchimpv3/assets/models_campaigns_post.json
* Uploaded payloads for `lists`, `campaigns` and `reports` object for `mailchimpv3` 
*  [Soba ](https://github.com/cloud-elements/soba/pull/8331)
* #[US9761](https://rally1.rallydev.com/#/176629158268d/detail/userstory/203300525368)
* #[US9760](https://rally1.rallydev.com/#/144349237612d/detail/userstory/203301242412)
* #[US10387](https://rally1.rallydev.com/#/176629158268d/detail/userstory/206196186156)
* #[US9759](https://rally1.rallydev.com/#/144349237612d/detail/userstory/203300892036)
=> Mailchimp Payloads 

src/test/elements/eloqua/objectMetadata.js
* 💥 
* https://github.com/cloud-elements/soba/pull/8269
* [RALLY-US10228](https://rally1.rallydev.com/#/144349237612d/detail/userstory/204671964644?fdp=true)
=> Tests for GET /object/{objectName}/metadata customFieldsOnly parameter

src/test/platform/vdrs/transformations.js, src/test/platform/vdrs/vdrs.js
* Test cloning a VDR and it's transformations from the system catalog to the user's account
* [SOBA](https://github.com/cloud-elements/soba/pull/8393)
=> Add test for the VDR clone API

src/test/platform/transformations/transformations.js, src/test/platform/vdrs/transformations.js
* Add tests to ensure GET common-resource and vdrs return a list of mapped elementIds
* [SOBA](https://github.com/cloud-elements/soba/pull/8369)
=> Add tests to ensure GET common-resource and vdrs return a list of mapped elementIds

src/test/elements/hubspot/assets/model_contact_properties_post.txt, src/test/elements/hubspot/assets/model_contact_properties_propertyId_patch.txt, src/test/elements/hubspot/assets/model_contact_propertygroups_post.txt, src/test/elements/hubspot/assets/model_contact_propertygroups_propertygroupId.txt, src/test/elements/hubspot/assets/model_workflow_post.txt, src/test/elements/hubspot/assets/model_workflow_workflowId_contacts_patch.txt
* Added Payloads for workflows,contacts(subresorces )APIs in Hubspot marketing element.
* For POST and PATCH request payloads are added. 
* https://github.com/cloud-elements/soba/pull/8313
=> Hubspot marketing Payload

src/test/platform/elements/instances.js, src/test/platform/formulas/instances.js
* Tests the `searchText` functionality
Formulas: https://cl.ly/3r1I2X3g2x0G
Elements: https://cl.ly/433t2C1t2o0l //One was previously failing
* [SOBA](https://github.com/cloud-elements/soba/pull/8364)
*  [US10475](https://rally1.rallydev.com/#/144349238268d/detail/userstory/206997202052)
=> SearchText tests

src/test/elements/freshdeskv2/contacts.js
* ☝️ 
* [SOBA](https://github.com/cloud-elements/soba/pull/8389)
* [TA-12111](https://rally1.rallydev.com/#/144349237612d/detail/task/209160156432)
* [TA-12111](https://rally1.rallydev.com/#/144349237612d/detail/task/209160156432)
=> Freshdesk test for escaped single quote

src/test/elements/eloqua/assets/contacts-bulk.json, src/test/elements/eloqua/bulk.js
* ☝️ 
* [SOBA](https://github.com/cloud-elements/soba/pull/8414)
* [TA-12542](https://rally1.rallydev.com/#/144349237612d/detail/task/210267213284)
* [TA-12542](https://rally1.rallydev.com/#/144349237612d/detail/task/210267213284)
=> Added bulk insert test

src/test/elements/box/folders.js, src/test/elements/box/search.js, src/test/elements/docushareflex/folders.js, src/test/elements/docushareflex/search.js, src/test/elements/dropbox/folders.js, src/test/elements/dropboxbusiness/folders.js, src/test/elements/dropboxbusinessv2/folders.js, src/test/elements/dropboxv2/folders.js, src/test/elements/dropboxv2/search.js, src/test/elements/egnyte/folders.js, src/test/elements/egnyte/search.js, src/test/elements/evernote/folders.js, src/test/elements/evernote/search.js, src/test/elements/googledrive/folders.js, src/test/elements/googledrive/search.js, src/test/elements/onedrive/folders.js, src/test/elements/onedrive/search.js, src/test/elements/onedrivebusiness/folders.js, src/test/elements/onedrivev2/folders.js, src/test/elements/onedrivev2/search.js, src/test/elements/onenote/folders.js, src/test/elements/sfdcdocuments/folders.js, src/test/elements/sfdcdocuments/search.js, src/test/elements/sfdclibraries/folders.js, src/test/elements/sfdclibraries/search.js, src/test/elements/sharepoint/folders.js, src/test/elements/sharepoint/search.js
* Added nextPage Pagination tests to all folders and search endpoints in Docs Hub elements
* https://github.com/cloud-elements/soba/pull/8380
* [RALLY-DE1071](https://rally1.rallydev.com/#/144349237612d/detail/defect/204617662972)
=> Tests for nextPage in Docs Hub

src/test/platform/transformations/transformations.js
=> Use the right name for objs for renaming payload

src/core/cloud.js, src/test/platform/elements/instances.js
* Added tests for the v2 get /objects endpoint
* [SOBA](https://github.com/cloud-elements/soba/pull/8387)
* [RALLY-#{US9427}](https://rally1.rallydev.com/#/144349238268d/detail/userstory/202270635988)
* Closes [US9427](https://rally1.rallydev.com/#/144349238268d/detail/userstory/202270635988)
=> Object api

src/test/platform/vdrs/assets/transformation.schema.json, src/test/platform/vdrs/assets/vdr.json, src/test/platform/vdrs/assets/vdr.schema.json
* Updated tests
https://cl.ly/3T302P012K2R
* [SOBA](https://github.com/cloud-elements/soba/pull/8488)
=> Update tests for new vdr fields

src/test/elements/docushareflex/files.js, src/test/elements/docushareflex/search.js
* 🐗 
* https://github.com/cloud-elements/soba/pull/8505
* [US10849](https://rally1.rallydev.com/#/144349237612d/detail/userstory/210887507392)
=> Docushare Flex tests for custom fields

src/test/elements/egnyte/files.js
* Added test cases for following API's
`files/revisions`
`files/revisions/{revisionId}`
`files/{id}/revisions`
`files/{id}/revisions/{revisionId}`
*Note: The above churros is failing randomly with a error message "message":"Request failed","providerMessage":"errorMessage - Not Acceptable"
* [SOBA](https://github.com/cloud-elements/soba/pull/8454)
* [RALLY-#${US-10668}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/209347303936)
* [US-10668](https://rally1.rallydev.com/#/144349237612d/detail/userstory/209347303936)
=> Egnyte: added /revisions API test cases

src/test/elements/bullhorn/assets/job-submissions.json, src/test/elements/bullhorn/job-submissions.js
* Added CRUDS for `job-submissions` for Bullhorn.
* [SOBA](https://github.com/cloud-elements/soba/pull/8513)
* [US10845](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/210886836208)
* [US10845](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/210886836208)
=> Bullhorn : Added job-submissions testcase

src/test/platform/transformations/assets/transformationFunctions.json, src/test/platform/transformations/scripts.js
* Testing the accessibility of new grover functions
https://cl.ly/1d2S140z3A3C
* [grover](https://github.com/cloud-elements/grover/pull/79)
* [grover](https://github.com/cloud-elements/grover/pull/78)
* Closes [US11053](https://rally1.rallydev.com/#/144349238268d/detail/userstory/212883709876)
=> Testing native grover functions

src/test/elements/zendesk/bulk.js
* Added bulk JSON download integration test for the Zendesk element
* https://github.com/cloud-elements/soba/pull/8572
* [DE1350](https://rally1.rallydev.com/#/144349238268d/detail/defect/212410500704)
* Closes #[DE1350](https://rally1.rallydev.com/#/144349238268d/detail/defect/212410500704)
=> Added bulk JSON download integration test for the Zendesk element

src/test/platform/vdrs/transformations.js
* Updated existing cloning test 
* Added tests for selective transformation cloning
* [SOBA](https://github.com/cloud-elements/soba/pull/8604)
* [RALLY-#US11251](https://rally1.rallydev.com/#/144349238268d/detail/userstory/214462716272)
=> Vdr clone api

src/core/oauth.js
* Modified webdriver code as per new vendor OAuth URLs ([here](https://developer.hootsuite.com/v1.0/docs/upgrading-to-platform-hootsuite-com?utm_source=notification_one&utm_medium=email&mkt_tok=eyJpIjoiTTJSa05HSTBaVGswWVRGaCIsInQiOiJcL3hiZ3dJcU5SZG1QVW5BUlJcL29McXRDMzVKNWRIVmE5MkphSkMyakJ0QmhGZFhjMURIakJqZnNOb2NrSDdMa1dHTFFzRnk0RGNCSHNrZ3BRVmY1Tk1sTE44R1pGV0JWVlF0NEpMSmtBb2dYWExhbCtIczZaajRTT1hIUFRrWTZSIn0%3D))
* [SOBA](https://github.com/cloud-elements/soba/pull/8471)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/186)
* [RALLY-#US10675](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/209349943528)
* [US10675](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/209349943528)
=> Modified webdriver code for Hootsuite

src/test/elements/assets/object.definitions.json, src/test/elements/github/assets/transformations.json, src/test/elements/github/branches.js, src/test/elements/github/me.js, src/test/elements/github/repositories.js, src/test/elements/github/users.js
* Added test cases for :
* Branches
* Me
* users
* repositories
* Have not added tests for pull-requests as valid PRs need to be there to perform action which is not possible to test everytime with the test-suite.
* [SOBA](https://github.com/cloud-elements/soba/pull/8566)
* [RALLY-US11281](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214559653052)
* [US11281](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214559653052)
=> GitHub : Added test cases

src/test/elements/assets/object.definitions.json, src/test/elements/caagilecentral/assets/createDefect.json, src/test/elements/caagilecentral/assets/createUserStory.json, src/test/elements/caagilecentral/assets/transformations.json, src/test/elements/caagilecentral/defects.js, src/test/elements/caagilecentral/ping.js, src/test/elements/caagilecentral/projects.js, src/test/elements/caagilecentral/userStory.js
* Added test cases for new Agile Central (Rally) element.
* Tests added for:
* Defects
* Projects
* Ping
* User story
* [SOBA](https://github.com/cloud-elements/soba/pull/8676)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/191)
* [RALLY-US11282](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214559654844)
* [US11282](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214559654844)
=> Agile Central (Rally) - Added test cases for new element

src/test/platform/applications/applications.js, src/test/platform/applications/assets/application.json
* Test changed /applications endpoints to be authenticated and limited to org admins
* [SOBA](https://github.com/cloud-elements/soba/pull/8712)
* [RALLY-US10530](https://rally1.rallydev.com/#/144349238268d/detail/userstory/207600198612)
=> Test for changes to /applications API

src/test/elements/marketo/programs.js
* Added an integration test for the Marketo element's `GET /objects/programs/metadata` API
* https://github.com/cloud-elements/soba/pull/8710
* [RALLY-#DE1702](https://rally1.rallydev.com/#/144349238268d/detail/defect/220959547292)
* Closes #[DE1702](https://rally1.rallydev.com/#/144349238268d/detail/defect/220959547292)
=> Added an integration test for metadata for the Marketo element's program resource

src/test/elements/eloqua/accounts.js, src/test/elements/eloqua/contacts.js
* Added testcases for  `GET /accounts/{id}/membership` and `GET /contacts/{id}/membership` APIs
* [SOBA](https://github.com/cloud-elements/soba/pull/8651)
* [US11698](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/217748477308)
* [US11697](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/217749004176)
* [US11698](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/217748477308)
* [US11697](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/217749004176)
=> Eloqua : Updated testcases for membership API for Contacts and Accounts

src/test/elements/intacct/assets/sales-orders.json
* Updated payload for POST /sales-orders
[IntacctChurrosResults.txt](https://github.com/cloud-elements/churros/files/2007697/IntacctChurrosResults.txt)
* [DE1527](https://rally1.rallydev.com/#/144349237612d/detail/defect/216996799524)
=> Intacct : Fix POST /sales-orders API

src/test/elements/quickbooks/changes.js
* Added test cases for QBO `GET /changes` API
(node:32500) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using oauth username: quickbooks@cloud-elements.com
info: Using api key: qyprdxLrqNbUbzaIRo3AsvwE9bPwHO
info: Running tests for element: quickbooks
info: Provisioned with instance id of 492
Basic tests
(node:32500) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
√ should GET /objects (384ms)
- docs
√ metadata (376ms)
error: Failed to delete /instances/492/transformations
error: Failed to retrieve or validate: /hubs/finance/changes
√ transformations (1780ms)
- should not allow provisioning with bad …
=> Added test cases for QBO changes resource

src/test/elements/infusionsoftcrm/assets/contacts.json, src/test/elements/infusionsoftcrm/contacts.js, src/test/elements/infusionsoftcrm/opportunities.js
Added testcases for following APIs 
- `GET /contacts`
- `GET /opportunities`
* [SOBA](https://github.com/cloud-elements/soba/pull/8681)
* [US11830](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877927488)
* [US11829](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877927188)
* [US11830](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877927488)
* [US11829](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877927188)
=> InfusionSoft CRM : Updated testcases for Contacts and Opportunities

src/core/oauth.js
* Added selenium flow supporting oauth2 provisioning for `SmartRecruiters`
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/195)
* [RALLY-#${US11922}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/219897348740)
* #[US11922](https://rally1.rallydev.com/#/144349237612d/detail/userstory/219897348740)
=> Added selenium flow supporting oauth2 provisioning for SmartRecruiters

src/test/platform/catalogProperties/catalogProperties.js
* 👆 
* [SOBA](https://github.com/cloud-elements/soba/pull/8761)
=> Wrote me some catalog-props tests

src/test/elements/eloqua/campaigns.js
* Modified the test case for `campaigns` object to support PATCH instead of PUT
Churros Test:
* [SOBA](https://github.com/cloud-elements/soba/pull/8740)
* [RALLY-#${DE1720}](https://rally1.rallydev.com/#/144349237612d/detail/defect/221306599508)
* #[DE1720](https://rally1.rallydev.com/#/144349237612d/detail/defect/221306599508)
=> Modified Churros test case for Campaigns object for Eloqua

src/test/elements/googlesuite/assets/groupsUpdate.json, src/test/elements/googlesuite/events.js, src/test/elements/googlesuite/groups.js
* All tests are passing now for GoogleSuit
* [SOBA](https://github.com/cloud-elements/soba/pull/8785)
* [RALLY-DE1820](https://rally1.rallydev.com/#/144349237612d/detail/defect/224708224872)
* [DE1820](https://rally1.rallydev.com/#/144349237612d/detail/defect/224708224872)
=> GoogleSuite : Fix churros tests

src/core/suite.js, src/core/tools.js, src/test/elements/marketo/bulk.js, src/test/elements/quickbooksonprem/assets/vendor-credit.json, test/core/suite.test.js, test/core/tools.test.js
* Does basic Bulk test for marketo
=> Enhanced Marketo Test to test bulk downloads

src/test/platform/formulas/assets/formulas/valid_script_step.json, src/test/platform/formulas/steps.js
* Test to see that steps properly disassociate from success/failure hooks
* Test to check we can still delete steps that aren't associated to a hook
* [SOBA](https://github.com/cloud-elements/soba/pull/8749)
=> Formula step disassociation

src/test/platform/formulas/executions.js
* [SOBA](https://github.com/cloud-elements/soba/pull/8867)
=> Improve stream step test to test form params

src/test/elements/xero/assets/overpayment-POST-allocations.json, src/test/elements/xero/assets/overpaymentInvoice-POST-allocations.json, src/test/elements/xero/assets/overpayments.json, src/test/elements/xero/overpayments.js
* Xero - Enhanced with /overpayments API Testcases
> `GET /overpayments`
> `GET /overpayments/{id}`
> `POST /overpayments/{id}/allocations`
[Soab](https://github.com/cloud-elements/soba/pull/8747)
[US12079](https://rally1.rallydev.com/#/144349237612d/detail/userstory/221608282536)
=> Xero - Enhance with /overpayments API - Churros

src/test/platform/accounts/accounts.js, src/test/platform/accounts/users.js, test/cli/churros.add.bats
New tests for:
* `PUT/PATCH {{api-v2}}/accounts/{accountId}/users/{userId}`
* `PUT/PATCH {{api-v2}}/accounts/{accountId}`
See comments
* [SOBA](https://github.com/cloud-elements/soba/pull/8873)
* [RALLY-#US12243](https://rally1.rallydev.com/#/144349238268d/detail/userstory/224207674644)
=> New tests for some account management APIs

src/cli/churros-test.js
* the `cliArgs.files` is an empty array so it always puts the `--file` flag even when it's empty. This causes problems with newer mocha versions
https://cl.ly/0D2I0H1O380q
https://cl.ly/2F1U2A0m1J2w
=> fixed problem with higher mocha versions

src/test/platform/transformations/transformations.js
* Adds try it out functionality test
https://cl.ly/2m0M2q2R0F2V
* [SOBA](https://github.com/cloud-elements/soba/pull/8878)
=> added try it out

src/test/elements/zuorav2/customers.js
* Modified test to take id of payment-method correctly.
* All churros are passing except one which is related to payments. Unable to generate proper value for that. It is not related to this change.
* [SOBA](https://github.com/cloud-elements/soba/pull/8928)
* [RALLY-DE2016](https://rally1.rallydev.com/#/144349237612d/detail/defect/231560589528)
* [DE2016](https://rally1.rallydev.com/#/144349237612d/detail/defect/231560589528)
=> Zuora V2: Changed id parameter for payment-method

src/test/elements/zuorav2/assets/transformations.json, src/test/elements/zuorav2/customers.js
* Modified transformations and customer.js file the Id field to be taken properly for the objects.
* All churros are passing except one which is related to payments. Unable to generate proper value for that.
* [SOBA](https://github.com/cloud-elements/soba/pull/8900)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/203)
* [RALLY-DE1928](https://rally1.rallydev.com/#/144349237612d/detail/defect/228416943296)
* [DE1928](https://rally1.rallydev.com/#/144349237612d/detail/defect/228416943296)
=> Zuora V2 : Modified test case and transformations for Id field

src/test/platform/transformations/transformations.js
=> removed JS spread

src/test/platform/elements/instances.js
* Tests ability to add and remove tags from instance
* [SOBA](https://github.com/cloud-elements/soba/pull/8866)
* Closes [US12635](https://rally1.rallydev.com/#/224141599444d/detail/userstory/228538522076?fdp=true)
=> Test for associating and removing tag from instance on PUT /instances

src/test/elements/adobe-esign/ping.js, src/test/elements/adobe-esign/users.js
* Fixed churros tests which were failing for :
* ping
* users
* [DE1411](https://rally1.rallydev.com/#/144349237612d/detail/defect/214177314864)
=> Adobe-Esign : Fix failing churros tests

src/test/elements/brighttalk/channels.js
* Modified churros test cases 
[SOBA](https://github.com/cloud-elements/soba/pull/8923)
[DE1979](https://rally1.rallydev.com/#/144349237612d/detail/defect/230367538904)
=> Fixed Brighttalk churros issue

src/test/platform/elementbuilder/faar2.js
* Fixes issues with faar2 test not creating and deleting assets correctly
=> Fixed faar2 tests

src/test/platform/transformations/transformations.js
* ☝️ 
https://cl.ly/1m1T2D190g2r
* [SOBA](https://github.com/cloud-elements/soba/pull/8948)
=> Tests allowing nulls and removed unmapped fields in vdrs

src/test/platform/elementbuilder/assets/ssl/ssl_element.json, src/test/platform/elementbuilder/ssl.js
* 💥 
* https://github.com/cloud-elements/soba/pull/8909
* https://github.com/cloud-elements/churros-sauce/pull/205
* [US12314](https://rally1.rallydev.com/#/144349238268d/detail/userstory/225474086760)
=> Tests for SSL Support

src/test/platform/transformations/commonResources.js
* Will reset the defaults and allow the tests to continue
https://cl.ly/1E3z0T2y1S1U
=> Using provisioner.delete

src/test/elements/googledrive/files.js
* 👨‍⚕️ 
* https://github.com/cloud-elements/soba/pull/9009
=> Google Drive - cloudElementsLink validation test

src/test/elements/marketo/activities.js, src/test/elements/marketo/assets/folders.json, src/test/elements/marketo/assets/programs.json, src/test/elements/marketo/programs.js
* Fixed failing tests for
* programs
* programsLeads
* folders
* activities
* [SOBA](https://github.com/cloud-elements/soba/pull/9019)
* [RALLY-DE2097](https://rally1.rallydev.com/#/144349237612d/detail/defect/235960898560)
* [RALLY-DE1434](https://rally1.rallydev.com/#/144349237612d/detail/defect/99047e1e-639b-40dc-a78e-b197e1d76136)
* [DE2097](https://rally1.rallydev.com/#/144349237612d/detail/defect/235960898560)
* [DE1434](https://rally1.rallydev.com/#/144349237612d/detail/defect/99047e1e-639b-40dc-a78e-b197e1d76136)
=> Marketo : Fixed failing tests

src/test/platform/vdrs/assets/snippets.json, src/test/platform/vdrs/vdrs.js
* Tests for snippet vdrs with system level tests
https://cl.ly/3G360e451u19
* [SOBA](https://github.com/cloud-elements/soba/pull/9028/files)
=> Added tests for JS snippets

src/test/elements/greatplains/assets/customers.json, src/test/elements/greatplains/assets/employee.json, src/test/elements/greatplains/assets/transformations.json, src/test/elements/greatplains/assets/vendors.json, src/test/elements/greatplains/classes.js, src/test/elements/greatplains/credit-terms.js, src/test/elements/greatplains/customers.js, src/test/elements/greatplains/employees.js, src/test/elements/greatplains/ledger-accounts.js, src/test/elements/greatplains/products.js, src/test/elements/greatplains/receivables-invoices.js, src/test/elements/greatplains/tax-rates.js, src/test/elements/greatplains/vendors.js
* Implemented Churros test cases for "Great Plains"
[US8371](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198207470640)
=> added churros test cases for greatplains

src/test/elements/bigcommerce/store-metadata.js
* Added test for `GET /store-metadata`
* Using basic authentication:
PS C:\Git\churros> churros test elements/bigcommerce --file store-metadata
(node:20460) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using oauth username: integration
info: Running tests for element: bigcommerce
info: Provisioned with instance id of 72
(node:20460) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (316ms)
- docs
√ metadata (348ms)
error: Failed to delete /instances/72/transformations
√ transformations (1251ms)
store-metadata
√ should …
=> BigCommerce: Churros test added for GET /store-metadata

src/test/elements/magentov20/assets/ordersInvoice.json, src/test/elements/magentov20/orders.js
* Added POST /orders/{id}/invoice churros tests
* Report-  [churros magento.txt](https://github.com/cloud-elements/soba/files/2219322/churros.magento.txt)
Churros test are failing in staging as well. Raised a  defect for same. [DE2128](https://rally1.rallydev.com/#/144349237612d/detail/defect/237101292356?fdp=true)
* [SOBA](https://github.com/cloud-elements/soba/pull/9060)
* [RALLY-#US13244](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/239641780444)
* [US13244](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/239641780444)
=> Magentov2: Added POST /orders/{id}/invoice churros tests

src/test/elements/zuorav2/customers.js, src/test/elements/zuorav2/invoices.js, src/test/elements/zuorav2/payments.js, src/test/elements/zuorav2/subscriptions.js
* Fixed churros for `customers`, `invoices`, `payments` and `subscriptions`
* [RALLY-#${DE2158}](https://rally1.rallydev.com/#/144349237612d/detail/defect/238716788292)
* [DE2158](https://rally1.rallydev.com/#/144349237612d/detail/defect/238716788292)
=> Zuorav2 : Fixed churros tests for  customers, invoices, payments and subscriptions

src/test/elements/amazonmarketplace/assets/inventories.json, src/test/elements/amazonmarketplace/assets/transformations.json, src/test/elements/amazonmarketplace/inventories.js, src/test/elements/assets/object.definitions.json
* Added Test suite for new resource `/inventories`
* [SOBA](https://github.com/cloud-elements/soba/pull/9046)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/212)
* [Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/233284130008)
* [US13000](https://rally1.rallydev.com/#/144349237612d/detail/userstory/233284130008)
=> AmazonMarketplace: Added Testsuite for /inventories resource

src/test/elements/jira/fields.js, src/test/elements/jira/incidentTypes.js, src/test/elements/jira/priorities.js, src/test/elements/jira/statuses.js
* Pagination test added for Fields, Statuses, Incident-types and Priorities.
* [SOBA](https://github.com/cloud-elements/soba/pull/9107)
* [RALLY-DE2231](https://rally1.rallydev.com/#/144349237612ud/detail/defect/240887902724)
* [DE2231](https://rally1.rallydev.com/#/144349237612ud/detail/defect/240887902724)
=> Jira : Added pagination tests for Fields, Status, Incident-types and Priorities

src/test/platform/vdrs/assets/signup.json, src/test/platform/vdrs/upgrades.js
* Tests for upgrade and rollback APIs for an organization VDR Version
* [SOBA](https://github.com/cloud-elements/soba/pull/9039)
=> Tests for upgrade and rollback APIs for an organization VDR Version

src/test/elements/volusion/products.js
* Now PATCH `/products` API testcases should work as expected
* Note: Basic tests are failing.
* [RALLY-#${DE2268}](https://rally1.rallydev.com/#/144349237612d/detail/defect/242883776532)
* [DE2268](https://rally1.rallydev.com/#/144349237612d/detail/defect/242883776532)
=> Volusion: Fixed failing testcases issue

src/test/elements/bullhorn/job-submissions-history.js
* Added test cases for `job-submissions-history` object
* [SOBA](https://github.com/cloud-elements/soba/pull/9140)
* [RALLY-#${US13355}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/243067786460)
* [US13355](https://rally1.rallydev.com/#/144349237612d/detail/userstory/243067786460)
=> Bullhorn : Added test cases for job-submissions-history

src/test/platform/formulas/assets/events/single-event-closeio.json, src/test/platform/formulas/assets/events/triple-event-closeio.json, src/test/platform/formulas/executions.js
* [SOBA](https://github.com/cloud-elements/soba/pull/9163)
=> Additional tests for manually triggering formulas and retries

src/test/platform/formulas/executions.js, src/test/platform/vdrs/upgrades.js
=> Fixing some FIE tests

src/test/elements/stripe/assets/models_customers_payment_method_patch_id.json, src/test/elements/stripe/payment-methods.js
* Stripe: Updated churros for PATCH /customers/payment-methods
* Updated payloads for PATCH /customers/payment-methods
* [SOBA](https://github.com/cloud-elements/soba/pull/9158)
* [DE2169](https://rally1.rallydev.com/#/144349237612d/detail/defect/239133629124)
=> Stripe: Updated churros for PATCH /payment-methods

src/test/platform/transformations/assets/definition-with-array.json, src/test/platform/transformations/assets/transformation-array.json, src/test/platform/transformations/transformations.js
* Array mapping tests
* [SOBA](https://github.com/cloud-elements/soba/pull/9136)
=> Array mapping tests

src/test/platform/vdrs/assets/transformation.system.json, src/test/platform/vdrs/transformations.js
* added tests for organization level cloning
* [SOBA](https://github.com/cloud-elements/soba/pull/9234)
=> added tests for organization level cloning

src/test/platform/elements/instances.js
* https://github.com/cloud-elements/soba/pull/9240
* [SLYT-403](https://cloudelements.atlassian.net/browse/SLYT-403)
* Closes [#SLYT-403](https://cloudelements.atlassian.net/browse/SLYT-403)
=> Added integration tests to ensure the "createdDate" is returned in the response payload for the GET /elements/{keyOrId}/instances APIs

src/test/elements/concur/ibm-assets/concur_createExpense.json, src/test/elements/concur/ibm-assets/concur_createItem.json, src/test/elements/concur/ibm-assets/concur_updateExpenseById.json, src/test/elements/concur/ibm-assets/concur_updateItemById.json
* Concur payloads for `/expenses` and `/items` resources
* [SOBA](https://github.com/cloud-elements/soba/pull/9214)
* [Jira](https://cloudelements.atlassian.net/browse/IBM-10)
* [Jira](https://cloudelements.atlassian.net/browse/IBM-10)
=> Concur Payloads

src/test/elements/jira/agents.js, src/test/elements/jira/assets/agents.json, src/test/elements/jira/assets/transformations.json
* Added POST and DELETE api for `agents` resource.
* [SOBA](https://github.com/cloud-elements/soba/pull/9215)
* [Churros-ibm](https://github.com/cloud-elements/churros/pull/1729)
* [Jira](https://cloudelements.atlassian.net/browse/IBM-1)
=> Jira: Added tests for new apis of agents

src/test/elements/sqlserver/contacts.js, src/test/platform/vdrs/assets/snippets.json
* Adding the required snippetType field
https://cl.ly/8d8bce630254
* [SOBA](https://github.com/cloud-elements/soba/pull/9247)
* [RVCL-50](https://cloudelements.atlassian.net/secure/RapidBoard.jspa?rapidView=12&modal=detail&selectedIssue=RVCL-50)
=> Add snippetType

src/test/elements/sfdcservicecloud/assets/newResource.json, src/test/elements/sfdcservicecloud/extended-resource.js
* Added test to check adding an extended resource
* [SOBA](https://github.com/cloud-elements/soba/pull/9204)
=> Salesforce Service Cloud : Added tests to check extendable resources

src/test/platform/docs/docs.js
* Tests for instance docs with baseUrl.
See comments section
* [SOBA](https://github.com/cloud-elements/soba/pull/9318)
* [RALLY-#DE2464](https://rally1.rallydev.com/#/144349238268d/detail/defect/253018333492)
=> Instance docs with baseUrl

src/test/elements/sfdc/report-types.js
* Added `report-types` test
* <img width="785" alt="screen shot 2018-09-12 at 3 25 17 pm" src="https://user-images.githubusercontent.com/35976783/45451244-26655d80-b6a0-11e8-9d6c-74969cd2f92c.png">
* <img width="757" alt="screen shot 2018-09-12 at 3 25 31 pm" src="https://user-images.githubusercontent.com/35976783/45451254-2e250200-b6a0-11e8-8486-e7f5b85f34e2.png">
[SOBA](https://github.com/cloud-elements/soba/pull/9317)
* [US13658](https://rally1.rallydev.com/#/144349237612d/detail/userstory/251318962324)
=> Added new test for SFDC

src/test/platform/transformations/assets/defaultValue-transformation.json, src/test/platform/transformations/assets/object-definitions.json, src/test/platform/transformations/commonResources.js, src/test/platform/transformations/transformations.js
* Tests for default value type
* Fixes all `platform/transformations`
https://cl.ly/64f9e873aba3
* [SOBA](https://github.com/cloud-elements/soba/pull/9274)
* [RVCL-76](https://cloudelements.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=RVCL&modal=detail&selectedIssue=RVCL-76)
=> adding default value type test

src/test/platform/elements/assets/element.configurations.schema.json
* Added new field returned in /elements/{keyOrId}/configuration to schema
[Screenshot](https://cl.ly/0q163r1g1I2S)
* [SOBA](https://github.com/cloud-elements/soba/pull/8583)
* [RALLY-#US11242](https://rally1.rallydev.com/#/144349238268d/detail/userstory/214414169832)
=> Test for return authentication with configuration
