cloud-elements/churros

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

* Moved `CONTRIBUTING.md` to a new `/.github` directory.
* Added templates for pull requests and issues to `/.github` directory

setting up github templates

---

src/core/suite.js
src/test/elements/closeio/contacts.js
src/test/platform/formulas/formulas.js
src/test/platform/notifications/notifications.js
src/test/platform/notifications/subscriptions.js
test/core/suite.test.js

* Added test for new `GET /formulas/:id/export` to validate that exporting a formula works.
* Changed the way `test.shouldReturn404...` methods work, where if an `id` is *not* passed in as an arg to the method, then it does not try to append `-1`.  This makes it easier to test `404`s for sub-resources, such as: `GET /formulas/:id/exports`

Adding Test for GET /formulas/:id/export

---

README.md

* Fixed reference to `CONTRIBUTING.md` in `README.md` since it's now nested under the `.github` directory.

fix contributing reference in readme

---

CHANGELOG.md
src/cli/churros-test.js

* `churros test` actually kicks off another `mocha` process and was swallowing the exit code from that shell command.  This code is now propagated back to the CLI properly.

propogate churros test shell code

---

src/cli/churros-add.js

* if the resource does not exist in the global `object.definitions.json`, create the key and add the `id` field as a string
* Closes #122

add id and object to object.definitions.json if needed

---

src/cli/assets/prompter.js
src/cli/churros-add.js
src/cli/churros-test.js

* When running `churros test`, the optional `--password` option is now just a flag.  When `--password` is passed, the user will then be prompted for their password on the command line.  Previously, you had to do `--password <password>`, forcing you to type your password in plain text on the command line.  No good at all.
* Closes #121

changed the --password option to churros test to be a flag

---

src/core/suite.js
src/test/platform/formulas/executions.js
src/test/platform/formulas/formulas.scripts.js
test/core/cloud.test.js
test/core/suite.test.js

* Added tests to test `POST /formulas` and `POST /formulas/:id/steps` APIs to ensure that the proper validation is done depending on what `scriptEngine` you are using.
* `v1` scripts *must* have a `return` statement in them
* `v2` scripts *must* have a `done()` callback in them

formulas tests for validating script steps

---

package.json

* tests rely on `sleep` npm package, however that was not in the `package.json`.

formula tests failing in circle CI

---

CHANGELOG.md
src/core/cloud.js
test/core/cloud.test.js
test/core/suite.test.js

* adds support for passing an alternate payload for the update portion of a CRUDS cycle via the churros segment of options.
```
let updatePayloadExample = {
name: 'updated!'
};
let options = {
qs: {
where: 'foo=bar'
},
churros: {
updatePayload: updatePayloadExample
}
};
test.withOptions(options).should.supportCruds();
```
* Closes #131

Custom update

---

src/core/cloud.js
src/core/suite.js
src/core/tools.js
src/test/platform/formulas/assets/big-formula-instance.json
src/test/platform/formulas/assets/common.js
src/test/platform/formulas/assets/formula.schema.json
src/test/platform/formulas/assets/loop-formula-instance.json
src/test/platform/formulas/assets/loop-formula.json
src/test/platform/formulas/executions.js
src/test/platform/formulas/formula.instances.js
test/core/suite.test.js
test/core/tools.test.js

* added new formula tests around the new `/formulas/:id/instances/:id/active` APIs
* added a formula execution test to kick off a long-running formula, deactivate it, and then ensure that it was terminated properly and has the right error message in its step execution values.
```
formulas
✓ should terminate an execution if the deactivate API is called during execution (21632ms)
1 passing (42s)
```

formula activation APIs

---

package.json

* `nock` dependency tying to a version to make 'er work.

fixing nock dependency

---

src/core/oauth.js
src/test/platform/formulas/formulas.scripts.js

* no longer validate that `v1` scripts need a `return` statement - removing test

 removing invalid test due to formula script v1 "return" validation changes

---

src/core/suite.js
test/core/suite.test.js

* `test.withOptions` was not passing on the right `api`, `validationCb` or `payload` in `suite.js`
new unit test to validate:
```
✓ should allow overriding the api and the options with new values
```
* Closes #178

withOptions was not passing on the right api, validationCb or payload

---

src/test/elements/woocommerce/assets/comments.json
src/test/elements/woocommerce/ordersComments.js

* Added /orders/{id}/comments
* Added /product/{id}/orders
```
customers
✓ should allow CRUDS for /hubs/ecommerce/customers (1949ms)
✓ should allow paginating with page and pageSize /hubs/ecommerce/customers (462ms)
discounts
✓ should allow CRUDS for /hubs/ecommerce/discounts (1678ms)
✓ should allow paginating with page and pageSize /hubs/ecommerce/discounts (252ms)
orders
✓ should allow CRUDS for /hubs/ecommerce/orders (2817ms)
✓ should allow paginating with page and pageSize /hubs/ecommerce/orders (405ms)
ordersComments
✓ should allow CRUDS for /hubs/ecommerce/ordersComments (4833ms)
products
✓ should allow CRUDS for /hubs/ecommerce/products (3301ms)
✓ should allow paginating with page and pageSize /hubs/ecommerce/products (690ms)
reports
✓ should allow retrieval of reports and report …
```

CE-4219 WooCommerce newly added API tests

---

src/core/provisioner.js

* allow for 100% custom provisioning for an element by putting a `provisioning.js` file in the test directory for that element

allow for 100% custom provisioning code

---

src/cli/churros-test.js
src/core/provisioner.js
src/test/elements/lifecycle.js
src/test/lifecycle.js
test/core/provisioner.test.js

* implement the `--externalAuth` flag for oauth2 elements to run through the full oauth2 flow prior to provisioning
* add tests to cover new functionality
* `tokenUrl` prop must be added to `sauce.json` for support
```
churros test elements/sfdc --externalAuth
churros test elements/box --externalAuth
```

External Auth Flag

---

src/core/provisioner.js
src/test/elements/lifecycle.js
src/test/platform/formulas/assets/common.js
src/test/platform/formulas/executions.js
test/core/provisioner.test.js

* the default headers need to be set in the `provisioner` or else tests using the `provisioner` have to set them, which kind of sucks ... 
* also, some minor updates to `executions` tests to use `cloud` instead of `chakram` so we get better logging as to what API calls are being made

changing the way that default request headers get set in chakram

---

src/test/elements/dropboxbusiness/assets/members.json
src/test/elements/dropboxbusiness/members.js

* Added tests for `/members-information` as per the latest updations.
* Updated old tests so that they do not fail in case license limit of `members` is reached and we try to add more members.

Updated old test scripts for the new Dropbox Business enhancements

---

CHANGELOG.md
package.json
src/cli/churros-clean.js
src/cli/churros.js
src/core/cleaner.js
src/core/cloud.js
src/core/provisioner.js
src/test/clean.js
src/test/platform/formulas/assets/common.js
src/test/platform/formulas/assets/formulas/filter-returns-false.json
src/test/platform/formulas/assets/formulas/manual-trigger.json
src/test/platform/formulas/assets/formulas/simple-successful-formula.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/error-sub-formulas.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/filter-sub-formulas.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/manual-sub-formulas.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/simple-sub-formulas.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/sub-formulas-no-steps-after.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/sub-formulas.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/two-sub-formulas-no-steps-after.json
src/test/platform/formulas/assets/formulas/sub-formula-executions/two-sub-formulas.json
src/test/platform/formulas/config.js
src/test/platform/formulas/executions.js
src/test/platform/formulas/load.js
src/test/platform/formulas/steps.js
src/test/platform/formulas/sub-formula-executions.js
test/cli/churros.clean.bats
test/core/cleaner.test.js

* First cut at some sub-formula tests to demonstrate the formula step type of `formula` (i.e. formulas calling formulas)
```  
formula executions: sub formulas
✓ should support a formula that contains a sub-formula (4247ms)
✓ should support a formula having multiple sub-formulas (22496ms)
✓ should support a formula multiple sub-formulas and no after steps (10457ms)
✓ should support a formula with a sub-formula that has a manual trigger type (7420ms)
✓ should have onSuccess or onFailure to represent the entire sub-formulas execution status (4346ms)
✓ should propagate errors from sub-formulas properly (4742ms)
```

Sub formula tests

---

src/core/provisioner.js
src/test/platform/elements/instances.js
test/core/provisioner.test.js

* Test out `PUT` and `PATCH` of `/instances/{id}` with `providerData` in order to re-authenticate.
```
churros test platform/elements --file instances --test 'update with reprovision'          ✓  4232  11:15:58
elements/instances
✓ should support update with reprovision by key (61301ms)
1 passing (1m)
```

Patch instances with reauthentication

---

src/core/tools.js
src/test/platform/formulas/assets/common.js
test/core/tools.test.js

* The `wait.for` function would never actually quit executing the given function.  Now it does.

Fix wait for function to not scroll errors

---

src/test/platform/elements/assets/common.js
src/test/platform/elements/resourceParameters.js
src/test/platform/elements/resources.js

* Saving sample data for resource and parameter
* API tests for for /elements/{id}/resources/{resources}
```
churros test platform/elements  --test 'resources'
elements/resources/hooks
✓ should support CRUD by key (326ms)
✓ should support CRUD by ID (306ms)
elements/resources/models
✓ should support CRUD by key (322ms)
✓ should support CRUD by ID (388ms)
✓ request swagger should support CRUD by key (337ms)
✓ request swagger should support CRUD by ID (311ms)
elements/resources/parameters
✓ should support CRUD by key (348ms)
✓ should support CRUD by ID (323ms)
✓ should support CRUD by key with sample data (329ms)
✓ should support CRUD by ID with sample data (320ms)
elements/resources
✓ should support CRUD by key (412ms)
✓ should support CRUD by ID (426ms)
✓ should support CRUD by key with …
```

Tests for saving sample data for resource and parameter level

---

src/test/platform/general/headers.js

* New tests to check that the `X-Frame-Options` header exists for JSP endpoints, but not for others.

add tests for the CWE 693 pen test fix

---

src/test/platform/elements/assets/common.js
src/test/platform/elements/resources.js

* Tests for adding operationId to resources
```
elements/resources/hooks
✓ should support CRUD by key (311ms)
✓ should support CRUD by ID (328ms)
elements/resources/models
✓ should support CRUD by key (317ms)
✓ should support CRUD by ID (319ms)
✓ request swagger should support CRUD by key (315ms)
✓ request swagger should support CRUD by ID (320ms)
elements/resources/parameters
✓ should support CRUD by key (327ms)
✓ should support CRUD by ID (312ms)
✓ should support CRUD by key with sample data (319ms)
✓ should support CRUD by ID with sample data (309ms)
elements/resources
✓ should support CRUD by key (398ms)
✓ should support CRUD by ID (412ms)
✓ should support CRUD by key with sample data and other optional fields (405ms)
✓ should support CRUD by ID with sample data and other optional …
```

Tests for adding operationId to resources

---

src/test/elements/connectwisehd/assets/comments.json
src/test/elements/connectwisehd/assets/contacts.json
src/test/elements/connectwisehd/assets/incidents.json
src/test/elements/connectwisehd/assets/organizations.json
src/test/elements/connectwisehd/assets/transformations.json
src/test/elements/connectwisehd/contacts.js
src/test/elements/connectwisehd/incidents.js
src/test/elements/connectwisehd/organizations.js

* Connectwise Helpdesk tests for `contacts`, `incidents`, `incident/comments`, `organizations`
```
contacts
✓ should allow CRUDS for /hubs/helpdesk/contacts (8548ms)
✓ should allow GET for /hubs/helpdesk/contacts (1059ms)
✓ should allow paginating with page and pageSize /hubs/helpdesk/contacts (1601ms)
incidents
✓ should allow CRUDS for /hubs/helpdesk/incidents (9010ms)
✓ should allow GET for /hubs/helpdesk/incidents (927ms)
✓ should allow paginating with page and pageSize /hubs/helpdesk/incidents (781ms)
✓ should allow CRU for /hubs/helpdesk/incidents/{id}/comments (5970ms)
organizations
✓ should allow CRUDS for /hubs/helpdesk/organizations (6648ms)
✓ should allow GET for /hubs/helpdesk/organizations (725ms)
✓ should allow paginating with page and pageSize /hubs/helpdesk/organizations …
```

Connectwise Helpdesk tests

---

src/test/elements/connectwisecrm/assets/contacts.json
src/test/elements/connectwisecrm/assets/organizations.json
src/test/elements/connectwisecrm/assets/transformations.json
src/test/elements/connectwisecrm/contacts.js
src/test/elements/connectwisecrm/organizations.js

* Connectwise CRM Tests for contacts and organizations
```
churros test elements/connectwisecrm
contacts
✓ should allow CRUDS for /hubs/crm/contacts (9637ms)
✓ should allow GET for /hubs/crm/contacts (1227ms)
✓ should allow paginating with page and pageSize /hubs/crm/contacts (1056ms)
organizations
✓ should allow CRUDS for /hubs/crm/organizations (7419ms)
✓ should allow GET for /hubs/crm/organizations (1045ms)
✓ should allow paginating with page and pageSize /hubs/crm/organizations (976ms)
6 passing (27s)
```

Connectwise CRM Tests

---

README.md
src/cli/churros-init.js

* `churros init` order of precedence is now CLI options, environment variables, and finally prompting.
* `export CHURROS_USER="rocky@cloud-elements.com"`
* `export CHURROS_PASSWORD="password"`
* `export CHURROS_URL="api.cloud-elements.com"`
* `export CHURROS_TEMPLATE="https://token@github.com/cloud-elements/churros-sauce/sauce.json"`

churros init should support environment variables

---

src/core/oauth.js
src/test/platform/transformations/scripts.js

* Validate transformations do not have `console` key

Validate transformations do not have console key

---

src/cli/churros-init.js

* Upon `init` and using a template, this fixes an issue in which using local filesystem paths that include `https` would be incorrectly matched as github repos

Fix init template source detection bug

---

src/test/elements/lifecycle.js

* Rather than flooding the endpoint with requests, process the object definition and transformation creations one at a time. Otherwise, running this locally tends to lock up Soba because there aren't enough threads or DB connections to handle it.
* Bonus: much more functional style 🎉

Create the object definitions and transformation one at a time

---

src/core/cloud.js
src/core/suite.js
test/core/suite.test.js

* There is now a custom churros option available to skip a specific churros test when using the `test` module inside of a `suite.for...` function
* Added better API docs for the available `options` argument that can be passed into `test.withOptions`
```
test
.withName('should allow skipping a specific test by passing in the skip option')
.withOptions({ skip: true })
.withApi(`${test.api}/api/that/is/not/mocked`)
.should.return200OnGet();
```
* Closes #346

Added support to skip a specific churros test when using the `test` module

---

src/test/elements/desk/contacts.js
src/test/elements/desk/organizations.js

* Skipping the tests that have no `DELETE` API available.

Skip tests that have no cleanup available.

---

src/test/platform/formulas/formulas.js

* Updated the cron string for the scheduled formula test, since the minimum allowable is now 1 minute.

Updated cron formula test to use a 30 second interval

---

src/test/elements/jira/agents.js
src/test/elements/jira/fields.js
src/test/elements/jira/incidentTypes.js
src/test/elements/jira/priorities.js
src/test/elements/jira/statuses.js

* I noticed (because I had the same problem in some tests I wrote), that these tests lack a return of the promise, which causes the framework to assume that the code is synchronous and that it can immediately return which results in none of the assertions being run and making it look like it's been successful when it may not have been.

Add missing returns

---

src/test/elements/pipedrive/filters.js
src/test/elements/pipedrive/opportunities.js

* Added test to check that deleting filters works for Pipedrive
https://github.com/cloud-elements/soba/pull/4392
* When a GET is performed with a `where` parameter, a filter is created.  This deletes that filter.
* Closes #541

Pipedrive Delete Filters

---

src/test/platform/formulas/assets/formulas/script-with-on-failure-successful-formula.json
src/test/platform/formulas/executions.js

* Add a new test to validate that console.log() statements are still returned when a script step fails.

Add a test for console.log() on a failed JS step

---

src/test/platform/publishing/publishing.js

* AWS Auto publishing to Lambda and API Gateway
```
publishing
✓ should allow AWS lambda autogenerate and download for the element  (427ms)
✓ should allow AWS database lambda autogenerate and download for the element  (318ms)
✓ should allow AWS lambda autogenerate and deploy to AWS  (78866ms)
```

AWS Auto publishing tests

---

src/test/elements/jira/incidents.js

* Added SR /incidents/:id/history tests
```
info: Running tests for element: jira
incidents
✓ should allow CRUDS for /incidents/:id/comments (5395ms)
✓ should allow CRDS for /incidents/:id/attachments and RD for /attachments and SR for /incidents/:id/history (9323ms)
✓ should allow CRUDS for /hubs/helpdesk/incidents (7397ms)
✓ should allow paginating with page and pageSize /hubs/helpdesk/incidents (438ms)
✓ should support searching /hubs/helpdesk/incidents by id (2219ms)

Updated incidents tests in Jira

---

src/test/elements/autotaskcrm/bulk.js
src/test/elements/autotaskhelpdesk/bulk.js

* Add bulk tests to autotaskcrm and autotaskhelpdesk
* Wasn't able to get any of the autotaskcrm churros tests to work, which are set to skip:true in churros-sauce

Add tests in support of adding bulk to autotask

---

src/test/platform/signup/assets/userpayload.json
src/test/platform/signup/signup-partners.js

* Tests for POST /signup-partners API
Test should return 401 for unauthorized users

Signup Partners Test

---

src/test/platform/publishing/publishing.js

* Skipping the auto publish as the maven is not installed on app servers

AWS Autopublish skip

---

src/test/platform/elements/instances.js

* A  401 should be thrown when API calls are made against a deleted element instance.
* Closes #617

Added test to ensure that a 401 is thrown for api calls against a deleted instance

---

src/test/platform/elements/assets/element.metadata.expanedschema.json
src/test/platform/elements/metadata.js

* New schema validation for additional fields
* Added missing get all elements metadata
```
elements/metadata
✓ should get all elements metadata (172ms)
✓ should return element metadata (227ms)
✓ should return element metadata for exapnd (248ms)
✓ should return 404 for invalid element ID (65ms)
✓ should return polling event metadata for polling element (175ms)
✓ should return webhook event metadata for webhook element (271ms)
```

Element metadata changes for Mendeleev

---

src/test/elements/desk/contacts.js
src/test/elements/desk/incidents.js
src/test/elements/sfdcservicecloud/contacts.js

* Adds querying tests to `contacts` and `incidents`
* Moving `sfdcservicecloud` paging test to the suite

Adding postive/negative tests for Desk.com querying

---

src/test/elements/lifecycle.js

* When running elements tests, only the necessary object definitions are created, as opposed to *every* object definition in the `object.definitions.json` file.
* Closes #507

Don't create unnecessary object definitions for element tests

---

src/test/elements/freshdeskv2/contacts.js
src/test/elements/sfdc/contacts.js

* Added a test case to ensure to that `400` is returned when a malformed bulk query request is made
* The malformed queries used are `POST /crm/bulk/query?select * contacts` (`from` is missing) and `POST /helpdesk/bulk/query?select * contacts` for the `sfdc` and `freshdeskv2` elements respectively
* Closes #651

Added bulk malformed query test cases

---

src/test/elements/onedrivebusiness/files.js

* Added `GET /files/links?path=<path>` and `GET /files/{id}/links` tests for the OneDrive for Business element
* Closes #636

Added GET /files/links?path=<path> and GET /files/{id}/links tests for the OneDrive for Business element

---

src/test/elements/freshservice/assets/transformations.json
src/test/elements/freshservice/incidents.js

* Removing transformations for incidents object. "id" was being mapped to 'display-id' field from vendor body. Vendor body already contains 'id' field. This transformation causes display-id to be removed from the response. We are not able to use the display-id field for further API test cases. If we try to use 'id' assuming it is transformed, churros uses the 'id' field from the vendor response. We expect display-id value here.
* Closes #4439

Fixing /incidents Churros

---

src/test/elements/facebookleadads/pages.js
src/test/elements/facebookleadads/ping.js

* Updated the churros tests for Facebook Lead Ads
- POST /pages/{pageId}/subscribed-apps 
- GET /pages/{pageId}/subscribed-apps resources
- GET /ping

Updated churros tests for Facebook Lead Ads (#4144)

---

src/test/platform/general/headers.js

* Added a test to check for the presence of `Access-Control-Expose-Headers`
* https://github.com/cloud-elements/soba/pull/5000

Added a CORS header test

---

src/test/elements/docusign/envelopes.js

* Added churros tests for GET /envelopes/{id}/custom_fields API
- GET /envelopes/{id}/custom_fields

CE-4146: Added churros tests for GET /envelopes/{id}/custom_fields API

---

src/test/elements/autotaskcrm/metadata.js
src/test/elements/sfdc/metadata.js

* Added a test to ensure a `picklist` is returned for the `Salutation` field for the Salesforce.com `Contact` object metadata
* Added a test to ensure a `picklist` is returned for the `accountType` field for the Autotask CRM `Account` object metadata
* Closes #690

Added metadata tests for SFDC and Autotask CRM

---

src/test/elements/shopify/customers.js
src/test/elements/shopify/orders.js
src/test/elements/shopify/products.js

* added tests for using an `orderBy` param in Shopify resources `customers`, `orders` and `products`
* Soba PR: https://github.com/cloud-elements/soba/pull/5058

Shopify tests for using the `orderBy` param

---

src/test/platform/elements/instances.js
src/test/platform/formulas/instances.js

* New test for retaining `@` symbols after sanitizing element/formula instance names.

Unescape symbols after sanitization

---

src/test/elements/hubspotcrm/assets/objects.json
src/test/elements/hubspotcrm/contacts.js

* The `email` property for HubSpot CRM transformations was not being fetched.
* @atulbarve fixed this issue, and this is an integration test for the same.
* Closes #707

Test for HubSpot CRM contact xforms

---

src/test/elements/shopify/customers.js

* super minor change to supported params for `/customers`

Shopify /customers `orderBy` update

---

package.json
src/test/platform/transformations/commonResources.js

* Added a lil' baby test for the new `/common-resources` resource that Console 2.0 is leveraging to simplify common resources in the UI.
* Added dependency on `ramda` npm module
> NOTE: Will eventually spruce up these tests as/if we expose these as consumable to customers.  Currently they're being tried out in the UI and will probably continue to change so do not want to document or add too many tests around them meow 🐱

:baby_symbol: Added test for GET /common-resources

---

src/test/platform/docs/docs.js

* Swagger docs validation for `x-api-key` validation when provider aws

Swagger docs validation for provider aws

---

src/cli/churros-test.js
src/test/elements/lifecycle.js

* can use a instance that is already available
* Use `-i ${instanceId}` or `--instance ${instanceId}`
`churros test elements/intacct -I 1243`

Added ability to run churros on previously created instance

---

src/test/platform/bulk/bulk.js

* Tests the ability to cancel a bulk job using the PUT /bulk/{id}/cancel API
* Closes #758

Bulk Job Cancellation Test

---

src/test/elements/pipedrive/emails.js

* Added the Churros Test for RUD operations of mailThread API.
* Added the skip in the suite, as emailThread API is deprecated and now vendor is not supported and for mailThread API we are not doing the POST mailThread Hence we need to skip RUD operation of mailThread. 
* Closes #$4133

CE-4133 Added Churros for mailThread API.

---

src/core/suite.js
src/core/tools.js
src/test/elements/desk/organizations.js
src/test/elements/mailchimpv3/assets/lists.json
src/test/elements/mailchimpv3/campaigns.js
src/test/elements/mailchimpv3/lists.js
src/test/elements/salesforcemarketingcloud/campaigns.js
src/test/elements/wufoo/forms.js
src/test/elements/wufoo/reports.js
src/test/elements/wufoo/users.js
test/core/suite.test.js
test/core/tools.test.js

* Can now only validate the unique identifier
* Pass the identifier as a string to the `supportPagination` test
test.should.supportPagination('id');
* Closes #764

Adds ability to only check unique identifiers for pagination

---

src/test/platform/formulas/assets/formulas/formula-with-invalid-status-code-properties.json
src/test/platform/formulas/assets/formulas/formula-with-valid-status-code-properties.json
src/test/platform/formulas/steps.js

* Added a tests for the newly added support for range in `retryStatusCode` field of the `request` type steps
* Closes #5630

Added churros for retryStatusCode validation on formula steps

---

src/cli/churros-init.js

* Fixes `churros init --template <github>` with utf8 sauce.
After this fix:
```
$ churros init --template https://${token}@github.com/cloud-elements/churros-sauce/sauce.json
? Default user to run tests: charlie@cloud-elements.com
? User's password: *********************
? Cloud Elements URL snapshot.cloud-elements.com
Making sauce directory
Writing sauce template from repo
Writing sauce file
Churros initialization successful!
```
* Closes #859

Fix for #859: use utf8 sauce when initing from github

---

src/test/elements/hubspotcrm/assets/leads.json

* For `leads` resource, enclosed the churros payload in `properties` key as per updated model.

IBM: Updated churros payload for HubspotCRM

---

src/test/elements/stripe/assets/transfers.json

* Removed extra field "statement_descriptor" from `POST /transfers` payload for Churros.
* Closes #910

Stripe : Removed extra field from POST /transfers payload

---

src/test/elements/sfdcdocuments/search.js

Added test cases for `GET /search` for the following scenarios:
* `startDate` and `endDate` filters
* Pagination
* `path` parameter
* Closes #5883 #3834

Added some test cases for Salesforce Files `GET /search` API

---

src/test/elements/sfdclibraries/folders.js

* Added a test for the new `orderBy` parameter for the `GET /folders/contents` and `GET /folders/{id}/contents` APIs for SFDC Libraries.
* Closes #928

Added a sort test for the GET /folders/content API for SFDC Libraries.

---

src/test/platform/docs/docs.js

* Added validation to check the AWS hostname in docs when provider is AWS

Added validation to check the AWS hostname in docs when provider is AWS

---

src/test/elements/sfdc/accounts.js
src/test/elements/sfdc/contacts.js

* Added tests to search SFDC accounts and contacts when a field value has one or more single quotes in it
* Closes #937

Added tests to search SFDC accounts and contacts when a field value has one or more single quotes in it

---

src/test/platform/formulas/assets/formulas/faar.json
src/test/platform/formulas/errors.js
src/test/platform/formulas/faar.js

* Tests out the new FaaR functionality, by exposing manual-triggered formula instances as an API, and executing that API.
```jjwyse@sneffels@[skeletor]$ clear;churros test platform/formulas --file faar 
FaaRs
✓ should allow exposing a formula instance as a synchronous POST API resource (11721ms)
✓ should not allow exposing two formula instances as the same API (818ms)
✓ should not allow exposing a formula instance that does not have a manual trigger (351ms)
✓ should throw an error if the formula instance settings API does not start with an HTTP verb
```

Added new tests for the new formulas as a resource functionality

---

src/test/elements/dropbox/folders.js
src/test/elements/dropboxbusiness/folders.js
src/test/elements/dropboxbusinessv2/folders.js
src/test/elements/dropboxv2/folders.js

* Added testing for pre-defined response of `GET /folders/metadata where path = /` & `GET /folders/%2F/metadata` where `%2F` is the Dropbox ID of the root folder

Dropbox GET /folders/metadata for root

---

src/test/platform/formulas/assets/formulas/formula-waitForIt-selfContained.json
src/test/platform/formulas/executions.js

- Added churros for new PATCH method to cancel a formula
- tests canceling a formula, canceling a formula that's completed (406), and canceling a formula that doesn't exist (404)
* Closes [#4478](https://github.com/cloud-elements/soba/issues/4478)

4478 cancel formula execution

---

src/core/assets/cleanup.json
src/core/suite.js
src/test/elements/hubspot/bulk.js
src/test/elements/quickbooksonprem/polling.js
test/core/assets/suite-helper.js
test/core/suite.test.js

* You must specify bulk to accept json, csv, or both
* `apiOverride` is no longer an argument, use `.withApi` instead
* Updated the tests with the removed `apiOverride` arg

Enhanced bulk tests

---

src/test/platform/usage/usage.js

* Previously, usage tests could pass without recent logs reaching ES. This change ensures that a new request is present in the usage logs.

Verify new request ID present on usage test init

---

src/test/platform/elementbuilder/assets/models/contacts_metadata.json
src/test/platform/elementbuilder/assets/models/onemodel_element.json
src/test/platform/elementbuilder/models.js

* Added tests for element `/objects` to be resource names, even if the model names are different
* Added tests for element `/objects/{objectName}/metadata` to be superset of all models for the resource with method at the field level

Tests for element object metadata and object names enhancements 

---

src/test/elements/mixpanel/activities.js
src/test/elements/mixpanel/assets/activities.json
src/test/elements/mixpanel/assets/users.json
src/test/elements/mixpanel/bulk.js
src/test/elements/mixpanel/users.js

* Mixpanel element tests for activities, users and bulk
```
churros test elements/mixpanel
info: Running tests for element: mixpanel
info: Provisioned with instance id of 5882
activities
✓ should allow POST for /hubs/general/activities (754ms)
bulk
error: Failed to retrieve or validate: /hubs/general/bulk/5138/status
error: Failed to retrieve or validate: /hubs/general/bulk/5138/status
error: Failed to retrieve or validate: /hubs/general/bulk/5138/status
✓ should support bulk download of activities (10138ms)
error: Failed to retrieve or validate: /hubs/general/bulk/5139/status
✓ should support bulk download of users (3375ms)
users
✓ should allow CUDS for /users (1930ms)
4 passing (24s)
1 pending
```

Mixpanel element tests

---

src/test/elements/freshservice/incidents.js

```
incidents
✓ should allow CRDS for /hubs/helpdesk/incidents (1094ms)
✓ should allow paginating with page and pageSize for /hubs/helpdesk/incidents (797ms)
✓ should allow C for /hubs/helpdesk/incidents/:id/comments (723ms)
✓ should allow CRUDS for /hubs/helpdesk/incidents/:id/tasks (1601ms)
✓ should allow pagination with page and pageSize for /hubs/helpdesk/incidents/:id/tasks (2185ms)
✓ should allow pagination with page and 1000 pageSize for /hubs/helpdesk/incidents/:id/tasks (2116ms)
```

Tests for pageSize over 1000!

---

src/test/elements/onedrivebusiness/files.js

* Added the overwrite parameter in the POST /files API. 
* While doing the POST /file, if the file is present and overwrites param is true it will overwrite the existing file. Making it true if in any case there, given path is already present then also it will successfully post the file and other dependent operation also passed successfully.
* Closes #${6461}

CE-6461: Added overwrite parameter in POST /file API of One Drive Business

---

src/core/oauth.js
src/test/elements/linkedin/ping.js

* The authentication was not getting through successfully as the `Allow Access` button was not getting clicked
* Changed the name of the button to be clicked in the `oauth.js` file
* Fixed the issue. The authentication and instance creation will now happen smoothly.
* Closes [#DE43](https://rally1.rallydev.com/#/144349237612d/detail/defect/152433784204)

Fixed LinkedIn authentication

---

src/test/elements/mixpanel/activities.js

* Added activities/top API to test
```
venkats-mbp:churros ramana$ churros test elements/mixpanel
info: Running tests for element: mixpanel
info: Provisioned with instance id of 6035
activities
✓ should allow POST for /hubs/general/activities (7532ms)
✓ should allow GET for /hubs/general/activities/top (417ms)
bulk
error: Failed to retrieve or validate: /hubs/general/bulk/5164/status
error: Failed to retrieve or validate: /hubs/general/bulk/5164/status
error: Failed to retrieve or validate: /hubs/general/bulk/5164/status
✓ should support bulk download of activities (10084ms)
error: Failed to retrieve or validate: /hubs/general/bulk/5165/status
error: Failed to retrieve or validate: …
```

Added activities/top API to test

---

src/test/elements/sfdcdocuments/search.js

Searching within  "text" query with any random text should return 400 error. 
* Closes [#US1357-TA608-sfdcdocuments](https://rally1.rallydev.com/#/144349237612d/detail/task/153578211224?fdp=true)

Fixing Search churros for SFDC documents

---

src/test/platform/elementbuilder/assets/objects/onemodel_element.json
src/test/platform/elementbuilder/element-objects.js
src/test/platform/elementbuilder/elementextend.js

* Modelbuilder swagger tests
```
venkats-mbp:churros ramana$ churros test platform/elementbuilder --file element-objects
element-objects
✓ should support calling objectnames for instance (1573ms)
✓ should support calling objects metadata for instance (169ms)
✓ should support calling generating swagger docs for the instance (199ms)
3 passing (4s)
```

Modelbuilder swagger tests

---

src/test/elements/sfdc/leads.js

* Added a churros test.withOptions() to test with email='' for Salesforce Sales Cloud single quote issue
* Closes #${DE4}

Added a test case for Salesforce single quote

---

src/test/elements/freshdeskv2/assets/accounts.json

* Fixed payload for POST /accounts. It takes `customer` field as a complex object and within which `name` is required.
* While running churros after fixing the issue https://github.com/cloud-elements/soba/issues/7360, churros test failed only for this specific API. Hence corrected the same.

Freshdesk V2 : Fixed payload for POST /accounts

---

src/test/elements/assets/object.definitions.json
src/test/elements/netsuitefinancev2/assets/vendors.json
src/test/elements/netsuitefinancev2/classifications.js
src/test/elements/netsuitefinancev2/customers.js
src/test/elements/netsuitefinancev2/polling.js
src/test/elements/netsuitefinancev2/tax-codes.js
src/test/elements/netsuitefinancev2/tax-rates.js
src/test/elements/netsuitefinancev2/time-activities.js
src/test/elements/netsuitefinancev2/vendor-payments.js
src/test/elements/netsuitefinancev2/vendors.js

* Fixed the failing churros 
* Churros result with polling enabled 
* Churros result without polling enabled after fixed classification API
* Closes #${https://rally1.rallydev.com/#/144349237612d/detail/userstory/151491240492}

Netsuitefinance: Fixed the failing churros 

---

src/core/oauth.js
src/test/elements/shopify/addresses.js
src/test/elements/shopify/fulfillment-events.js
src/test/elements/shopify/fulfillments.js

* Removed skip from` /fulfillments, /fulfillment-events and /addresses `churros test  
* Fixed the instance creation flow 
* Fixed the /fulfillments and /fulfillment-events churros test 
* Not removed skip from discounts APIs it is deprecated  and they are not visible in the swagger doc 
* [RALLY-#${https://rally1.rallydev.com/#/144349237612d/detail/userstory/151491239588}](Link to Rally User Story or Task)
* Closes #${https://rally1.rallydev.com/#/144349237612d/detail/userstory/151491239588}

Shopify : Fixed the failing churros test 

---

src/test/elements/marketo/assets/newResource.json
src/test/elements/marketo/extended-resource.js

* Implemented churros te test extended resources for Marketo. 
* [SOBA](https://github.com/cloud-elements/soba/pull/7382)
* [RALLY-#${ticketNumber}(https://rally1.rallydev.com/#/144349237612d/detail/userstory/153626883688)
* Closes #US1362 : https://rally1.rallydev.com/#/144349237612d/detail/userstory/153626883688

Implemented churros  for extended resources of Marketo

---

src/cli/churros-test.js
src/core/provisioner.js
src/test/elements/lifecycle.js
test/core/provisioner.test.js

* Will use back up instance if provisioning fails
* Added flag with 3 options `--backup ['use backup', 'no backup', 'only backup']`
* Defaults to use backup
`churros test elements/box --backup 'no backup'`
Without back up it won't provision
https://cl.ly/1b0W2l1l2l0B
Skips provisioning process `--backup 'only backup'`
https://cl.ly/0S2g1C2y3g3S
Fails then uses backup
https://cl.ly/1h420X2z2A1d
* [RALLY-#US1464]https://rally1.rallydev.com/#/144349237612d/detail/userstory/155170826608?fdp=true

Added ability to use a back up instance

---

src/test/elements/lifecycle.js

* Incase of failure don't delete backup instance
* Only happens when something during provisioning throws error

Don't cleanup back up

---

src/test/elements/mailjet/assets/newResource.json
src/test/elements/mailjet/extended-resource.js

* Added Churros for extended resources of  MailJet.
* All churros tests are passing, including testing for addition of new resource.
* https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195548928
* Closes #US-1493

Added churros for extended resource for MailJet

---

src/test/elements/adobe-esign/groups.js
src/test/elements/adobe-esign/library-documents.js
src/test/elements/adobe-esign/transient-documents.js
src/test/elements/adobe-esign/uris.js
src/test/elements/adobe-esign/users.js
src/test/elements/adobe-esign/widgets.js
src/test/elements/adobe-esign/workflows.js

* There were test cases skipped on Adobe E Sign. 
* Verified whether those are passing and un-skipped them
* Added a comment  where skip is needed due to unavailability of delete API
* Churros result: 
* Closes  [#US1141](https://rally1.rallydev.com/#/144349237612d/detail/userstory/149195710604)

Unskipped test cases and added comment where needed for Adobe E Sign

---

src/test/elements/sharepoint/assets/newResource.json
src/test/elements/sharepoint/extended-resource.js

* Added churros test cases for SharePoint extended resources
Polling for Sharepoint is not working, raised a separate bug (#DE83) for the same.
* Closes #US1491

Added test cases for extended resources of Sharepoint

---

src/test/elements/marketo/assets/sampleBulkCustomObject_c.json
src/test/elements/marketo/sampleBulkCustomObject_c.js
src/test/elements/marketo/tagTypes.js

* Using dynamic data for posting a new record for `sampleBulkCustomObject_c` object.
* Removed `skip` from `tagTypes` resource test.
* [RALLY-#US1312](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/151491240096k)
* Closes #US1312

Fixed failing custom object test for Marketo element

---

src/test/platform/users/assets/role.schema.json
src/test/platform/users/assets/roles.schema.json
src/test/platform/users/users.js

* Tests for the new user roles APIs:
* `GET /users/:id/roles`
* `PUT /users/:id/roles/:roleKey`
* `DELETE /users/:id/roles/:roleKey`
```
$ churros test platform/users
users
✓ should support CRUDS for users (402ms)
user roles
✓ should support CRD of admin role for user in own account (509ms)
✓ should not support CRD of roles for user in other account (318ms)
✓ should throw a 404 when trying to PUT /users/-1/roles/admin with an ID that does not exist (109ms)
✓ should return a 403 on PUT where user does not have permission to grant the role
✓ should return a 403 on PUT where user does not have permission to grant the role
✓ should return a 400 on PUT with an invalid role
✓ should return a 409 on two PUTs with the …
```

Tests for user roles

---

src/core/suite.js
src/test/platform/accounts/accounts.js
src/test/platform/accounts/assets/role.schema.json
src/test/platform/accounts/assets/roles.schema.json
test/core/assets/suite-helper.js
test/core/suite.test.js

* Tests for accounts roles APIs related to the new roles architecture in Soba.
```
accounts
✓ should allow CRUD for /accounts (2111ms)
✓ should allow S for /accounts (477ms)
✓ should support searching /accounts by name (1112ms)
✓ should throw a 404 when trying to DELETE /accounts with an ID that does not exist (577ms)
✓ should throw a 404 when trying to PATCH /accounts with an ID that does not exist (545ms)
✓ should throw a 404 when trying to GET /accounts with an ID that does not exist (576ms)
account roles
✓ should support CRD of roles for own account (1479ms)
✓ should not support CRD of roles for other org's account (617ms)
✓ should throw a 404 when trying to PUT /accounts/-1/roles/admin with an ID that does not exist (224ms)
✓ should throw a 403 when trying to PUT …
```

Account roles tests

---

src/test/elements/sendgrid/assets/newResource.json
src/test/elements/sendgrid/extended-resource.js

* Added Churros for extended resources of SendGrid.
* [SOBA](https://github.com/cloud-elements/soba/pull/7519)
* [RALLY-#$US1499](https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195550592)
* Closes #$[US1499](https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195550592)

Added Churros for extended resource for SendGrid (Messaging)

---

src/test/elements/twilio/assets/newResource.json
src/test/elements/twilio/extended-resource.js

* Added Churros for extended resources of Twilio SMS (Messaging).
* No churros test present currently for Twilio SMS element.
* Basic Tests are failing as Twilio does not contain any `objects` and `definitions`.
* Churros passing for extended-resource.
* Churros Sauce file update pending, as Kelly needs to confirm which credentials needs to be added.
* [SOBA](https://github.com/cloud-elements/soba/pull/7517)
* [RALLY-#$US1592](https://rally1.rallydev.com/#/144349237612d/detail/userstory/156281695228)
* Closes #$[US1592](https://rally1.rallydev.com/#/144349237612d/detail/userstory/156281695228)

Added Churros for extended resource for Twilio SMS (Messaging)

---

src/test/elements/mailjetmarketing/assets/newResource.json
src/test/elements/mailjetmarketing/extended-resource.js

* Added Churros for extended resources of MailJet Marketing.
* [SOBA](https://github.com/cloud-elements/soba/pull/7490)
* [RALLY-#$US1494](https://rally1.rallydev.com/#/144349237612d/detail/userstory/155195549172)
* Closes #$US1494

Added Churros for extended resource for MailJet Marketing

---

src/test/elements/bigcommerce/customers.js
src/test/elements/bigcommerce/orders.js

- Added  appropriate comments in orders.js for skip test and updated where query in orders and customers.js
- Please  find attached the results of the tests running successfully
[bigcommerce-polling-churros.txt](https://github.com/cloud-elements/churros/files/1344261/bigcommerce-polling-churros-stag.txt)
- PFA the test results after tax-calculations is set to Manual and order tests are unskipped
[bigcommerce-churros-orders-unskipped.txt](https://github.com/cloud-elements/churros/files/1389975/bigcommerce-churros-orders-unskipped.txt)
* [RALLY-#${US1485}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/155192973820) …

BigCommerce : Updated customers and orders churros tests

---

src/test/elements/netsuitefinancev2/assets/customrecords.json
src/test/elements/netsuitefinancev2/assets/expense-reports.json
src/test/elements/netsuitefinancev2/customrecords.js
src/test/elements/netsuitefinancev2/expense-reports.js

* Churros for CustomRecords and ExpenseReports
seshus-MacBook-Pro:~ seshuede$ churros test elements/netsuitefinancev2 --file customrecords --instance 276
info: Running tests for element: netsuitefinancev2
info: Provisioned with instance id of 276
error: Failed to create or validate: /instances/276/objects/accounts/definitions
error: Failed to create or validate: /instances/276/objects/accounts/definitions
error: Failed to create or validate: /instances/276/transformations/accounts
error: Failed to create or validate: /instances/276/transformations/accounts
custom-record-types
✓ should allow CRUDS /hubs/finance/customrecords (17213ms)
1 passing (21s)
1 pending
seshus-MacBook-Pro:~ seshuede$ churros test elements/netsuitefinancev2 --file …

Churros for CustomRecords and ExpenseReports

---

src/test/elements/assets/basics.js

* Document hub doesn't always support this endpoint
* google drive now passes all
Google drive: https://cl.ly/2Y081O0Q2n0f

Won't run the /objects tests on the doc hub

---

src/test/platform/elements/instances.js

* Checking for elements-element-instance-id header on responses from elements
* [SOBA](https://github.com/cloud-elements/soba/pull/7572)

Testing presence of elements-element-instance-id header on elements responses

---

src/test/elements/ecwid/assets/newResource.json
src/test/elements/ecwid/extended-resource.js

- Added  test cases for Ecwid extended-resource
[Ecwid- Churros-Results.txt](https://github.com/cloud-elements/churros/files/1382733/Ecwid-.Churros-Results.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/7530)
* [RALLY-#${US1595}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/156281696296)
* Closes #[US1595](https://rally1.rallydev.com/#/144349237612d/detail/userstory/156281696296)

US1595: Updated Ecwid to be Extendable

---

src/test/elements/assets/object.definitions.json
src/test/elements/sapbusinessone/assets/equipment-cards.json
src/test/elements/sapbusinessone/assets/transformations.json
src/test/elements/sapbusinessone/customers.js
src/test/elements/sapbusinessone/equipment-cards.js

elements-mac67->/Users/atul (master-US2498): churros test elements/sapbusinessone
info: Using user: demandbase@cloud-elements.com
info: Using oauth username: manager
info: Running tests for element: sapbusinessone
info: Provisioned with instance id of 289
Basic tests
✓ should GET /objects (158ms)
- docs
✓ metadata (181ms)
✓ transformations (7398ms)
customers
✓ should allow CRUDS for /hubs/erp/customers (3884ms)
✓ should allow paginating with page and pageSize for /hubs/erp/customers (1929ms)
✓ should support searching /hubs/erp/customers by CardName (1465ms)
drafts
✓ should allow CRDS for /hubs/erp/drafts (3071ms)
✓ should allow paginating with …

Enhanced/ Added New Test for SAPBusinessOne

---

src/test/elements/quickbooks/assets/estimates.json
src/test/elements/quickbooks/estimates.js

* Quickbooks estimate object tests
```
asura:churros ramana$ churros test elements/quickbooks
info: Using url: http://localhost:5050
info: Using user: churros@ce.com
info: Using oauth username: quickbooks@cloud-elements.com
info: Using api key: qyprdxLrqNbUbzaIRo3AsvwE9bPwHO
info: Running tests for element: quickbooks
info: Provisioned with instance id of 6283
Basic tests
✓ should GET /objects (152ms)
- docs
✓ metadata (110ms)
error: Failed to delete /instances/6283/transformations
error: Failed to delete /instances/6283/transformations
✓ transformations (401ms)
bill-payments
✓ should allow CRDS for /hubs/finance/bill-payments (6132ms)
✓ should allow GET for /hubs/finance/bill-payments …
```

Quickbooks estimate object tests

---

src/test/elements/sfdc/assets/users.json

* Changing the alias for users tests to make removing in future with Data Loader Easier
* [US3123](https://rally1.rallydev.com/#/144349238268d/detail/userstory/174528527120)

changing alias for users

---

src/test/elements/ciscospark/users.js

* Removed `skip` from `users` CRUD APIs as `DELETE /users` API is working now.
* [RALLY-#US3108](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/174410551440)

Removed 'skip' from 'users' APIs

---

src/test/elements/quickbooks/preferences.js

* Added test cases for preference endpoints of QuickBooks Online element
* [SOBA](https://github.com/cloud-elements/soba/pull/7633)
* [RALLY-#[US2485](https://rally1.rallydev.com/#/144349237612d/detail/userstory/163971164532)
* Closes #$US2485

Added test cases for preference endpoints of QuickBooks Online element

---

src/core/oauth.js
src/test/elements/onenote/assets/newResource.json
src/test/elements/onenote/extended-resource.js

* Added churros for extended-resource for Onenote.
Churros for this element is missing created the User story for the same.
* [[SOBA]](https://github.com/cloud-elements/soba/pull/7570)
* [[churros-sauce]](https://github.com/cloud-elements/churros-sauce/pull/111)
* [RALLY-#${US1599}][https://rally1.rallydev.com/#/144349237612d/detail/task/162178648660](https://rally1.rallydev.com/#/144349237612d/detail/task/162178648660)

Added churros for extended-resource for Onenote

---

src/test/elements/bullhorn/assets/company.json
src/test/elements/bullhorn/assets/placments.json
src/test/elements/bullhorn/candidates.js
src/test/elements/bullhorn/company.js
src/test/elements/bullhorn/contacts.js
src/test/elements/bullhorn/notes.js
src/test/elements/bullhorn/placements.js

* Added tests for new endpoints  - `placements ,  company`
* Company currently does not support Delete operation, so the test for company CRUS are skipped.
* SOBA PR - #[7680](https://github.com/cloud-elements/soba/pull/7680)
* RALLY #[US2295](https://rally1.rallydev.com/#/144349237612/detail/userstory/172897030496), #[US2996](https://rally1.rallydev.com/#/144349237612/detail/userstory/172897686352)
* Closes  #[US2295](https://rally1.rallydev.com/#/144349237612/detail/userstory/172897030496), #[US2996](https://rally1.rallydev.com/#/144349237612/detail/userstory/172897686352)

Added churros tests for new resources for Bullhorn

---

src/test/elements/zuorav2/assets/subscriptions.json
src/test/elements/zuorav2/subscriptions.js

1. Added tests for Suspend and Resume APIs.
2. Please note that sauce credentials do not work for these APIs as they do not have permission to suspend a subscription.
3. Credentials to test are:
kelly@cloud-elements.com
Z3brasrideoncl0uds!
* [SOBA](https://github.com/cloud-elements/soba/pull/7693)
* [RALLY-#${US2757}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168528669852)
* [RALLY-#${US2758}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168528670264)
* Closes 
#$[{US2757}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168528669852) …

ZuoraV2 : Added test for Suspend and Resume API

---

src/test/elements/googlecalendar/access-control-list.js

* Removed pagination test case of access-control-list resource of google Calendar element.
* [SOBA](https://github.com/cloud-elements/soba/pull/7652)
* [RALLY]-#$[DE435](https://rally1.rallydev.com/#/144349237612d/detail/defect/173146322572)
* Closes #$DE435

Removed pagination test case of access-control-list resource of google Calendar element

---

src/test/platform/formulas/assets/formulas/amqp-step.json
src/test/platform/formulas/assets/formulas/notification-step.json
src/test/platform/formulas/assets/formulas/notify-email.json
src/test/platform/formulas/executions.js

* formula amqp step test
* formula notification step and notify.email tests
* [RALLY-#${US4266}](https://rally1.rallydev.com/#/144349238268d/detail/userstory/179993177580)

add formula execution tests for amqp and notification steps and notify.email

---

src/test/elements/intacct/assets/attachment.json
src/test/elements/intacct/assets/objects.attachments.json
src/test/elements/intacct/assets/transformations.json
src/test/elements/intacct/attachments.js

* Added Churros for attachment API's of Intacct.
* [SOBA](https://github.com/cloud-elements/soba/pull/7708)
* [RALLY-#${US2872}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/170991500320?fdp=true)
* Closes #[US2872](https://rally1.rallydev.com/#/144349237612d/detail/userstory/170991500320?fdp=true)

Added Churros for attachment API's of Intacct

---

src/test/elements/intacct/assets/schema.json
src/test/elements/intacct/reporting-periods.js

* Added churros for reporting periods API for Intacct.
* [SOBA](https://github.com/cloud-elements/soba/pull/7718)
* [RALLY-#${#2999}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/172898191972?fdp=true)
* Closes #$[2999](https://rally1.rallydev.com/#/144349237612d/detail/userstory/172898191972?fdp=true)

Added churros for reporting periods API for Intacct

---

src/test/platform/formulas/assets/formulas/complex-to-upgrade.json
src/test/platform/formulas/formulas.js

* Tests for the formula APIs to upgrade a formula to v3 and revert back to v1
* [SOBA](https://github.com/cloud-elements/soba/pull/7759)

Formula upgrade and revert API test

---

src/test/platform/models/assets/payload.json
src/test/platform/models/assets/payload.schema.json
src/test/platform/models/models.js

* Model auto generation tests for `POST /models/{objectName}/schema`
```
asura:churros ramana$ churros test platform/models
models
✓ should generate model schema from payload (1718ms)
1 passing (3s)
```
* [7775](https://github.com/cloud-elements/soba/pull/7775)
* [US3470](https://rally1.rallydev.com/#/153723136912ud/detail/userstory/178585626984)

Model autogeneration tests

---

src/test/elements/adobe-esign/users.js

* Added Search test in /users API of Abode-Sign
* [SOBA](https://github.com/cloud-elements/soba/pull/7830)
* [RALLY-#${DE-558}](https://rally1.rallydev.com/#/144349237612d/detail/defect/181105993840)
* Closes #${[DE-558](https://rally1.rallydev.com/#/144349237612d/detail/defect/181105993840)}

Added /users API  of Abode-Sign 

---

src/test/elements/onedrivev2/folders.js

* The `GET /folders/contents?path=%2F` and `GET /folders/contents?path=%2FDocuments` APIs were failing for Total Jobs for the OneDriveV2 element due to a soba class loader issue that was seen only in the EU production environment.
* Added tests for the above APIs
* [RALLY- #DE619] https://rally1.rallydev.com/slm/detail/df/184793607740
* Closes #DE619

Added tests for the OneDriveV2 element for root and Documents folder contents

---

src/test/elements/box/files.js

* Added tests for:
* `GET /files/revisions by path`
* `GET /files/revisions/:revisionId by path`
* `GET /files/:id/revisions`
* `GET /files/:id/revisions/:revisionId`
* [SOBA](https://github.com/cloud-elements/soba/pull/7771)
* ~[CircleCI](Link to SOBA PR adding Tests to `circle.yml`, when applicable)~
* ~[churros-sauce](Link to Associated Churros-sauce PR, when applicable)~
* [RALLY-#US3189](https://rally1.rallydev.com/#/144349237612d/detail/userstory/175563856328)

Box /files/revisions endpoints tests

---

src/test/elements/onedrivev2/files.js

* `GET /files/:id/revisions`
* `GET /files/:id/revisions/:revisionId`
* `GET /files/revisions`
* `GET /files/revisions/:revisionId`
* `GET /files/:id/revisions`  (List all revisions by file Id.)
* `GET /files/:id/revisions/:revisionId` (Retrieve revision by file Id.)
* `GET /files/revisions`  (List all revisions by file Path.)
* `GET /files/revisions/:revisionId` (Retrieve revision by file Path.)
-- | -- | --
[SOBA](https://github.com/cloud-elements/soba/pull/7817)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/user …

Enhanced OneDrive with revisions API

---

src/test/elements/intacct/vendors.js

* Pre-DE586, Intacct returned whatever was requested for pageSize if above maxPage. Now, we should return substantially less
**Note**: failing resources, _reporting periods_ and _attachments_ - have unmerged soba PRs
```
churros test elements/intacct
error: Failed to retrieve or validate: /hubs/finance/bills-payments
info: Using user: system
info: Running tests for element: intacct
info: Provisioned with instance id of 819
Basic tests
✓ should GET /objects (130ms)
- docs
✓ metadata (196ms)
error: Failed to retrieve or validate: /hubs/finance/attachments
1) transformations
attachments
error: Failed to retrieve or validate: /hubs/finance/attachments
2) should allow CRUDS for …
```

Added edge case test for DE586

---

src/test/elements/onedrivebusiness/files.js

* `GET /files/:id/revisions`
* `GET /files/:id/revisions/:revisionId`
* `GET /files/revisions`
* `GET /files/revisions/:revisionId`
* `GET /files/:id/revisions`  (List all revisions by file Id.)
* `GET /files/:id/revisions/:revisionId` (Retrieve revision by file Id.)
* `GET /files/revisions`  (List all revisions by file Path.)
* `GET /files/revisions/:revisionId` (Retrieve revision by file Path.)
-- | -- | --
[Soba](https://github.com/cloud-elements/soba/pull/7827) 
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/use …

Enhanced OneDriveBusiness with revisions API

---

src/test/platform/organizations/rbac.js

* More detailed RBAC privileges tests
**roles** (/organizations/roles, /org/users/id/roles)
- put /organizations/roles/reset
- put /organizations/roles
**common objects**
- get /accounts/objects/definitions
**elements**
- clone
- resources
- parameters **found bug in read
- configuration
- hooks
- active
- resource parameters
- resource models
- resource hooks
- instances
**formulas**
- PATCH formulas
- triggers
- steps
- configs
- instances (updates)
* https://github.com/cloud-elements/soba/pull/7836
* [US5047](https://rally1.rallydev.com/#/144349238268d/detail/userstory/182651219456)

RBAC tests round 2

---

src/test/platform/formulas/assets/formulas/faar-modified-request-key.json
src/test/platform/formulas/faar.js

* Added regression test for FaaR to make sure triggers with key `request` doesn't get overwritten
* [7770](https://github.com/cloud-elements/soba/pull/7770)

FaaR trigger request key integration test

---

src/test/elements/assets/object.definitions.json
src/test/elements/intacct/assets/bill-payments.json
src/test/elements/intacct/assets/transformations.json
src/test/elements/intacct/bills-payments.js

* Updated tests to use transformations 
* Fixed bill-payments tests
```
churros test elements/intacct
info: Using user: system
info: Running tests for element: intacct
info: Provisioned with instance id of 824
Basic tests
✓ should GET /objects (146ms)
- docs
✓ metadata (210ms)
error: Failed to retrieve or validate: /hubs/finance/attachments
1) transformations
attachments
error: Failed to retrieve or validate: /hubs/finance/attachments
2) should allow CRUDS for /hubs/finance/attachments
error: Failed to retrieve or validate: /hubs/finance/attachments
3) should allow paginating with page and pageSize for /hubs/finance/attachments
error: Failed to retrieve or validate: …
```

Updated Intacct tests

---

src/test/elements/zuorav2/assets/transformations.json
src/test/elements/zuorav2/customers.js
src/test/elements/zuorav2/invoices.js
src/test/elements/zuorav2/subscriptions.js

* ☝️ 
```
churros test elements/zuorav2
info: Using user: system
info: Using oauth username: kelly@cloud-elements.com
info: Running tests for element: zuorav2
info: Provisioned with instance id of 868
Basic tests
✓ should GET /objects (126ms)
- docs
✓ metadata (212ms)
✓ transformations (4159ms)
customers
✓ should support CreatedDate > {date} Ceql search (340ms)
✓ should allow paginating with page and nextPage /hubs/payment/customers (981ms)
✓ should allow CRUDS for /hubs/payment/customers (1384ms)
✓ should allow CRUDS /hubs/payment/customers/id/payment-method (2292ms)
✓ should allow GET /hubs/payment/customers/id/history,GET /hubs/payment/customers/id/payments (260ms)
✓ GET …
```

Fixed and cleaned up Zuora tests

---

src/test/elements/acton/lists.js

There is a limitation on acton side, it allows only 20 request  per 60 secs
* Fix failing churros for Acton
* [DE519](https://rally1.rallydev.com/#/144349237612d/detail/defect/179008725356)

Fix failing churros for Acton

---

src/test/elements/onedrivev2/folders.js

* `GET /folders/:id/contents`
* `GET /folders/contents`
* `GET /folders/:id/contents where : (name = 'filename')`
* `GET /folders/contents where : (extension = '.txt')`
-- | -- | --
[Soba](https://github.com/cloud-elements/soba/compare/OneDrive_US3209?expand=1) 
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/175564890248)

Enhanced OneDrive folders/contents API with ability to filter files by name and extension

---

src/test/elements/onedrivebusiness/folders.js

* `GET /folders/:id/contents`
* `GET /folders/contents`
* `GET /folders/:id/contents where : (name = 'filename')`
* `GET /folders/contents where : (extension = '.txt')`
-- | -- | --
[Soba](https://github.com/cloud-elements/soba/pull/7841) 
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/175564889260)

Enhanced OneDrive Business folders/contents API with ability to filter files by name and extension

---

src/test/elements/googledrive/files.js
src/test/elements/googledrive/folders.js

* Added test for `GET /folders/contents?includePath=false` 
* Addressed issue with Google Drive attempting to validate a response contained data it would never contain
* Removed unnecessary body != null checks from tests that validated body contained certain data right after
* [SOBA](https://github.com/cloud-elements/soba/pull/7859)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/150)
* [RALLY-#US5949](https://rally1.rallydev.com/#/144349238268d/search?keywords=US5949)

Google Drive - includePath test

---

src/test/elements/facebookleadads/leads.js
src/test/elements/facebookleadads/pages.js

* Added test cases for `leads` resource
* In the test cases for `pages` resource, the `GET /leads/{leadId}` API was being used. Changed those to use the correct API.
* Also added test cases for testing the `fields` param on both the resources GET by `id` APIs
* [SOBA for pages resource](https://github.com/cloud-elements/soba/pull/7849)
* [SOBA for leads resource](https://github.com/cloud-elements/soba/pull/7849)
* [RALLY-#US5585](https://rally1.rallydev.com/#/144349237612d/detail/userstory/185452570132)
* [RALLY-#US5653](https://rally1.rallydev.com/#/144349237612d/detail/userstory/186259325732)
* [#US5586](https://rally1.rallydev.com/#/144349237612d/detail/userstory/185452570552)
* [#US5653](https://rally1.rallydev.com/#/144349237612d/detail/userstory/186259325732)

Added test cases for leads and corrected for pages on Facebook Lead Ads

---

src/test/elements/marketo/assets/contacts.json
src/test/elements/marketo/contacts.js

* ☝️ 
```
churros test elements/marketo
info: Using user: system
info: Using oauth username: marketo@cloud-elements.com
info: Using api key: 19e7183b-53ac-4366-ad5a-205deb9bec84
info: Running tests for element: marketo
info: Provisioned with instance id of 938
Basic tests
✓ should GET /objects (785ms)
- docs
✓ metadata (144ms)
error: Failed to retrieve or validate: /hubs/marketing/activities
error: Failed to retrieve or validate: /hubs/marketing/companies
error: Failed to retrieve or validate: /hubs/marketing/sampleBulkCustomObject_c
✓ transformations (4620ms)
activities
✓ should allow GET for /hubs/marketing/activity-types (717ms)
✓ should allow GET for …
```

Fixed contacts and added POST /contacts/:id/merge tests

---

src/test/elements/clover/assets/order.json
src/test/elements/clover/orders.js

* Added churros for /orders api
* [SOBA](https://github.com/cloud-elements/soba/pull/7854)
* [RALLY-#${US2993}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/172615120724)
* Closes #[US2993](https://rally1.rallydev.com/#/144349237612d/detail/userstory/172615120724)

Churros for /orders api

---

src/test/elements/readytalk/recordings.js

* Added new Test cases for API getByID for Recordings 
* [SOBA](https://github.com/cloud-elements/soba/tree/US6873)
* [RALLY- US6873](https://rally1.rallydev.com/#/144349237612d/detail/userstory/190656993420)
*  [RALLY- US6873](https://rally1.rallydev.com/#/144349237612d/detail/userstory/190656993420)

Readytalk record registration test cases added

---

src/test/elements/mailjetmarketing/assets/campaigns.json
src/test/elements/mailjetmarketing/assets/contacts.json
src/test/elements/mailjetmarketing/assets/lists.json
src/test/elements/mailjetmarketing/assets/listsContacts.json
src/test/elements/mailjetmarketing/ping.js

* Added missing payloads for :
1. assets/campaigns.json
2. assets/contacts.json
3. assets/lists.json
4. assets/listsContacts.json
* Added missing test for `ping.js`
* All churros are passing. Only one basic test is failing.
* [RALLY-DE125](https://rally1.rallydev.com/#/144349237612d/detail/defect/162202371088)
* [DE125](https://rally1.rallydev.com/#/144349237612d/detail/defect/162202371088)

Mailjet Marketing : Added missing payloads and tests

---

src/test/elements/hubspotcrm/owners.js

* Fixed churros for `owners.js` by removing the test for CRUD operations as the API is not present in the element.
* Churros run successfully
* [RALLY-DE635](https://rally1.rallydev.com/#/144349237612d/detail/defect/185383094480)
* [DE635](https://rally1.rallydev.com/#/144349237612d/detail/defect/185383094480)

Hubspot CRM : Fixed Churros

---

src/test/elements/onedrivev2/folders.js

The special character test and filter tests were invalid. The corresponding SOBA code is on hold but churros got merged. Commented the test cases for now. These were necessary to be in comment as we wanted to run US7224 successfully. 

Commenting invalid test cases

---

src/test/platform/usage/usage.js

* Adds tests to be sure analytics endpoints for elements and formulas return empty arrays instead of 404s
* [SOBA](https://github.com/cloud-elements/soba/pull/7957)

Element and Formula analytics empty response test

---

src/test/elements/box/files.js
src/test/elements/box/index.js
src/test/elements/googledrive/files.js

* Googledrive and Box added tests for posting a file by folderid
```
elemnts-mac49:churros ramana$ churros test elements/box
info: Using url: http://localhost:5050
info: Using user: churros@ce.com
info: Using oauth username: developer@cloud-elements.com
info: Using api key: 0zltudvqp2mlbqbctahxhndis0p630hm
info: Running tests for element: box
error: Failed to retrieve or validate: /instances
info: Provisioned with instance id of 6379
Basic tests
✓ should GET /objects (1359ms)
- docs
✓ metadata (185ms)
✓ transformations
custom-fields
- should support CRUS for /custom-fields/templates
files
✓ should allow POST /files by providing folder id (9182ms)
✓ should allow PUT /files/:id/lock and …
```

Googledrive and Box added tests for posting a file by folderid

---

src/test/elements/bullhorn/assets/candidates.json
src/test/elements/bullhorn/assets/company.json
src/test/elements/bullhorn/assets/contacts.json
src/test/elements/bullhorn/assets/opportunities.json
src/test/elements/bullhorn/candidates.js
src/test/elements/bullhorn/company.js
src/test/elements/bullhorn/contacts.js
src/test/elements/bullhorn/leads.js
src/test/elements/bullhorn/notes.js
src/test/elements/bullhorn/opportunities.js

* Added test cases on every resource to test the GET APIs with `fields` parameter.
* Corrected the test cases for `companies` resource as they were initially refering to a non-existing URL with enpoint as `company`. Changed this to `companies`
* The credentials for Bullhorn are not specified in the `sauce.js` file. A valid set of credentials is not yet available. Have requested for the same. Will add those  when available.
* [SOBA](https://github.com/cloud-elements/soba/pull/7862)
* [RALLY-#DE642](https://rally1.rallydev.com/#/144349237612d/detail/defect/186246933788)
* Closes [#DE642](https://rally1.rallydev.com/#/144349237612d/detail/defect/186246933788)

Enhanced test cases for Bullhorn

---

src/test/elements/onenote/assets/files.json
src/test/elements/onenote/assets/folders.json
src/test/elements/onenote/assets/textFile.txt
src/test/elements/onenote/files.js
src/test/elements/onenote/folders.js

* Added testcases for OneNote files and folders.
* [SOBA](https://github.com/cloud-elements/soba/pull/7923/)
* [RALLY-#${US6660}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/189405848196)
* Closes #${US6660}

Test cases for OneNote files and folders

---

src/test/elements/jira/incidents.js

* `GET  /incidents where : summary LIKE 'QBO%'`
* `GET  /incidents where : customfield_10100 = '1|hzzvw7:'`
* `GET  /incidents where : customfield_12201 like 'testing new field blah blah'`
* As Per JIRA Documentation Only `summary, description and comment`  fields supports 
LIKE (CE) / ~ (JIRA)
* Business Logic added to handle special characters in search values
`GET  /incidents where : creator = 'byron@cloud-elements.com'` 
`GET  /incidents where : reporter = 'Atul Barve'` 
`GET  /incidents where : created<='2015-09-17'` 
* Business Logic added to handle custom fields search of JQL using custom_field_Id
* Note : Custom Field Id's for any Custom Field are identified using `/fields API`
[Soba](https://github.com/cloud-elements/soba/pull/7933) …

JIRA - Fixed Issue of LIKE Operator and Custom Field Search

---

src/test/elements/square/assets/customer.json
src/test/elements/square/assets/transformations.json
src/test/elements/square/customers.js
src/test/elements/square/employees.js
src/test/elements/square/locations.js
src/test/elements/square/payments.js
src/test/elements/square/timesheets.js

* Square enhancements with `/customers` API
* Added Test cases to `/customers`.
* Fixed Churros Issues For Square.
[Soba](https://github.com/cloud-elements/soba/pull/7898)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/188402884648)

Square /customers API Testcases

---

src/test/elements/assets/object.definitions.json
src/test/elements/freshdeskv2/assets/accounts.json
src/test/elements/freshdeskv2/assets/transformations.json

* Fixes freshdeskv2 churros for /accounts
```elemnts-mac49:churros ramana$ churros test elements/freshdeskv2
info: Using url: http://localhost:5050
info: Using user: churros@ce.com
info: Using oauth username: pcTlQRXAg1YWdxDwsxIX
info: Running tests for element: freshdeskv2
error: Failed to retrieve or validate: /instances
info: Provisioned with instance id of 6410
Basic tests
✓ should GET /objects (137ms)
- docs
✓ metadata (155ms)
✓ transformations (2447ms)
accounts
✓ should allow CRUDS for /hubs/helpdesk/accounts (1428ms)
✓ should allow paginating with page and pageSize for /hubs/helpdesk/accounts (847ms)
agents
✓ should allow SR for /hubs/helpdesk/agents (406ms)
✓ should allow …
```

Fixes freshdeskv2 churros

---

src/test/elements/quickbooks/assets/currencies.json
src/test/elements/quickbooks/assets/deposits.json
src/test/elements/quickbooks/assets/transfers.json
src/test/elements/quickbooks/budgets.js
src/test/elements/quickbooks/currencies.js
src/test/elements/quickbooks/deposits.js
src/test/elements/quickbooks/transfers.js

* QuickBooks Online Enhanced with testcases for /transfers, /budgets, /deposits and currencies endpoints . 
[Soba](https://github.com/cloud-elements/soba/compare/Quickbooks_US7346?expand=1)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/193152085556)

QuickBooks Online Enhanced with /transfers, /budgets, /deposits and currencies endpoints

---

src/test/elements/sugarcrmv2/assets/activitiesEmails.json

* Fixed test cases for activitiesEmails
* The patch test cases were failing due to no update allowed on the fields `name` and `description`
* Removed the above 2 fields from the payload
* Complete report: 
[SugarCRM_churros.txt](https://github.com/cloud-elements/churros/files/1706671/SugarCRM_churros.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/8044)
* [RALLY-#US7693](https://rally1.rallydev.com/#/144349237612d/detail/userstory/195163540364)
* [#US7693](https://rally1.rallydev.com/#/144349237612d/detail/userstory/195163540364)

Fixed test cases for activitiesEmails on SugarCrm

---

src/test/elements/intacct/assets/transformations.json
src/test/elements/intacct/bills-payments.js

* Fixes Intacct `/bill-payments` testcases
* [Soba](https://github.com/cloud-elements/soba/pull/8060)
* [Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/196757925664)

Intacct fixes testcases for /bill-payments

---

src/test/elements/googledrive/folders.js
src/test/elements/googledrive/search.js

* Enhanced  Google  Drive API's with orderBy functionality
`GET /search    orderBy  : createdDate asc` 
`GET /folders/contents    orderBy  : name desc,createdDate asc`
`GET /folders/:id/contents  orderBy  : modifiedDate desc`
* Enhanced orderBy functionality to Google Drive `search, folders/contents and folders/:id/contents` API's
* Default sorting order is Ascending, as per documentation.
-- | -- | --
[Soba](https://github.com/cloud-elements/soba/compare/GoogleDrive_US7091?expand=1) …

Test cases for Google Drive search, folders/contents and folders/:id/contents with orderBy functionality

---

src/test/platform/accounts/users.js

* Fixed existing tests to work with newer deactivation/deletion logic.
* [SOBA](https://github.com/cloud-elements/soba/pull/8031)
* [RALLY-#US8100](https://rally1.rallydev.com/#/144349238268d/detail/userstory/195797035060)

Improved tests for account deactivation/deletion

---

src/test/elements/box/ping.js
src/test/elements/dropbox/ping.js
src/test/elements/dropboxbusiness/ping.js
src/test/elements/googledrive/ping.js

* `/Ping` API enhanced for GoogleDrive, Dropbox, Dropbox Business and Box 
* `/ping`  tells you, vendorConnection is Success or not.
[Soba](https://github.com/cloud-elements/soba/pull/8057)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/195164477496)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540739048)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540737828)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540737160)

Test Cases for Dropbox, Dropbox Business, Box, GoogleDrive enhanced with /ping API

---

src/test/elements/quickbooks/bill-payments.js
src/test/elements/quickbooks/bills.js
src/test/elements/quickbooks/classes.js
src/test/elements/quickbooks/credit-memos.js
src/test/elements/quickbooks/credit-terms.js
src/test/elements/quickbooks/customers.js
src/test/elements/quickbooks/departments.js
src/test/elements/quickbooks/employees.js
src/test/elements/quickbooks/estimates.js
src/test/elements/quickbooks/invoices.js
src/test/elements/quickbooks/journal-entries.js
src/test/elements/quickbooks/ledger-accounts.js
src/test/elements/quickbooks/payment-methods.js
src/test/elements/quickbooks/payments.js
src/test/elements/quickbooks/products.js
src/test/elements/quickbooks/purchase-orders.js
src/test/elements/quickbooks/purchases.js
src/test/elements/quickbooks/refund-receipts.js
src/test/elements/quickbooks/sales-receipts.js
src/test/elements/quickbooks/tax-agencies.js
src/test/elements/quickbooks/tax-codes.js
src/test/elements/quickbooks/tax-rates.js
src/test/elements/quickbooks/time-activities.js
src/test/elements/quickbooks/vendor-credits.js
src/test/elements/quickbooks/vendor.js

* Added test for query parameter `returnCount : true` for all supported APIs to check if `elements-return-count` header is present in response headers.
* Churros for customer-search is failing in staging as well.
* [SOBA](https://github.com/cloud-elements/soba/pull/7975)
* [RALLY-US7092](https://rally1.rallydev.com/#/144349237612d/detail/userstory/191447718964)
* [US7092](https://rally1.rallydev.com/#/144349237612d/detail/userstory/191447718964)

Quicbooks Online : Added test for checking elements-return-count header

---

src/core/oauth.js

* Added ability to provision Ecwid element using an Oauth2
* Added selenium script for provisioning Ecwid instance using  Oauth2
* Note: 
1) Basic tests transformations were failing before my implementation as well.
2) The churros testcases will be executed with new OAuth2 flow and not with existing custom flow.
* [SOBA](https://github.com/cloud-elements/soba/pull/8004)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/154)
* [RALLY-#${US2755}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168523636680)
* Closes [US2755](https://rally1.rallydev.com/#/144349237612d/detail/userstory/168523636680)

Added ability to provision Ecwid element using an Oauth2

---

src/test/platform/organizations/branding.js
src/test/platform/organizations/rbac.js

* Add churros test for new branding API properties
one test failing because missing AWS setup
* [SOBA](https://github.com/cloud-elements/soba/pull/8072)
* [RALLY-#TA7413](https://rally1.rallydev.com/#/detail/task/197326037840?fdp=true)

Add churros test for branding API properties

---

src/test/elements/netsuiteerpv2/customrecords.js

* Considering we have transformation, calling GET on internalId failing. It should be GET by 'id'.
* Closes #${DE737}

Adding the right ID for customrecords API

---

src/test/elements/adobe-esign/ping.js
src/test/elements/onedrive/ping.js
src/test/elements/onedrivebusiness/folders.js
src/test/elements/onedrivebusiness/ping.js
src/test/elements/zendesk/ping.js

* Added `/ping API` for `onedrive, onedrivebusiness, zendesk, adobe-esign`
* Added Testcases /ping to check instance is healthy or not
* Commented few test cases in onedrivebusiness of name and extension search for /folders/contents,     since soba stories are get blocked.
[Churros](https://github.com/cloud-elements/churros/pull/1400)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540742232)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540738360)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540738672)

Enhanced Testcases for onedrive, onedrivebuiness, zendesk, adobe-esign with /ping API

---

src/test/elements/mysql/ping.js
src/test/elements/sqlserver/ping.js

Enhanced `sqlserver`, `mysql`,  and `pstgresql` with `/ping API`
* Added Test cases for /PING API for `sqlserver`, `mysql`,  and `pstgresql`.
[Soiba](https://github.com/cloud-elements/soba/pull/8099)
[Postgres_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540741012)
[sql_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540740428)
[mysql_Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197540740752)

Enhanced Testcases for sqlserver, mysql and postgresql

---

src/test/elements/sfdcdocuments/files.js
src/test/elements/sfdclibraries/files.js

* ☝️ 
* [SOBA #8141](https://github.com/cloud-elements/soba/pull/8141)
* [TA-8730](https://rally1.rallydev.com/#/144349237612d/detail/task/200484827380)
* [TA-8730](https://rally1.rallydev.com/#/144349237612d/detail/task/200484827380)

Added checks for content types in SFDC Documents and Libraries

---

src/test/elements/intacct/assets/transformations.json

* `/terms API`
##Screenshot
[Soba](https://github.com/cloud-elements/soba/pull/8175)
[Rally](https://rally1.rallydev.com/#/144349237612ud/detail/defect/199594438284)

Intacct Transformation Fix  for /terms API

---

src/test/elements/box/assets/folderTags.json
src/test/elements/box/files.js
src/test/elements/box/folders.js

* Enhanced Test cases for dropbox UR tags information for files and folders.
* Tags Info for 
`GET folders/metadata`
`PATCH folders/metadata`
`GET folders/:id/metadata`
`PATCH folders/:id/metadata`
[Soba](https://github.com/cloud-elements/soba/pull/8113)
[ClosedPR](https://github.com/cloud-elements/churros/pull/1420)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197579323248)

Test Cases for Implemented Box file and folder tags

---

src/test/elements/intacct/expense-reports.js

* Updated the where clause for /expense-reports API 
`(node:15888) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using oauth username: zoho@cloud-elements.com
info: Running tests for element: zohocrm
info: Provisioned with instance id of 158
(node:15888) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (536ms)
- docs
√ metadata (166ms)
√ transformations (11100ms)
accounts
√ should allow ping for zohocrm (192ms)
√ should allow CRUDS for /hubs/crm/accounts (5553ms)
√ should allow paginating with page and pageSize for …

Updated the where clause for /expense-reports

---

src/test/elements/servicemax/installed-products.js
src/test/elements/servicemax/order-parts.js
src/test/elements/servicemax/service-contracts.js
src/test/elements/servicemax/work-orders.js

* Fixed search by id test cases for following resources 
1.  installed-products
2.   order-parts
3.   service-contracts
4.   work-orders
For these resources the Post API response has "id" field  but the Get API model has "Id" field ,hence the existing search by id test cases were failing.
* [SOBA](https://github.com/cloud-elements/soba/pull/8170)
* #[Rally DE1013](https://rally1.rallydev.com/#/144349237612d/detail/defect/201813342260)
* #[DE1013](https://rally1.rallydev.com/#/144349237612d/detail/defect/201813342260)

Servicemax : Fixed test cases for search by id

---

src/test/elements/assets/object.definitions.json
src/test/elements/hubspot/assets/deals.json
src/test/elements/hubspot/assets/transformations.json
src/test/elements/hubspot/deals.js

* Added churros testcases for CRUDS APIs for Deals.
Please Note : An error is coming for pagination of `Activities` as there is no record present for `GET /activities`. There is no `POST /activities` as well to create new one activity. Tried from hubspot UI but unable to do so.
* [SOBA](https://github.com/cloud-elements/soba/pull/8132)
* [RALLY-#${US8502}](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/198554041816)
* Closes #${US8502}

Hubspot Marketing : Added CRUDS testcases for Deals APIs

---

src/test/elements/googledrive/files.js
src/test/elements/googledrive/folders.js

* Fixed `should allow GET for /folders/contents with orderBy modifiedDate asc`
* Added test to validate 404 for a bad path in `/files/comments`
* [SOBA](https://github.com/cloud-elements/soba/pull/8151)
* [TA8966](https://rally1.rallydev.com/#/144349237612d/detail/task/201008560348)
* [TA8966](https://rally1.rallydev.com/#/144349237612d/detail/task/201008560348)

Fixed G-Drive and added negative test

---

src/test/elements/docusign/envelopes.js

* Added Envelopes Recipients GET API: GET /envelopes/{id}/recipients
* [SOBA](https://github.com/cloud-elements/soba/pull/8018)
* [US7344](https://rally1.rallydev.com/#/144349237612d/detail/userstory/193151748320)
* [US7344](https://rally1.rallydev.com/#/144349237612d/detail/userstory/193151748320)

Docusign: Added Envelope Recipients GET API #8018

---

src/test/elements/box/index.js

* Updated folders metadata test cases to test the newly supported update of description field
* Churros report: [box_churros.txt](https://github.com/cloud-elements/churros/files/1727435/box_churros.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/8091)
* [RALLY-#DE869](https://rally1.rallydev.com/#/144349237612d/detail/defect/196709008204)
* [#DE869](https://rally1.rallydev.com/#/144349237612d/detail/defect/196709008204)

Updated folders metadata test cases to update description

---

src/test/elements/googledrive/files.js
src/test/elements/googledrive/folders.js

>GET /folders/contents 
>GET /folders/:id/contents
>GET /search
* Updated undefined check for thumbnail and mimeType for folders items
#Screen shot
[soba](https://github.com/cloud-elements/soba/pull/8143)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/198774886136)

Updated Testcases for the Google Drive fix -  null thumbnail field being returned for folder response items 

---

src/test/elements/quickbooksonprem/assets/bills.json

* Fixed `bills` object for Quickbooks Enterprise.
Churros testcases are failing for all the objects. Hence as discussed in call with Atul, fixed testcase only for `bills` now.
* [SOBA](https://github.com/cloud-elements/soba/pull/8164)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/168)
* [RALLY-#${TA9255}](https://rally1.rallydev.com/#/144349237612ud/detail/task/201561689952)  ([DE246](https://rally1.rallydev.com/#/144349237612ud/detail/defect/163928267524))
* [TA9255](https://rally1.rallydev.com/#/144349237612ud/detail/task/201561689952)  ([DE246](https://rally1.rallydev.com/#/144349237612ud/detail/defect/163928267524))

Fixed Payload for Bills object of QBE

---

src/test/elements/twiliov2/accounts.js
src/test/elements/twiliov2/addresses.js
src/test/elements/twiliov2/assets/accounts.json
src/test/elements/twiliov2/assets/addresses.json
src/test/elements/twiliov2/assets/transformations.json

* Added testcases for `/addresses` resource.
* Added testcases for `/accounts` resource.
* [SOBA](https://github.com/cloud-elements/soba/pull/8131)
* [Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042924)
* [Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042592)
* [US8506](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042924)
* [US8505](https://rally1.rallydev.com/#/144349237612d/detail/userstory/198554042592)

TwilioV2: Added Testcases for accounts and addresses api

---

src/test/elements/dropbox/assets/UpdateCustomFields.json
src/test/elements/dropbox/assets/UpdateTemplate.json
src/test/elements/dropbox/assets/customFields.json
src/test/elements/dropbox/assets/template.json
src/test/elements/dropbox/custom-fields-templates.js
src/test/elements/dropbox/custom-template-fields.js
src/test/elements/dropbox/files.js

* Added the churros test CRUDS for /custom-fields-templates/templates
* Added the churros test CUD for /files/{id}/custom-fields-templates/{templateKeyId}/custom-fields'
- Raised the DE for failing APIs [DE872](https://rally1.rallydev.com/#/144349237612d/detail/defect/194400963348?fdp=true)
* [SOBA](https://github.com/cloud-elements/soba/pull/7994)
* [RALLY-#${TA5987}](https://rally1.rallydev.com/#/144349237612d/detail/task/192341621964)
* Closes #$[US7271](https://rally1.rallydev.com/#/144349237612d/detail/userstory/192209559176)

Added the custom-template-fields APIs in Dropbox

---

src/test/elements/chargify/assets/invoices.json
src/test/elements/chargify/assets/transformations.json
src/test/elements/chargify/invoices.js

* Chargify element enhance with `/invoices` API Testcases
* Invoices API's
> `GET /invoices`
> `GET /invoices/{id}`
#Screen shot
[Soba](https://github.com/cloud-elements/soba/pull/8211)
[US8327](https://rally1.rallydev.com/#/144349237612d/detail/userstory/197894482304)

Enhanced chargify element with /invoices testcases

---

src/test/elements/sharepoint/files.js

* Sharepoint enhanced with `/revisions API` by path and id testcases.
* Revisions By Path
`files/revisions`
`files/revisions/{revisionId}`
* Revisions By Id
`files/{fileId}/revisions`
`files/{fileId}/revisions/{revisionId}`
#Screen shot
[Soba](https://github.com/cloud-elements/soba/pull/8204)
[US9381](https://rally1.rallydev.com/#/144349237612d/detail/userstory/202233375544)

Enhanced sharepoint element with /revisions API's Testcases

---

src/test/elements/shopify/metafields.js

* Fixed churros tests for metafields APIs
* [SOBA](https://github.com/cloud-elements/soba/pull/8161)
* [RALLY-DE846](https://rally1.rallydev.com/#/144349237612d/detail/defect/195599813620)
* [DE846](https://rally1.rallydev.com/#/144349237612d/detail/defect/195599813620)

Shopify : Fixed failing metafields API tests

---

src/test/elements/netsuitefinancev2/assets/currencies.json
src/test/elements/netsuitefinancev2/assets/transformations.json
src/test/elements/netsuitefinancev2/currencies.js

* Added CRUD tests for currencies object Netsuite Finance
* For GET /currencies, no CEQL query test is added as it's a limitation from vendor.
Churros Report- [NS finance churros.txt](https://github.com/cloud-elements/churros/files/1792511/NS.finance.churros.txt)
Some of the churros are failing, raised bug [DE1049](https://rally1.rallydev.com/#/144349237612ud/detail/defect/203650294104?fdp=true) for that.
* [SOBA](https://github.com/cloud-elements/soba/pull/8224)
* [RALLY-US9389](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/202236832756)

Added tests for currencies object Netsuite Finance

---

src/test/elements/bigcommerce/orders.js

* Added churros test case for the newly added GET `/orders/{id}/transactions` API on BigCommerce
(node:3044) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using api key: 6eiwidt0hc15od30a1bq7c3lp0uk15m
info: Running tests for element: bigcommerce--custom
info: Provisioned with instance id of 270
(node:3044) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (154ms)
- docs
√ metadata (175ms)
√ transformations (13195ms)
customers
√ should allow CRUDS for /hubs/ecommerce/customers (10682ms)
√ should allow GET for …

Added test cases for transactions API on BigCommerce

---

src/test/elements/hubspot/polling.js

* Added polling testcase for `Deals` object which was newly added in `Hubspot Marketing`
* [SOBA](https://github.com/cloud-elements/soba/pull/8232)
* [TA10178](https://rally1.rallydev.com/#/144349237612ud/detail/task/203957758960) ([DE1027](https://rally1.rallydev.com/#/144349237612ud/detail/defect/202696714648/tasks))
* [TA10178](https://rally1.rallydev.com/#/144349237612ud/detail/task/203957758960) ([DE1027](https://rally1.rallydev.com/#/144349237612ud/detail/defect/202696714648/tasks))

Added polling testcase for Deals in Hubspot Marketing

---

src/test/elements/dropbox/me.js
src/test/elements/dropboxbusiness/me.js
src/test/elements/dropboxbusinessv2/me.js
src/test/elements/dropboxv2/me.js

* Added `GET /me API`  Testcases for Dropbox and DropboxBusiness
* Normalized /me api across documentation hub
[Soba](https://github.com/cloud-elements/soba/pull/8286)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677248568)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/201677248816)

Enhanced  Dropbox and Dropboxbusiness /me API testcases

---

src/test/elements/chargify/customers.js

* Added ceql search test for `customers` object.
- Some of the product related test cases are failing. On further lookup it seems we can not create more products anymore. As per vendor [doc ](https://help.chargify.com/products/products-intro.html#archiving-products-coupons--components), deleting product is not supported.
* [RALLY-#DE1032](https://rally1.rallydev.com/#/144349237612ud/detail/defect/202962019264)
* Closes #DE1032

Added ceql search test for customers: Chargify

---

src/test/elements/sageone/assets/financial-settings.json
src/test/elements/sageone/financial-settings.js

* Added test cases for new resource `financial-settings` on SageOne
- `GET /financial-settings`
- `PUT /financial-settings`
* Complete report: [SageOne_churros.txt](https://github.com/cloud-elements/churros/files/1828597/SageOne_churros.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/8302)
* [RALLY-#US10286](https://rally1.rallydev.com/#/144349237612d/detail/userstory/205610401792)
* [#US10286](https://rally1.rallydev.com/#/144349237612d/detail/userstory/205610401792)

Test cases for new resource financial-settings on SageOne

---

src/test/elements/sharepoint/files.js
src/test/elements/sharepoint/folders.js

* Added Test case to Validate return parentFolderId - Gliffy Enhancements
[Soba](https://github.com/cloud-elements/soba/pull/8249)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/202233376020)

Sharepoint Gliffy enhancements - updated test cases

---

src/test/elements/onedrivev2/me.js

* Added churros for `GET /me` for `onedrivev2`
* [SOBA](https://github.com/cloud-elements/soba/pull/8245)
* [US9352](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/201677249100)
* [US9352](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/201677249100)

Onedrivev2 : Added testcase for /me API

---

src/test/elements/magentov20/categories.js
src/test/elements/magentov20/products-attribute-sets.js

fix churros tests for the following resources
* /hubs/ecommerce/categories/{id}/products
* /hubs/ecommerce/products-attribute-sets-groups
* [DE1176](https://rally1.rallydev.com/#/144349237612d/detail/defect/207566662640)

modified churros for magentov20

---

src/test/elements/dropbox/folders.js
src/test/elements/dropbox/ping.js

* Removed Dropbox `GET /folders/contents` `where` clause tests as where clause was never implemented for this endpoint and tests had been merged prematurely. 
* Adjusted `GET /ping` test to not validate a `status` field was returned since status code was used in place of populating a status field. When /ping fails a 4XX status code will be returned. 
* [RALLY-#DE828](https://rally1.rallydev.com/#/144349237612d/detail/defect/194400963348/discussion)

Dropbox tests fixes

---

src/test/elements/bullhorn/metadata.js

* Added churros for `objects/{objectName}/metaData`.
* [8284](https://github.com/cloud-elements/soba/pull/8284)
* [RALLY-#${US10234}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/204671642908)
* [US10234](https://rally1.rallydev.com/#/144349237612d/detail/userstory/204671642908)

Added metadata churros for Bullhorn

---

src/test/elements/assets/object.definitions.json
src/test/elements/maximizer/appointments.js
src/test/elements/maximizer/assets/appointments.json
src/test/elements/maximizer/assets/transformations.json

* Added /appointments API Testcases for Maximizer
[Soba](https://github.com/cloud-elements/soba/pull/8328)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/203863331304)

Enhanced maximizer with /appointments api Testcases

---

src/test/elements/autotaskhelpdesk/assets/contracts.json
src/test/elements/autotaskhelpdesk/contracts.js

* Added testcases for Autotask Helpdesk - `contracts` CRUS. There was no DELETE API mentioned in the vendor Documentation -https://www.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf
Hence DELETE is not implemented. Hence have added skip as well
* [SOBA](https://github.com/cloud-elements/soba/pull/8276)
* [US10054](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/203777846060)
* [US10054](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/203777846060)

Added testcases for contracts APIs for Autotask Helpdesk

---

src/core/oauth.js

* Now churros will be able to make an instance for QBO via Oauth2 provisioning
* However the churros are failing for some resources as `quickbooks--oauth2` in sauce.json points to `quickbooks+oauth2@cloud-elements.com` account and runs churros of key `quickbooks`. These churros are written for account `quickbooks@cloud-elements.com` for key `quickbooks` in sauce.json
Hence not fixing them as part of this story.
*  [DE1091](https://rally1.rallydev.com/#/144349237612ud/detail/defect/204816326028)

Fixed Authentication for QBO via Oauth2

---

src/test/elements/acton/assets/contacts.json
src/test/elements/acton/assets/contactsUpdate.json

* Fixed failing testcase for resource `POST /lists/{}/contacts` and `PATCH /lists/{}/contacts/{id}`
* It is observed that the fields present for the POST and PATCH payloads are all custom fields. 
* [DE1163](https://rally1.rallydev.com/#/144349237612ud/detail/defect/207151981156)

Fixed Acton churros for failing testcases

---

src/test/elements/stripe/assets/payment-methods.json
src/test/elements/stripe/balances.js

* Added GET /balances API 
* where clause not supported hence not added the test for where clause
> 
PS C:\Users\GS-1259\CE-4656\churros\finalch\churros-sauce> churros  test elements/stripe
info: Using oauth username: sk_test_HZ6dO9HizZtYuHcO8Up9kmjI
info: Running tests for element: stripe
info: Provisioned with instance id of 689
Basic tests
√ should GET /objects (171ms)
- docs
√ metadata (191ms)
error: Failed to retrieve or validate: /hubs/payment/tokens
error: Failed to retrieve or validate: /hubs/payment/payment-methods
√ transformations (18590ms)
balances
√ …

Stripe : Added GET /balances API 

---

src/test/elements/autotaskcrm/metadata.js
src/test/elements/autotaskfinance/metadata.js
src/test/elements/autotaskhelpdesk/metadata.js
src/test/elements/zohocrm/metadata.js

* Enhanced Testcases for `/objects/{objectName}/metadata API` for Autotask  Helpdesk, Finance , CRM and Zoho CRM to support customFieldsOnly 
[Soba](https://github.com/cloud-elements/soba/pull/8340)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/userstory/204382421512)

Enhanced Autotask Helpdesk, Finance, CRM and Zoho CRM - Test cases for Discovery API

---

src/test/elements/intacct/metadata.js

* Added metadata API for "billsPayments,"checkingAccounts", "CCTRANSACTION" , "EXCHANGERATEENTRY", "EXCHANGERATE","exchangeRateTypes
```
PS C:\Users\GS-1259\CE-4656\churros\finalch\churros> churros -i 666 test
info: Running tests for element: intacct
info: Provisioned with instance id of 666
error: Failed to create or validate: /instances/666/objects/bills/definit
error: Failed to create or validate: /instances/666/objects/bills/definit
error: Failed to create or validate: /instances/666/transformations/bills
error: Failed to create or validate: /instances/666/transformations/bills
Basic tests
√ should GET …
```

Added metadata API for intacct

---

src/test/elements/stripe/charges.js

* Enhanced test cases for searching for `charges` resource in stripes
* Added test cases for searching in `charges` resource.
* Churros result for `charges`.
* [SOBA](https://github.com/cloud-elements/soba/pull/8404)
* [DE1220](https://rally1.rallydev.com/#/144349237612d/detail/defect/208991134680)

Added test cases for stripe-charges where clause fields

---

src/test/platform/elements/assets/element.metadata.docs.json
src/test/platform/elements/metadata-docs.js

* Added /objects/{objectName}/docs tests
```
elements-mac112:churros ramana$ churros test platform/elements --file metadata-docs
metadata-docs
✓ should return object docs (261ms)
✓ should return object docs with custom fields when discovery is true (630ms)
✓ should return object docs with custom fields when discovery is true and basic is true (704ms)
✓ should return object docs with custom fields when discovery is true and resolveReference is true (597ms)
4 passing (5s)
````
* [US10439](https://rally1.rallydev.com/#/144349237612d/detail/userstory/206385306616)

Added /objects/{objectName}/docs tests

---

src/test/elements/sfdcservicecloud/assets/models_activities_post.json
src/test/elements/sfdcservicecloud/assets/models_contacts_post.json
src/test/elements/sfdcservicecloud/assets/models_incidents_post.json
src/test/elements/sfdcservicecloud/assets/models_task_post.json

Added SFDC Service Cloud model Payloads for:
- `Contacts` 
(sub-resource - Tasks, Events)
- `Incidents` mapped to `Case` on vendor Side
(sub-resource - Tasks, Events)<br/><br/>
Note: Payloads for Tasks, Events in both `Contacts` and `Incidents` is the same. Thus they have been name as *models_task_post* and *models_activities_post* respectively.
* [SOBA_model_PR](https://github.com/cloud-elements/soba/pull/8253)

Sales Force Service Cloud Model Payloads

---

src/test/elements/sageone/assets/bankAccount.json
src/test/elements/sageone/assets/ledgerAccount.json
src/test/elements/sageone/bank-accounts.js
src/test/elements/sageone/ledger-accounts.js

* Enhanced test cases for CUD for `bank-accounts` and `ledger-accounts`.
* Churros result for `bank-accounts` and `ledger-accounts`.
* [SOBA](https://github.com/cloud-elements/soba/pull/8352)
* [SOBA](https://github.com/cloud-elements/soba/pull/8406)
* #[US10532](https://rally1.rallydev.com/#/144349237612d/detail/userstory/207618302300)
* #[US10656](https://rally1.rallydev.com/#/144349237612d/detail/userstory/209157374828)

Added test case for CUD /bank-accounts and /ledger-account

---

src/test/elements/marketo/assets/custom-objects.json
src/test/elements/marketo/custom-objects.js

Following APIs are supported for CustomObjects : 
- `GET /custom-objects`
- `GET /custom-objects/{customObjectName}/custom-fields` 
- `GET /custom-objects/{customObjectName}/custom-fields-templates` 
- `POST /custom-objects/{customObjectName}/custom-fields` 
- `GET /custom-objects/{customObjectName}/custom-fields/{id}` 
- `PATCH /custom-objects/{customObjectName}/custom-fields/{id}` 
- `DELETE /custom-objects/{customObjectName}/custom-fields/{id}` 
Please note that `afrinCustom_c` is a custom-object and `dedupeFieldafrin` is a custom-field, defined only via Marketo UI.
* [SOBA](https://github.com/cloud-elements/soba/pull/8344)
* [US10078](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/203863314560)
* [US10553](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/207 …

Marketo : Added new APIs for Custom-objects 

---

src/test/elements/sfdcdocuments/files.js

* SFDC Documents enhanced with `/revisions API` Test cases by path and id.
* Revisions By Path
`files/revisions`
`files/revisions/{revisionId}`
* Revisions By Id
`files/{fileId}/revisions`
`files/{fileId}/revisions/{revisionId}`
#Screen shot
[Soba](https://github.com/cloud-elements/soba/pull/8422)
[US9381](https://rally1.rallydev.com/#/144349237612d/detail/userstory/207342019876)

Enhanced /sfdcdocuments with /revisions API testcases

---

src/test/elements/sugarcrmv2/assets/metadata.json
src/test/elements/sugarcrmv2/metadata.js

* Added test for GET /object/{objectname}/metadata API.
[churros sugarcrm](https://github.com/cloud-elements/churros/files/1894638/churros.updated.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/8385)
* [RALLY-#US10441](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/206386316544)

Added metadata test for SugarCRMV2

---

src/test/elements/marketo/metadata.js
src/test/elements/marketo/objects.js

* Added Testcases for /objects/{objectName}/metadata for Marketo 
[Soba](https://github.com/cloud-elements/soba/pull/8431)
[Rally](https://rally1.rallydev.com/#/144349237612d/detail/defect/209422551924)

Enhanced Marketo with GET /objects/{objectName}/metadata API Testcases

---

src/test/elements/sfdc/assets/objects.json
src/test/elements/sfdc/metadata.js

* When the `GET /objects/{objectName}/metadata` API is used for VDRs, the metadata for only those fields that are mapped in the VDR should be returned
* [SOBA PR 8462](https://github.com/cloud-elements/soba/pull/8462)
* [DE1318](https://rally1.rallydev.com/#/144349238268d/detail/defect/211748346892)
* Closes #DE1318

Tests to ensure that VDR metadata includes only mapped fields

---

src/test/elements/stripe/charges.js
src/test/elements/stripe/orders.js

* Added test for where clause to search on nested fields for `orders` and `charges`
* [SOBA](https://github.com/cloud-elements/soba/pull/8425)
* [RALLY-#DE1211](https://rally1.rallydev.com/#/144349237612d/detail/defect/208699181044)
* [DE1211](https://rally1.rallydev.com/#/144349237612d/detail/defect/208699181044)

Stripe : Added test for where clause on nested fields

---

src/test/elements/hubspot/assets/timelineeventproperties.json
src/test/elements/hubspot/assets/timelineevents.json
src/test/elements/hubspot/assets/timelineeventtypes.json
src/test/elements/hubspot/timeline-event-types.js

* Added tests for timeline resource.
- Churros Report - [hubspot churros marketing.txt](https://github.com/cloud-elements/churros/files/1884257/hubspot.churros.marketing.txt) . Some metadata tests are failing. Raised [defect ](https://rally1.rallydev.com/#/144349237612ud/detail/defect/211046505152?fdp=true) for that.
* [SOBA](https://github.com/cloud-elements/soba/pull/8435)
* [RALLY-#US10495](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/207345899004)
* Closes #[US10495](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/207345899004)

Added tests for timeline resource for Hubspot Marketing

---

src/test/elements/oraclesalescloud/assets/models_opportunities_patch.json
src/test/elements/oraclesalescloud/assets/models_opportunities_post.json

- Updated payloads for Oracle Sales Cloud - opportunities resource 
- There are few fields for which the API gives error similar to following , so they are not put in the 
payload (fields like `DeleteFlag ,DescriptionText ,EmailAddress,MaximumDaysInStage,PartyName1 ,PartyUniqueName1 ,PhaseCd ,PrimaryContactFormattedPhoneNumber,PrimaryContactPartyName`)
{
"requestId": "5ad498d0e4b0649d09e32afa",
"message": "Request failed",
"providerMessage": "Attribute AverageDaysAtStage in view object Opportunity cannot be set."
} 
- `PrimaryRevenueId` gets posted without error but   GET and GET by id API fails for that posted record id. 
So its been removed from the payload.
PFA the screenshot the python script result with these payloads
* [RALLY-#{DE1234}](https://rally1.rallydev.com/#/144349237612ud/de …

Oracle Sales Cloud:Post and Patch request payload for opportunities

---

src/test/elements/bullhorn/assets/job-orders.json
src/test/elements/bullhorn/job-orders.js

* Added testcase for Job-orders CRUDS.
* [SOBA](https://github.com/cloud-elements/soba/pull/8480)
* [RALLY-#${US10847}](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/210887131944)
* [US10847](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/210887131944)

Bullhorn : Added testcase for job-orders APIs

---

src/test/elements/chargify/product-families.js
src/test/elements/chargify/products.js
src/test/elements/chargify/subscriptions.js

* Skipped POST tests for /subscriptions and /product-families/products as deleting subscriptions and products archives the items instead of deleting.
* Removed POST /products from `products` test suite as no API available on CE platform.
* Vendor doc is [here](https://reference.chargify.com/v1/basics/introduction).
* Test for GET /products is removed as no vendor API is present for this. Raised a bug [DE1389 ](https://rally1.rallydev.com/#/144349237612ud/detail/defect/213671799188) to update element for the same.
Report- [chargify churros.txt](https://github.com/cloud-elements/churros/files/1918793/chargify.churros.txt)
* [RALLY-#DE1292](https://rally1.rallydev.com/#/144349237612ud/detail/defect/211017348380)
* Closes #[DE1292](https://rally1.rallydev.com/#/144349237612ud/detail/defect/211 …

Updated tests for Chargify

---

src/test/elements/connectwisecrm/incidents.js
src/test/elements/connectwisehd/incidents.js

* Added testcase for `GET /incidents/{id}/comments` for `ConnectWise` and `ConnectWise CRM`
a) ConnectWise 
b) ConnectWise CRM
* [SOBA](https://github.com/cloud-elements/soba/pull/8530)
* [US11022](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/212708562068)
* [US11022](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/212708562068)

Added churros for GET incidents/{id}/comments connectwisehd and connectwisecrm

---

src/test/elements/acton/lists.js

* Added Testcase related to `/objects/{listsContacts}/metadata` to dynamically generate metadata based on listId.
[Soba](https://github.com/cloud-elements/soba/pull/8484)
[DE1153](https://rally1.rallydev.com/#/144349237612d/detail/defect/206739677860)
[DE1152](https://rally1.rallydev.com/#/144349237612d/detail/defect/206738611664)

Enhanced - Acton  with /object/listsContacts/metadata test cases

---

src/test/platform/changemanagement/assets/elementmodel.json
src/test/platform/changemanagement/pull-requests.js

* Added a test to validate that a resource is being associated to a model when the model diff is hydrated on a pull request
* [SOBA](https://github.com/cloud-elements/soba/pull/8442)

Validating model diff on pull request

---

src/test/platform/changemanagement/pull-requests.js

* Added test for POST `/pull-requests/{id}/qaEntity` and PUT `/pull-requests/{id}` with the payload set to `{qaApproved: true}`

Tests to validate a QA user can clone and mark a pull request QAed

---

src/test/elements/assets/object.definitions.json
src/test/elements/intacct/assets/creditMemos.json
src/test/elements/intacct/assets/customers.json
src/test/elements/intacct/assets/debitMemos.json
src/test/elements/intacct/assets/deposits.json
src/test/elements/intacct/assets/expense-report-patch.json
src/test/elements/intacct/assets/expense-reports.json
src/test/elements/intacct/assets/invoices.json
src/test/elements/intacct/assets/sales-orders.json
src/test/elements/intacct/assets/salesReceipts.json
src/test/elements/intacct/assets/transformations.json
src/test/elements/intacct/bills.js
src/test/elements/intacct/contracts.js
src/test/elements/intacct/credit-memos.js
src/test/elements/intacct/debit-memos.js
src/test/elements/intacct/deposits.js
src/test/elements/intacct/sales-receipts.js
src/test/elements/intacct/vouchers.js

* Added churros for credit-memos, debit-memos, deposits and sales-receipts APIs 
* For contracts object we dont have permission hence it is failing
*  Sales-order API is failing on snapshot and staging also, not have correct values in the payload
> Churros initialization successful!
PS C:\Users\GS-1259\CE-4656\churros\finalch\churros-sauce> churros test elements/intacct
info: Running tests for element: intacct
info: Provisioned with instance id of 817
Basic tests
√ should GET /objects (457ms)
- docs
√ metadata (489ms)
error: Failed to retrieve or validate: /hubs/finance/attachments
error: Failed to retrieve or validate: /hubs/finance/contracts
1) transformations
- should not allow …

Intacct: Added churros for missing endpoints

---

src/test/elements/assets/object.definitions.json
src/test/elements/netsuiteerpv2/assets/cash-sales.json
src/test/elements/netsuiteerpv2/assets/transformations.json
src/test/elements/netsuiteerpv2/cash-sales.js

* Added a new resource  `cash-sales` to the Netsuite ERP v2 element.
* Added Churros test and payload for `cash-sales` resource
* Added a new resource  `cash-sales` to the Netsuite ERP v2 element and added standard modes.
* Added Churros test and payload for `cash-sales` resource
* Vendor doc => http://www.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2016_2/schema/record/cashsale.html 
* NetSuite docs => https://system.netsuite.com/app/help/helpcenter.nl?topic=EDIT_TRAN_CASHSALE
- Churros Test:
* [SOBA](https://github.com/cloud-elements/soba/pull/8576)
* [RALLY-#${US11279}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214543983880)
* [US11279](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214543983880)

Netsuite ERP V2 : Added Churros test and payload for cash-sales resource

---

src/test/elements/hubspotcrm/contacts.js
src/test/elements/hubspotcrm/pipelines.js

* Updated test cases for `GET /contacts/{contactId}/activities` 
(node:26004) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using oauth username: developer@cloud-elements.com
info: Using api key: da5693c8-48d8-4a54-90b0-9e83eb76a6fc
info: Running tests for element: hubspotcrm
Trying the portal ID: 3919835
info: Provisioned with instance id of 449
(node:26004) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (234ms)
- docs
√ metadata (149ms)
√ transformations (5231ms)
accounts
√ should allow paginating with page and …

Updated test cases for GET /contacts/{contactId}/activities

---

src/test/elements/docusign/envelopes.js

* Docusign - Added test cases for
`/envelopes/{id}/documents/{documentId}`
[soba](https://github.com/cloud-elements/soba/pull/8579)
[US11535](https://rally1.rallydev.com/#/144349237612d/detail/userstory/216064319720)

Docusign - Enhanced with /envelopes/{id}/documents/{documentId} Testcases

---

src/test/elements/eloqua/objectMetadata.js

* Removed customFields test cases for `account` object from objectMetadata test suite, because account object doesn't return any customFields in response and also doesn't specify anything about `customField:true/false`.
```
PS C:\Users\gs-1108\Documents\GitHub\churros> churros test elements/eloqua
(node:16448) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using user: pore@gslab.com
info: Using oauth username: Atul.Barve
info: Using api key: f4ae3e0d-e5eb-4d44-825d-21cccf81a6b7
info: Running tests for element: eloqua
info: Provisioned with instance id of 511
(node:16448) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET …
```

Eloqua: Removed customFields test cases for account object

---

src/test/elements/sfdc/assets/objects.json
src/test/elements/sfdc/metadata.js

* The `GET /objects/{objectName}/metadata` API when used for VDRs now returns nested VDR fields
* https://github.com/cloud-elements/soba/pull/8631
* [RALLY-#US11204](https://rally1.rallydev.com/#/144349238268d/detail/userstory/213580848164)
* Closes [US11204](https://rally1.rallydev.com/#/144349238268d/detail/userstory/213580848164)

Added an integration test for metadata for a VDR with a nested object

---

src/test/elements/onedrivev2/files.js

* OneDriveV2 Updated Test cases to check cloudElementsLink property 
`files/id/links`
`files/links`
[Soba](https://github.com/cloud-elements/soba/pull/8617)
[DE1450](https://rally1.rallydev.com/#/144349237612d/detail/defect/215371686920)

OneDrive v2 - Updated Test cases for cloudElementsLink not populatingfrom "/files/{id}/links"

---

src/test/elements/chargify/product-families.js

* Added  testcase for `GET /product-families/{productFamilyId}/products`
- For the failing churros testcase a bug was raised [DE1575](https://rally1.rallydev.com/#/144349237612d/detail/defect/218190606812)
* [SOBA](https://github.com/cloud-elements/soba/pull/8636)
*  [DE1389](https://rally1.rallydev.com/#/144349237612d/detail/defect/213671799188)

Updated product-families testcase

---

src/test/elements/evernote/files.js

* Evernote Added `/revisions API` Testcases
[Soba](https://github.com/cloud-elements/soba/pull/8657)
[US10699](https://rally1.rallydev.com/#/144349237612d/detail/userstory/209348138184)

Evernote enhanced with /revisions API Testcases

---

src/test/elements/eloqua/campaigns.js
src/test/elements/eloqua/custom-objects.js

* Updated the test-case  for PUT campaigns and custom-objects
* We don't need to pass ` id`  field in body parameter for PUT campaigns and custom-objects, now it will take `id` from path parameter. 
> 
PS C:\Users\GS-1259\CE-4656\churros\finalch\churros> churros -i 927 test elements/eloqua
info: Using oauth username: Atul.Barve
info: Using api key: f4ae3e0d-e5eb-4d44-825d-21cccf81a6b7
info: Running tests for element: eloqua
info: Provisioned with instance id of 927
Basic tests
√ should GET /objects (2906ms)
- docs
√ metadata (548ms)
√ transformations (18953ms)
accounts
√ should allow CRUDS for /hubs/marketing/accounts (23225ms)
√ should …

Eloqua: Updated the testcase for PUT campaigns and custom-objects 

---

src/test/elements/smartrecruiters/assets/transformations.json
src/test/elements/smartrecruiters/users.js

* Added churros  GET /users/:id API
* [SOBA](https://github.com/cloud-elements/soba/pull/8632)
* [RALLY-#${US11686}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/217731463656)
* Closes [US11686](https://rally1.rallydev.com/#/144349237612d/detail/userstory/217731463656)

Smartrecruiters : Added churros for GET /users/:id API

---

src/test/elements/shopify/metadata.js

* Added integration test for the shopify metadata API
* https://github.com/cloud-elements/soba/pull/8649
* [RALLY-#US11815](https://rally1.rallydev.com/#/144349238268d/detail/userstory/218785569300)
* Closes [#US11815](https://rally1.rallydev.com/#/144349238268d/detail/userstory/218785569300)

Added integration test for the shopify metadata API

---

src/test/elements/docusign/assets/envelopes.documentsNew.json
src/test/elements/docusign/assets/envelopes.patchDocumentNew.json
src/test/elements/docusign/assets/model_envelopedocuments_patch.json
src/test/elements/docusign/assets/model_envelopedocuments_put.json
src/test/elements/docusign/assets/model_envelopes_post.json
src/test/elements/docusign/envelopes.js

* Added testcase for `PUT /envelopes/{id}/documents` and `PATCH /envelopes/{id}/documents/{documentId}`.
* [SOBA](https://github.com/cloud-elements/soba/pull/8678)
* [DE1639](https://rally1.rallydev.com/#/144349237612d/detail/defect/219372907756)

Updated Docusign envelopes testcase

---

src/test/elements/googledrive/assets/folders.json
src/test/elements/googledrive/assets/quotefolders.json
src/test/elements/googledrive/folders.js

* Google Drive - Updated Test cases to support Quote and Backslash in FolderName
[Soba](https://github.com/cloud-elements/soba/pull/8610)
[DE1438](https://rally1.rallydev.com/#/144349237612d/detail/defect/214838047168)

GoogleDrive - Updated testcases to support Quote and Backslash in folder name

---

src/test/elements/chargify/objectMetadata.js

* Fixed churros for failing test case of objectMetadata of subscriptions.
* The test was failing because after transformation only `Id` field is returned which is not a custom field and hence an empty response is returned. It was being compared to a non-empty response body.
* One test of transformation is failing on Basic Tests that churros runs but no helpful information available to debug that.
* [DE1575](https://rally1.rallydev.com/#/144349237612d/detail/defect/218190606812)

Chargify - Fixed failing test case of metadata

---

src/test/elements/hubspot/accounts.js
src/test/elements/hubspot/assets/accountsProperties.json
src/test/elements/hubspot/assets/accountsPropertygroups.json

* Added CRUDS for /accounts/properties.
* Added CUDS for /accounts/propertygroups.
- Report - [hubspot marketing churros](https://github.com/cloud-elements/churros/files/2013003/hubspot.marketing.churros.txt)
Some of the churros are failing. Raised [DE1708 ](https://rally1.rallydev.com/#/144349237612ud/detail/defect/221095074132?fdp=true) for that.
* [SOBA]()
* [RALLY-#US11907](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/219810905356)
* Closes [US11907](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/219810905356)

Added test for accountsProperties and accountsPropertygroups: Hubspot Marketing

---

src/test/platform/formulas/assets/formulas/complex-to-upgrade.json
src/test/platform/formulas/formulas.js

* When a formula was upgraded to v3, empty step property values, or those with just spaces in the string were being translated to "${}", which is invalid.
* Fixed this issue in `soba` and made the corresponding change in `churros` to test for this fix.
* https://github.com/cloud-elements/soba/pull/8753
* [RALLY-#DE1478](https://rally1.rallydev.com/#/144349238268d/detail/defect/216031226988)
* Closes #[DE1478](https://rally1.rallydev.com/#/144349238268d/detail/defect/216031226988)

Updated the formula upgrade to v3 integration to match a soba change

---

src/test/elements/infusionsoftmarketing/accounts.js
src/test/elements/infusionsoftmarketing/leads.js

Added testcases for following APIs 
- `GET /accounts`
- `GET /leads`
* [SOBA](https://github.com/cloud-elements/soba/pull/8679)
* [US11826](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/218877781528)
* [US11827](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/218877781936)
* [US11826](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/218877781528)
* [US11827](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/218877781936)

InfusionsoftMarketing : Updated testcases for Leads and Accounts

---

src/test/elements/magentov20/categories.js
src/test/elements/magentov20/products-attribute-sets.js
src/test/elements/magentov20/shipments.js

* Fixed failing test case for `shipments`, `categories` and `products-attribute-sets`.
* [DE1789](https://rally1.rallydev.com/#/144349237612d/detail/defect/223577141408)

Magento V2 : Fix failing churros tests

---

src/test/elements/hootsuite/interactions.js

* Added churros test for `interactions` to check for GET API response and pagination
[HootsuiteChurros.txt](https://github.com/cloud-elements/churros/files/2044476/HootsuiteChurros.txt)
* [SOBA](https://github.com/cloud-elements/soba/pull/8782)
* [RALLY-#${DE1790}](https://rally1.rallydev.com/#/144349237612d/detail/defect/223623145816)
* [DE1790](https://rally1.rallydev.com/#/144349237612d/detail/defect/223623145816)
Closed duplicate PR [https://github.com/cloud-elements/churros/pull/1583](https://github.com/cloud-elements/churros/pull/1583)

Hootsuite : Added churros test for interactions

---

src/test/elements/stripe/assets/orders.json
src/test/elements/stripe/assets/subscriptions.json
src/test/elements/stripe/assets/transformations.json
src/test/elements/stripe/subscriptions.js

* Added tests for POST, PATCH and DELETE subscription APIs
* Fixed churros errors for `orders`
[StripeChurros.txt](https://github.com/cloud-elements/churros/files/2053792/StripeChurros.txt)
* [RALLY-#${DE1777}](https://rally1.rallydev.com/#/144349237612d/detail/defect/223133123660)
* [DE1777](https://rally1.rallydev.com/#/144349237612d/detail/defect/223133123660)

Stripe : Added tests for POST, PATCH and DELETE subscription APIs

---

src/test/elements/facebookleadads/leads.js

* Added test case for `GET /forms/{formId}/leads` for Facebook Lead Ads.
*  [SOBA](https://github.com/cloud-elements/soba/pull/8826)
*  [US12311](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/225398556000)
*   [US12311](https://rally1.rallydev.com/#/144349237612ud/detail/userstory/225398556000)

Added testcase for GET /forms/{formId}/leads in Facebook Lead Ads

---

src/test/elements/magentov20/invoices.js

* Added churros test for capture and void endpoints for `invoices`
* The test are skipped since it requires an `invoice` to be set to `Authorize only` payment method, which can be done through Magento UI
* Churros for complete element is failing. [DE1913](https://rally1.rallydev.com/#/144349237612d/detail/defect/227844434644?fdp=true)
* [SOBA](https://github.com/cloud-elements/soba/pull/8853)
* [RALLY-#${US11824}]https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877926500)
* [US11824](https://rally1.rallydev.com/#/144349237612d/detail/userstory/218877926500)

Added test cases for void and capture invoices APIs on MagentoV2

---

src/test/elements/marketo/assets/leads.json
src/test/elements/marketo/leads.js

* Added Test suite for `/leads` resource
- GET `/leads`
- POST `/leads`
- DELETE `/leads/{id}`
- GET `/leads/{id}`
- PATCH `/leads/{id}`
- POST `/leads/{leadId}/interactions`
- POST `/leads/{leadId}/merge`
* [SOBA](https://github.com/cloud-elements/soba/pull/8567)
* [DE1472](https://rally1.rallydev.com/#/144349237612d/detail/defect/215750227576)
* [US11328](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214796117868)
* [DE1472](https://rally1.rallydev.com/#/144349237612d/detail/defect/215750227576)
* [US11328](https://rally1.rallydev.com/#/144349237612d/detail/userstory/214796117868)

Marketo: Added leads test suite

---

src/test/elements/dropboxv2/assets/revokelinkaccess.json
src/test/elements/dropboxv2/files.js

* Added test case for `/files/revoke-link-access` endpoint 
* Users can now revoke the shared links for files through the element API docs
* [SOBA](https://github.com/cloud-elements/soba/pull/8882)
* [RALLY-#${US12546}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/227740091500)
* [US12546](https://rally1.rallydev.com/#/144349237612d/detail/userstory/227740091500)

Dropbox v2: Added test case for /files/revoke-link-access endpoint 

---

src/test/elements/intacct/assets/invoices.json

* Added `billto.contactname` and `shipto.contactname` in invoices payload of `Intacct` element.
Please note : 
Contract API is failing because of Permission issue of churros account credentials. However it would work for other creds.
* [SOBA](https://github.com/cloud-elements/soba/pull/8819)
* [DE1857](https://rally1.rallydev.com/#/144349237612ud/detail/defect/225819399664)
* [DE1857](https://rally1.rallydev.com/#/144349237612ud/detail/defect/225819399664)

Intacct : Added new fields for POST /invoices

---

src/test/elements/magentov20/metadata.js
src/test/elements/netsuitefinancev2/metadata.js

* Added a test for the `Helium` (2.0) version of the `GET /objects` API for the Netsuite Finance v2 and Magento V2 elements.
* Added a test to retrieve an element instance's objects via the `Helium` API during element instantiation for the Netsuite Finance v2 and Magento V2 elements.
* https://github.com/cloud-elements/soba/pull/8891
* [RALLY-#US12336](https://rally1.rallydev.com/#/144349238268d/detail/userstory/225707181892)
* Closes #[US12336](https://rally1.rallydev.com/#/144349238268d/detail/userstory/225707181892)

Added tests for the Helium version of the GET /objects API and invoking this during element instance instantiation

---

src/test/elements/maximizer/addressbook-entries.js
src/test/elements/maximizer/assets/documents.json
src/test/elements/maximizer/assets/notes.json

* Maximizer -  Added Test cases for `Notes` and `Documents` API
[Soba](https://github.com/cloud-elements/soba/pull/8714)
[US12347](https://rally1.rallydev.com/#/144349237612d/detail/userstory/225943888616)

Maximizer Enhanced with Notes and Documents API

---

src/test/elements/mailjet/assets/transformations.json
src/test/elements/mailjet/messages.js
src/test/elements/sendgrid/messages.js

* Remove ce_message_log table 
[Soba](https://github.com/cloud-elements/soba/pull/8771)
[US11891](https://rally1.rallydev.com/#/144349237612d/detail/userstory/219740683616)

Drop ce_message_log  - Updated Test cases

---

src/test/elements/netsuiteerpv2/assets/credit-memos.json
src/test/elements/netsuiteerpv2/assets/states.json

* Fixed failing testcases related to `/credit-memos` and `/states` API's
* Fixed failing testcases for `/location` API's by cleaning up locations from UI
```
PS C:\Users\gs-1108\Documents\GitHub\churros> churros test elements/netsuiteerpv2
(node:24156) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using url: https://staging.cloud-elements.com
info: Using user: abhay.pore@gslab.com
info: Running tests for element: netsuiteerpv2
info: Provisioned with instance id of 100084
(node:24156) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (1167ms)
- docs
√ metadata (1107ms)
error: Failed to retrieve or validate: /hubs/erp/custom-records
√ transformations …
```

NetsuiteERPv2: Fixed churros failing test cases

---

src/test/elements/servicenow/agents.js
src/test/elements/servicenow/assets/submit_producer.json
src/test/elements/servicenow/contacts.js
src/test/elements/servicenow/items.js
src/test/elements/servicenowoauth/agents.js
src/test/elements/servicenowoauth/assets/submit_producer.json
src/test/elements/servicenowoauth/contacts.js
src/test/elements/servicenowoauth/items.js

* Added test cases in ServiceNow and ServiceNowOAuth for following APIs : 
- `GET /items`
- `POST /items/{sys_id}/submit_producer`
* Modified test cases in ServiceNow and ServiceNowOAuth for following APIs:
- `PATCH /agents/{id}`
- `PATCH /contacts/{id}`
- Payload for `POST /items/{sys_id}/submit_producer` is item specific. So have hard-coded the sys_id of item in churros test case.
Applicable churros are passing
- For ServiceNow:
- For ServiceNowOAuth:
* [SOBA](https://github.com/cloud-elements/soba/pull/8861)
* [US12351](https://rally1.rallydev.com/#/144349237612d/detail/userstory/225944455852)
* [US12351](https://rally1.rallydev.com/#/144349237612d/detail/userstory/225944455852)

ServiceNow and ServiceNowOAuth: Added new test cases for /items

---

src/test/elements/netsuitecrmv2/accounts.js
src/test/elements/netsuitecrmv2/activities.js
src/test/elements/netsuitecrmv2/contacts.js
src/test/elements/netsuitecrmv2/folders.js
src/test/elements/netsuitecrmv2/leads.js
src/test/elements/netsuitecrmv2/opportunities.js
src/test/elements/netsuitecrmv2/prospects.js

* Enhanced test cases for validating the where clause with IN operator
* We can query for objects like: `where=internalId in (1,2,3,4,45)`  - This will return all the records of the object whose `internalId` match with any of the Ids provided. If some of the provided ids are invalid, the request is still processed for the valid Ids.
* `where` clause is supported in following resources:
`accounts`
`activities`
`contacts`
`folders`
`leads`
`opportunities`
`prospects`
* Churros
To test my changes I have ran test cases for only supported objects.
* [SOBA](https://github.com/cloud-elements/soba/pull/8926)
* [RALLY-#${US12539}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/227735062352)
* Closes #${US12539}

Netsuite CRM : Enhanced test cases for validating the where clause with IN operator

---

src/test/elements/dropbox/files.js
src/test/elements/dropboxv2/assets/revokelinkaccess.json
src/test/elements/dropboxv2/files.js

* Added test cases for DELETE - `files/links` and `files/{id}/links`
* [SOBA](https://github.com/cloud-elements/soba/pull/8970)
* [RALLY-#DE1992](https://rally1.rallydev.com/#/144349237612d/detail/defect/230993131944)
* Closes #[DE1992](https://rally1.rallydev.com/#/144349237612d/detail/defect/230993131944)

Dropbox : Added test cases for DELETE - `files/links` and `files/{id}/links`

---

src/test/elements/sharepoint/files.js
src/test/elements/sharepoint/folders.js
src/test/elements/sharepoint/search.js

* Now included `subsite` as a header in existing testcases for `/files` and `/folders` resources
* [SOBA](https://github.com/cloud-elements/soba/pull/8989)
* [RALLY-#${DE2013}](https://rally1.rallydev.com/#/144349237612d/detail/defect/232550823596)
* [DE2013](https://rally1.rallydev.com/#/144349237612d/detail/defect/232550823596)

Sharepoint: Included subsite header in testcases for /files and /folders 

---

src/core/oauth.js
src/test/elements/assets/object.definitions.json
src/test/elements/zohocrmv2/accounts.js
src/test/elements/zohocrmv2/activities-calls.js
src/test/elements/zohocrmv2/activities-events.js
src/test/elements/zohocrmv2/assets/accounts.json
src/test/elements/zohocrmv2/assets/activities-calls.json
src/test/elements/zohocrmv2/assets/activities-events.json
src/test/elements/zohocrmv2/assets/campaigns.json
src/test/elements/zohocrmv2/assets/cases.json
src/test/elements/zohocrmv2/assets/contacts.json
src/test/elements/zohocrmv2/assets/leads.json
src/test/elements/zohocrmv2/assets/notes.json
src/test/elements/zohocrmv2/assets/opportunities.json
src/test/elements/zohocrmv2/assets/products.json
src/test/elements/zohocrmv2/assets/tasks.json
src/test/elements/zohocrmv2/assets/transformations.json
src/test/elements/zohocrmv2/campaigns.js
src/test/elements/zohocrmv2/cases.js
src/test/elements/zohocrmv2/contacts.js
src/test/elements/zohocrmv2/leads.js
src/test/elements/zohocrmv2/opportunities.js
src/test/elements/zohocrmv2/products.js
src/test/elements/zohocrmv2/tasks.js
src/test/elements/zohocrmv2/users.js

* Added test cases for following resources are added:
- accounts
- account notes
- campaigns
- contacts
- contact notes
- activities-calls
- activities-events
- cases
- leads
- lead notes
- opportunities
- opportunity notes
- products
- tasks
- users
PS C:\Git\churros> churros test elements/zohocrmv2
(node:12640) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using oauth username: zoho@cloud-elements.com
info: Using api key: 1000.OQED8XTSGYQ608895COSTV7639Q25R
info: Running tests for element: zohocrmv2
error: Failed to create or validate: /instances
error: Failed to create an instance of zohocrmv2
error: Failed to initialize element: Error: AssertionError …

Added churros test cases for the newly added ZohoCRM V2 element

---

src/test/elements/jira/groups.js

* Added churros tests for newly added `groups` APIs
* For API `GET /groups/{groupname}`, 'groupname' is path parameter for CE and query parameter for vendor. Thus I have not used test.should.supportSr() 
* [SOBA](https://github.com/cloud-elements/soba/pull/9002)
* [RALLY-#${DE2015}](https://rally1.rallydev.com/#/144349237612d/detail/defect/231549189776)
* [DE2015](https://rally1.rallydev.com/#/144349237612d/detail/defect/231549189776)

Jira : Added tests for 'groups' APIs

---

src/test/elements/facebooksocial/search.js
src/test/elements/facebooksocial/status.js
src/test/elements/facebooksocial/user.js

* As we have migrated to 3.0 API and deprecated APIs has been removed from the Facebook element, removed churros tests for deprecated APIs
* Churros instance creation is failing as of now because I'm unable to set the redirect uri as the app is under review.
* [SOBA](https://github.com/cloud-elements/soba/pull/8998)
* [RALLY-#${US12232](https://rally1.rallydev.com/#/144349237612d/detail/userstory/223891389748)
* [US12232](https://rally1.rallydev.com/#/144349237612d/detail/userstory/223891389748)

Facebook : Removed tests for deprecated APIs

---

src/test/elements/sfdc/bulk.js
src/test/elements/sfdc/metadata.js

* Fixed failing tests for `bulk` and `metadata` objects.
* Removed hardcoded names in bulk download query test.
- Report- [sfdc churros.txt](https://github.com/cloud-elements/churros/files/2204692/sfdc.churros.txt)
Churros are run on two different accounts as API limit was exhausted for first Salesforce account
* [RALLY-DE2149](https://rally1.rallydev.com/#/144349237612ud/detail/defect/238018763604?fdp=true)
* [DE2149](https://rally1.rallydev.com/#/144349237612ud/detail/defect/238018763604?fdp=true)

SFDC: Fixed failing churros tests

---

src/test/elements/slack/files.js

* Added test for /files/{fileId}/contents API.
* Pagination test is failing for which [DE2151](https://rally1.rallydev.com/#/144349237612d/detail/defect/238399140816) is already raised.
* [SOBA](https://github.com/cloud-elements/soba/pull/9059)
* [RALLY-US13236](https://rally1.rallydev.com/#/144349237612d/detail/userstory/239219008916)
* [US13236](https://rally1.rallydev.com/#/144349237612d/detail/userstory/239219008916)

Added test for /contents

---

src/test/elements/slack/channels.js

* Added ceql test for GET channels.
- Report - [slack churros.txt](https://github.com/cloud-elements/churros/files/2205325/slack.churros.txt)
-Raised [DE ](https://rally1.rallydev.com/#/144349237612ud/detail/defect/238399140816?fdp=true)for failing tests.
* [SOBA](https://github.com/cloud-elements/soba/pull/9043)
* [RALLY-#DE2110](https://rally1.rallydev.com/#/144349237612ud/detail/defect/236266830044)
* Closes [#DE2110](https://rally1.rallydev.com/#/144349237612ud/detail/defect/236266830044)

Slack: Added ceql test for GET channels

---

src/test/elements/jira/assets/projects.json
src/test/elements/jira/incidentTypes.js

* Removed `where` clause from test cases, as vendor doesn't supports where clause from `/incident-types` API
```
PS C:\Users\gs-1108\Documents\GitHub\churros> churros test elements/jira
(node:14656) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using url: https://staging.cloud-elements.com
info: Using user: abhay.pore@gslab.com
info: Using oauth username: jiradev
info: Running tests for element: jira
info: Provisioned with instance id of 103432
(node:14656) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (1054ms)
- docs
√ metadata (1670ms)
√ transformations (18339ms)
agents
√ should allow get for …
```

Jira: Removed where clause from test cases

---

src/test/elements/stripe/assets/capture.json
src/test/elements/stripe/charges.js

* Added payload for /charges/{id}/capture test cases.
```
PS C:\Users\gs-1108\Documents\GitHub\churros> churros --instance 481 test elements/stripe
(node:21740) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using user: pore@gslab.com
info: Using oauth username: sk_test_HZ6dO9HizZtYuHcO8Up9kmjI
info: Running tests for element: stripe
info: Provisioned with instance id of 481
error: Failed to create or validate: /instances/481/objects/charges/definitions
error: Failed to create or validate: /instances/481/objects/charges/definitions
error: Failed to create or validate: /instances/481/transformations/charges
error: Failed to create or validate: /instances/481/transformations/charges
Basic tests
√ should …
```

Stripe: Fixed input schema issue for /charges/{id}/capture API

---

src/test/elements/netsuiteerpv2/bulk.js

* Added test cases for Netsuite ERP bulk download:
- All fields query
- Only specific fields query
PS C:\Users\GS-1026> churros test elements/netsuiteerpv2 --file bulk
(node:7784) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Running tests for element: netsuiteerpv2
info: Provisioned with instance id of 87
(node:7784) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (448ms)
- docs
√ metadata (210ms)
error: Failed to delete /instances/87/transformations
√ transformations (23058ms)
bulk
error: Failed to retrieve or …

Added bulk test cases to Netuite ERP V2

---

src/test/elements/googledrive/assets/permission.json
src/test/elements/googledrive/assets/permissionUpdate.json
src/test/elements/googledrive/files.js

* Added tests for below permissions API for files.
* GET /files/permissions
* GET /files/permissions/{permissionId}
* GET /files/{id}/permissions
* GET /files/{id}/permissions/{permissionsId}
* POST /files/{id}/permissions
* POST /files/permissions
* PATCH /files/{id}/permissions/{permissionId}
* PATCH /files/permissions/{permissionId}
* DELETE /files/{id}/permissions/{permissionId}
* DELETE /files/permissions/{permissionId}
* 7 tests are failing on Staging. Have raised [DE2226](https://rally1.rallydev.com/#/144349237612d/detail/defect/240740623856?fdp=true) for the same.
* [SOBA](https://github.com/cloud-elements/soba/pull/9084)
* [RALLY-US13270](https://rally1.rallydev.com/#/144349237612d/detail/userstory/239854764612)
* [US13270](https://rally1.rallydev.com/#/144349237612d/detail/userst …

GoogleDrive : Added tests for Files Permissions API

---

src/test/elements/assets/object.definitions.json
src/test/elements/tangocard/accounts.js
src/test/elements/tangocard/assets/creditcard.json
src/test/elements/tangocard/assets/creditcard2.json
src/test/elements/tangocard/assets/creditcarddeposits.json
src/test/elements/tangocard/assets/customers.json
src/test/elements/tangocard/assets/customers2.json
src/test/elements/tangocard/assets/customersAccounts.json
src/test/elements/tangocard/assets/orders.json
src/test/elements/tangocard/assets/orders2.json
src/test/elements/tangocard/assets/transformations.json
src/test/elements/tangocard/catalogs.js
src/test/elements/tangocard/credit-cards.js
src/test/elements/tangocard/customers.js
src/test/elements/tangocard/orders.js

* Added test cases for `accounts`, `catalogs`, `customers`, `orders`, and `credit-cards` objects for Tango card
* Since there are limits for `customers` and `orders` objects and `credit-cards` are dependent `customers`, we needed to skip the tests for churros
* Screenshots for credit-cards and orders
* One API fails in orders due to order resend limit from vendor
* [SOBA](https://github.com/cloud-elements/soba/pull/9108)
* [churros-sauce](https://github.com/cloud-elements/churros-sauce/pull/214)
* [RALLY](https://rally1.rallydev.com/#/144349237612d/detail/userstory/236655542160)
* [US13175](https://rally1.rallydev.com/#/144349237612d/detail/userstory/236655542160

Tango Card - Added test cases for new element in Rewards hub

---

src/test/elements/jira/issuesecurity-schemes.js
src/test/elements/jira/notification-schemes.js
src/test/elements/jira/permission-schemes.js
src/test/elements/jira/project-categories.js
src/test/elements/jira/projects.js

* Added Testsuites for following resources:
- `issuesecurity-schemes`
- `notification-schemes`
- `permission-schemes`
- `project-categories`
* Added Test cases for following new API:
- `/projects/{id}/avatars` 
```
PS C:\Users\gs-1108\Documents\GitHub\churros> churros test elements/jira
(node:11628) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
info: Using user: pore@gslab.com
info: Using oauth username: jiradev
info: Running tests for element: jira
info: Provisioned with instance id of 575
(node:11628) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Basic tests
√ should GET /objects (5410ms)
- docs
√ metadata (362ms)
√ transformations (28150ms)
- …
```

Jira: Added churros Testsuite for dependent resources

---

src/test/elements/microsoftgraph/assets/contacts.json
src/test/elements/microsoftgraph/contacts.js
src/test/elements/outlookemail/assets/contacts.json
src/test/elements/outlookemail/assets/transformations.json
src/test/elements/outlookemail/contacts.js

* Added tests for CRUDS of Contacts API for below two elements :
* Microsoft Graph
* Microsoft Outlook
* Churros for messaging is failing because of permission issue on account to send an email.
Outlook :
Graph:
* [SOBA](https://github.com/cloud-elements/soba/pull/9157)
* [RALLY-US13357](https://rally1.rallydev.com/#/144349237612d/detail/userstory/243068459092)
* [US13357](https://rally1.rallydev.com/#/144349237612d/detail/userstory/243068459092)

Microsoft Outlook & Graph : Added tests for Contacts CRUDS

---

src/test/elements/sageone/items.js

* Added a test for the `GET /items` endpoint
* Added a test for the `GET /items/{id}` endpoint
* [SOBA](https://github.com/cloud-elements/soba/pull/9184)
* [RALLY-#US13404](https://rally1.rallydev.com/#/144349238268d/detail/userstory/244824007596)
* Closes #[US13404](https://rally1.rallydev.com/#/144349238268d/detail/userstory/244824007596)

Added integration tests for the new /items endpoint for the SageOne element

---

src/test/elements/eloqua/accounts.js
src/test/elements/eloqua/assets/accounts-update.json
src/test/elements/eloqua/assets/accounts.json
src/test/elements/eloqua/assets/contacts-update.json
src/test/elements/eloqua/assets/contacts.json
src/test/elements/eloqua/contacts.js

* Tests for Native / Custom fields
* [SOBA](https://github.com/cloud-elements/soba/pull/9186)
* [DE2334](https://rally1.rallydev.com/#/144349237612d/detail/defect/246897692744)

Added Accounts/Contacts tests for CU on native/custom fields

---

src/test/elements/sageone/vendors.js

* Ensure that the `GET /vendors` and `GET /vendors/{id}` APIs for the SageOne element are returning the full response payload.
* https://github.com/cloud-elements/soba/pull/9231
* [Jira-#SLYT-408](https://cloudelements.atlassian.net/browse/SLYT-408)
* Closes #[SLYT-408](https://cloudelements.atlassian.net/browse/SLYT-408)

Added a test to validate that the GET /vendors API's response payload

---

src/test/elements/quickbooks/assets/exchange-rates.json
src/test/elements/quickbooks/assets/journal-codes.json
src/test/elements/quickbooks/entitlements.js
src/test/elements/quickbooks/exchange-rates.js
src/test/elements/quickbooks/journal-codes.js

* Added churros tests for below resources :
* Journal Codes (CRUS)
* Credit-Terms (U)
* Entitlements (S)
* Exchange-Rates (RU)
* Journal codes test is skipped as we are not able to test the API as it is available only for France locale. As per the vendor docs, 'Applicable only for France-locale companies (FR locale)'
* Skipped update of exchange rates as it only works with account having multicurrency enabled.
* [SOBA](https://github.com/cloud-elements/soba/pull/9203)
* [RALLY-US13476](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246869751416)
* [US13476](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246869751416)

Quickbooks : Added tests for new resources

---

src/test/elements/zuorav2/productRatePlans.js
src/test/elements/zuorav2/products.js

* Added tests for GET `product-rate-plans` and GET `products/{id}/rate-plans` APIs.
* [SOBA](https://github.com/cloud-elements/soba/pull/9244)
* [Churros-ibm](https://github.com/cloud-elements/churros/pull/1734)
* [Churros-sauce-ibm](https://github.com/cloud-elements/churros-sauce/pull/221)
* [Zuorav2](https://cloudelements.atlassian.net/browse/IBM-7)

Zuorav2 tests added for two product-rate-plans APIs

---

src/test/elements/vsts/workitems.js

* Updated pagination test to `cursor` type pagination
* Removed order by test case as we no longer have the option for the resource
* [DE2357](https://rally1.rallydev.com/#/144349237612d/detail/defect/248019618728)

pagination update and removed order by test for vsts element

---

src/test/platform/docs/docs.js

* Test that the Swagger docs endpoint will use the provided `baseUrl` as its `host` value.
See comments section
* [SOBA](https://github.com/cloud-elements/soba/pull/9272)
* [RALLY-#US13645](https://rally1.rallydev.com/#/144349238268d/detail/userstory/250376904756)

Test out the base URL for swagger

---

src/test/elements/freshbooksv2/assets/expenses-create.json
src/test/elements/freshbooksv2/assets/expenses-update.json
src/test/elements/freshbooksv2/customers.js
src/test/elements/freshbooksv2/expenses.js
src/test/elements/freshbooksv2/invoices.js
src/test/elements/freshbooksv2/items.js
src/test/elements/freshbooksv2/payments.js
src/test/elements/freshbooksv2/tasks.js
src/test/elements/freshbooksv2/taxes.js
src/test/elements/freshbooksv2/vendors.js

* Added tests for `expenses` object.
* The earlier test may fail when the test for where clause may return empty responses.
So, corrected tests for following objects:
* `customers`
* `invoices`
* `items`
* `payments`
* `tasks`
* `taxes`
* `vendors`
* [SOBA](https://github.com/cloud-elements/soba/pull/9220)
* [RALLY-#${US13482}](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246880392732)
* Closes #${[US13482](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246880392732)}

Freshbooks Cloud Accounting: Added tests for expenses and corrected other tests

---

src/test/elements/salesforcemarketingcloud/contacts.js

* Added tests `DELETE /contacts` and skipped tests for `GET /contacts` as it is marked as `API NO DOC`.
* [SOBA](https://github.com/cloud-elements/soba/pull/9298)
* [Element-irs](https://github.com/cloud-elements/elements-irs/pull/28)
* [SFMC](https://cloudelements.atlassian.net/browse/IBM-19)

SFMC :  Updated test for contacts resource 

---

src/test/elements/dropboxbusiness/files.js
src/test/elements/dropboxbusiness/folders.js
src/test/elements/dropboxbusiness/namespaces.js

* Added tests for support for `team spaces` in `dropboxbusiness`
* Added test for files and folders
* Added test for new endpoint `/namespaces'
* [SOBA](https://github.com/cloud-elements/soba/pull/9283)
* [RALLY-#${US13235}]https://rally1.rallydev.com/#/144349237612d/detail/userstory/239218486112)
* Closes #${US13235}

Dropbox Business : Added test cases for Team Spaces support

---

src/test/elements/facebookleadads/assets/context-card.json
src/test/elements/facebookleadads/assets/draft-form.json
src/test/elements/facebookleadads/assets/form.json

*  Updated the payloads for `context-cards`, `draft-forms`, `forms`
* [SOBA](https://github.com/cloud-elements/soba/pull/9336)
* [elements-irs](https://github.com/cloud-elements/elements-irs/pull/39)
* [Jira](https://cloudelements.atlassian.net/browse/IBM-25)

Facebook lead ads: updated the payloads

---

src/test/elements/hubspotcrm/contacts.js

* Added test for the newly added API `GET /contacts/{userToken}/profile` 
info: Using oauth username: developer@cloud-elements.com
info: Using api key: da5693c8-48d8-4a54-90b0-9e83eb76a6fc
info: Running tests for element: hubspotcrm
Trying the portal ID: 4821991
info: Provisioned with instance id of 15
Basic tests
√ should GET /objects (339ms)
- docs
√ metadata (234ms)
√ transformations (6791ms)
accounts
√ should allow paginating with page and pageSize for /hubs/crm/accounts (2410ms)
√ should test CRUD for /accounts and GET /accounts/{id}/activities (5828ms)
√ should test accounts poller url (12251ms)
accounts/285826161/activities
- …

Added `GET /contacts/{userToken}/profile`  API test to HubSpot CRM

---

src/test/elements/fortnox/financial-years.js
src/test/elements/fortnox/voucher-series.js

* Added tests for 'voucher-series' and 'financial-years' objects.
* [SOBA](https://github.com/cloud-elements/soba/pull/9253)
* [US13486](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246881224644)
* Closes [US13486](https://rally1.rallydev.com/#/144349237612d/detail/userstory/246881224644)

added churros for the voucher-series and financial-years endpoints
